* Hadoop
#+AUTHOR: dirtysalt1987@gmai.com
#+OPTIONS: H:5

参考资源
   - Cloudera http://www.cloudera.com/
   - Apache Hadoop http://hadoop.apache.org/
   - Apache Hadoop r1.0.3 文档 http://hadoop.apache.org/common/docs/r1.0.3/
   - Apache Hadoop r1.0.3 中文文档 http://hadoop.apache.org/common/docs/r1.0.3/cn
   - CDH Downloads https://ccp.cloudera.com/display/SUPPORT/Downloads
   - CDH Documentation https://ccp.cloudera.com/display/DOC/Documentation
   - CDH Tutorial https://ccp.cloudera.com/display/SUPPORT/Hadoop+Tutorial

** FAQ
*** Hadoop可以用来做什么
Why Hadoop? http://www.cloudera.com/why-hadoop/

TODO(dirlt):translate it!!!

Simply put, Hadoop can transform the way you store and process data throughout your enterprise. According to analysts, about 80% of the data in the world is unstructured, and until Hadoop, it was essentially unusable in any systematic way. With Hadoop, for the first time you can combine all your data and look at it as one.
   - Make All Your Data Profitable. Hadoop enables you to gain insight from all the data you already have; to ingest the data flowing into your systems 24/7 and leverage it to make optimizations that were impossible before; to make decisions based on hard data, not hunches; to look at complete data, not samples; to look at years of transactions, not days or weeks. In short, Hadoop will change the way you run your organization.
   - Leverage All Types of Data, From All Types of Systems. Hadoop can handle all types of data from disparate systems: structured, unstructured, log files, pictures, audio files, communications records, email– just about anything you can think of. Even when different types of data have been stored in unrelated systems, you can dump it all into your Hadoop cluster before you even know how you might take advantage of it in the future.
   - Scale Beyond Anything You Have Today. The largest social network in the world is built on the same open-source technology as Hadoop, and now exceeds 100 petabytes. It’s unlikely your organization has that much data. As you need more capacity, you just add more commodity servers and Hadoop automatically incorporates the new storage and compute capacity.
     
*** Hadoop包括哪些组件
TODO(dirlt):translate it!!!

Apache Hadoop包括了下面这些组件：
   - [[http://hadoop.apache.org/common/][Hadoop Common]] The common utilities that support the other Hadoop subprojects.
   - [[http://hadoop.apache.org/hdfs/][Hadoop Distributed File System(HDFS)]] A distributed file system that provides high-throughput access to application data.
   - [[http://hadoop.apache.org/mapreduce/][Hadoop MapReduce]] A software framework for distributed processing of large data sets on compute clusters.
和Apache Hadoop相关的组件有：
   - [[http://avro.apache.org/][Avro]] A data serialization system.
   - [[http://cassandra.apache.org/][Cassandra]] A scalable multi-master database with no single points of failure.
   - [[http://incubator.apache.org/chukwa/][Chukwa]] A data collection system for managing large distributed systems.
   - [[http://hbase.apache.org/][HBase]] A scalable, distributed database that supports structured data storage for large tables.
   - [[http://hive.apache.org/][Hive]] A data warehouse infrastructure that provides data summarization and ad hoc querying.
   - [[http://mahout.apache.org/][Mahout]] A Scalable machine learning and data mining library.
   - [[http://pig.apache.org/][Pig]] A high-level data-flow language and execution framework for parallel computation.
   - [[http://zookeeper.apache.org/][ZooKeeper]] A high-performance coordination service for distributed applications.

*** CDH和Apache Hadoop的关系
CDH Hadoop FAQ https://ccp.cloudera.com/display/SUPPORT/Hadoop+FAQ

TODO(dirlt):translate it!!!

   - What exactly is included in CDH? / Cloudera's Distribution Including Apache Hadoop (CDH) is a certified release of Apache Hadoop. We include some stable patches scheduled to be included in future releases, as well as some patches we have developed for our supported customers, and are in the process of contributing back to Apache.
   - What license is Cloudera's Distribution Including Apache Hadoop released under? / Just like Hadoop, Cloudera's Distribution Including Apache Hadoop is released under the Apache Public License version 2.
   - Is Cloudera forking Hadoop? / Absolutely not. Cloudera is committed to the Hadoop project and the principles of the Apache Software License and Foundation. We continue to work actively with current releases of Hadoop and deliver certified releases to the community as appropriate.
   - Does Cloudera contribute their changes back to Apache? / We do, and will continue to contribute all eligible changes back to Apache. We occasionally release code we know to be stable even if our contribution to Apache is still in progress. Some of our changes are not eligible for contribution, as they capture the Cloudera brand, or link to our tools and documentation, but these do not affect compatibility with core project.

** Projects
   - [[file:./HDFS.org][HDFS]]   
