#!/bin/bash

mkdir -p www
# do publish
emacs --batch --script publish.el
./appbdstat # append baidu stat(tongji.baidu.com)

if [ $1"X" == "siteX" ]
then
    xv=123456
    tar czvf www.tar.gz www
    ./publish.exp $xv
    rm -rf www.tar.gz
fi
