#!/bin/bash

mkdir -p www
# do publish
emacs --batch --script publish.el
./appbdstat # append baidu stat(tongji.baidu.com)

if [ $1"X" == "siteX" ]
then
    PASSWD=`grep "dirlt.com.password" ~/.password | awk -F= '{print $2;}'`
    if [ $PASSWD"X" == "X" ]
    then
        echo "no password!!!"
        exit -1
    else
        echo "password=$PASSWD"
    fi
    tar czvf www.tar.gz www
    ./publish.exp $PASSWD
    rm -rf www.tar.gz
fi
