* ubuntu
#+OPTIONS: H:5

千万不要抱有一朝一兮就可以搞定的想法。最好的话身边有一个群体，大家都使用Ubuntu这个东西。
这样如果有什么问题的话，大家就比较容易找到解决办法，直到自己完全适应为止。

** 输入法
安装：
   - sudo apt-get install ibus
   - sudo apt-get install ibus-sunpinyin
   - sudo apt-get install xsunpinyin
   - sudo apt-get install python-xlib # 需要在emacs下面调用ibus

*** 切换输入法
在Preferences里面：
   - Input Method 里面添加 SubPinyin
   - 然后在General里面的Keyboard Shortcuts里面设置Enable or disable设置切换按键
     - Release+Shift_L 左边的Shift键
     - Constrol+space control和空格键
     - 这些都和windows输入法的默认配置很像。
TODO（dirlt）：在Emacs里面需要安装ibus.el以及ibus-agent。但是现在不知道为什么左边的Shift键在Emacs里面一直不能使用。

*** 自动启动输入法
另外系统默认是不会自动启动ibus的，可以在System Settings里面的Language Support里面设置Input method为ibus
这样ibus就可以自动启动了。如果emacs需要使用ibus的话，那么ibus-daemon必须先于emacs启动。可能这样agent才能够工作。

*** google docs不能输入中文
似乎sunpinyin在google docs下面工作不是很好。使用原来的pinyin就没有问题。what a shame！

** 浏览器
安装：
   - # sudo apt-get install chromium-browser # 实验性质版本
   - # sudo apt-get install google-chrome-stable # 稳定版本
   - sudo apt-get install firefox

*** 设置默认浏览器

System Settings =》 Details 里面可以设置默认浏览器。至于emacs里面的话可以使用如下配置。
#+BEGIN_SRC elisp
(setq browse-url-generic-program (executable-find "chromium-browser")
      browse-url-browser-function 'browse-url-generic)
#+END_SRC

** 邮件客户端
安装：
   - sudo apt-get install thunderbird

*** 配置gmail
   - pop3 pop.gmail.com/pop.googlmail.com SSL/TLS 995 normal password
   - smtp smtp.gmail.com/pop.googlmail.com SSL/TLS 465 normal password
   - 不过似乎现在thunderbird已经非常智能了，只要输入username以及email的话就可以自动进行配置了。nice！！！（现在看起来选择iamp模式也没有什么问题）
   - server settings => 
     - 1) leave mesages on server until I delete them. （对于imap模式来说的话，就使用默认移动到Trash下面即可）
     - 2) empty trash on exit. 
     - 3) check for new messages at startup. 
     - 4) check for new messages every 10 minutes.     
   - copies and folders => 1) cc these email addresses: dirtysalt1987@gmail.com（如果使用imap模式可以不使用）
   - composition and addressing => 1) start my reply above the quote and place my signature below the quote.

设置签名为
#+BEGIN_EXAMPLE
章炎(dirtysalt)
home:http://dirlt.com
dirtysalt1987@gmail.com
#+END_EXAMPLE

*** thunderbird的Inbox文件过大
   - http://blog.tianya.cn/blogger/post_read.asp?BlogID=3802303&PostID=35373429

在安装新的操作系统时候，可能需要将原来的邮件全部迁移过去。thunderbird迁移邮件非常方便。在C:\Documents and Settings\\Application Data\Thunderbird\Profiles\wkq5wydz.default\Mail\ 下面会有你这个pop-server对应的文件，比如Inbox(对应thunderbird的收件箱),Drafts(对应thunderbird的草稿箱）等。将这些文件直接copy过去就OK了。不得不说这点非常方便：）

但是我们会遇到一个问题就是Inbox文件太大了。而且如果我们在thunderbird下面删除收件箱里面内容的话，会发现这个Inbox文件其实没有发生变化。原因是因为thunderbird采用标记删除，所以原来的邮件内容依然是保存的（也就是说如果我们通过修改Inbox里面的标记位是可以恢复的，而且这个工作不难，因为阅读Inbox的内容就会发现里面保存的文本格式。不过谨慎选用编辑器，不要将Inbox内容全部载入不然内存会爆掉的）。 *解决这个问题非常简单，就是在thunderbird下面针对这个文件夹右键点击压缩。对于草稿箱和其他的文件夹是一样的操作。而且在thunderbird下面有工具->选项->高级->网络&磁盘空间里面，可以选择如果超过过大的话就会进行压缩。*

作为后端开发者，觉得thunderbird这样做是很正常的。有几种方式：
   1. 一种是用小碎片文件来解决，每个小碎片文件对应一个邮件，但是这样邮件太多的话性能和碎片会成为问题，但是增加和删除都非常方便
   2. 另外就是使用大文件来追加写，然后针对每封邮件进行索引。索引可以保存在内存里面并且定期dump出去，启动时候检查索引是否和文件对应，不对应的话那么可能需要增量做一部分索引。但是这样删除会成为问题，标记删除可能就是最好的办法了。所以需要用户手动或者是通过程序判断磁盘文件大小来触发压缩。
   3. 使用数据库本质上和2是一样的，只不过可以在一定程度上简化代码。在删除方便可能还是使用压缩删除。如果是我自己做的话那么可能考虑使用sqlite来做。单机可以embed,并且通过SQL来进行检索或者是其他操作。

NOTE（dirlt）：其实thunderbird超过一定大小就会自动提醒是否需要压缩

** 虚拟机
安装
   - sudo apt-get install virtualbox
   - sudo apt-get install virtualbox-guest-additions # 设置windows虚拟机共享文件夹

*** 安装windows虚拟机
安装windows虚拟机主要是为了方便一些需要在windows下面完成的操作，比如U盾。
另外windows下面也有一些第三方的软件在Linux下面比较匮乏比如EverBox，
虽然DropBox也非常不错但是相对来说还是国内服务器会比较好一些。

使用virtualbox，通过加载windows xp的镜像安装，这个非常简单。
或者是直接使用别人生成好的.vdi文件。vdi全称应该是virtual disk image。

*** windows虚拟机共享文件夹
设置共享文件夹主要是为了数据可以进行同步。通过windows虚拟机，安装同步软件比如GDrive。
然后通过共享文件夹，将GDrive的同步目录隐射到Linux文件系统上面，完成数据同步。

   - 首先挂载VBoxAdditions.iso,这个文件在/usr/share/virtualbox下面
   - 之后就会在虚拟机里面提示安装相关的驱动程序。
   - 完成之后在设置virtualbox的settings/share folder，创建本地share folder
   - 然后进入虚拟机“我的电脑”右键选择映射网络驱动器，通过浏览可以找到对应的网络驱动器。
   
我是参考这篇图文并茂的文章的 http://hi.baidu.com/hifinan/item/79f22545a8400ed3c1a592f3

*** virtualbox使用U盾
首先需要在 https://www.virtualbox.org/wiki/Downloads VirtualBox Extension Pack，双击执行。
在Settings =》 USB选项里面勾选 Enable USB Controller 和 Enable USB2.0（EHCI） Controller。

然后我们需要添加vboxusers这个群组，同时将自己加入到这个群组内：
   - sudo groupadd vboxusers
   - sudo gpasswd -a dirlt vboxusers
接着重新启动ubuntu。

接着Settings =》 USB里面添加那些已经识别的设备，接着启动windows虚拟机就可以使用U盾了。

** 外观和快捷键
*** 常用快捷键
   - Ctrl+Alt+T // 打开一个terminal。
   - Ctrl+Alt+上下左右 // 在不同的workspace之间切换。
   - 
*** 调整字体大小
System Settings =》 Universal Access里面的Seeing部分可以用来调整字体大小。但是只有等级没有具体的数字可以进行调整。
可以通过安装gnome-tweak-tool并且运行之来进行微调。

参考链接 http://ltek.dyndns.org/wordpress/?p=282

** 系统管理
*** 重启机器
似乎Ubuntu下面限制用户进行重启，所以要重启的话可以执行sudo reboot.

*** 重启unity
unity restart &

** 窗口管理器
*** gnome
安装：
   - gnome-shell # gnome窗口管理器

** 开发和娱乐
安装：
   - sudo apt-get install vlc # 视频
   - sudo apt-get install pidgin # 聊天
   - # sudo apt-get install stardict # 词典
   - sudo apt-get install amarok # 音乐
   - sudo apt-get install okular # pdf阅读
   - sudo apt-get install git
   - sudo apt-get install subversion
   - sudo apt-get install htop
   - sudo apt-get install dstat
   - sudo apt-get install sysstat
   - sudo apt-get install httperf
   - sudo apt-get install rsync
   - sudp apt-get install tree
   - sudo apt-get install tcpdump
   - sudo apt-get install clusterssh
   - sudo apt-get install libjs-extjs
   - sudo apt-get install libjs-extjs-doc
   - sudo apt-get install openssh-server
   - sudo apt-get install sqlite3
   - sudo apt-get install eclipse
   - sudo apt-get install python-dev
   - sudo apt-get install libevent-dev
   - sudo apt-get install python-gevent
   - sudo apt-get install python-gevent-doc
   - sudo apt-get install gunicorn
   - sudo apt-get install recordmydesktop # 录制桌面
   - sudo apt-get install maven2
   - sudo apt-get install ttyload
   - sudo apt-get install autoconf
   - sudo apt-get install libtool
   - sudo apt-get install automake
   - sudo apt-get install alien
   - sudo apt-get install dos2unix
   - sudo apt-get install astyle
   - sudo apt-get install valgrind
   - sudo apt-get install mongodb
   - sudo apt-get install python-imaging
   - sudo apt-get install python-imaging-doc
   - sudo apt-get install screen
   - sudo apt-get install python-pychart
   - sudo apt-get install python-pychart-doc
   - sudo apt-get install python-doc
   - sudo apt-get install python-setuptools

*** amarok循环播放
在amarok的右下角有task progression的图标，选择repeat track即可。

*** deb安装文件列表
通常我们不太清楚一个deb安装了哪些文件，尤其是doc的话可能不知道放置在什么位置上面。

我们可以通过搜索引擎查找这个包，然后在 http://packages.ubuntu.com 下面找到这个包以及对应的文件列表信息。

doc存放位置通常在/usr/share/doc/<package>/下面。

*** deb包管理
--------------------

*deb和rpm包转换*

   - 安装alien
   - rpm转deb sudo alien -d test.rpm
   - deb转rpm sudo alien -r test.deb

看了一下alien的help还可和下面几个包格式互转
   - slp
   - lsb
   - tgz
   - pkg

甚至可以直接调用alien -i test.rpm直接安装而不需要转换。

--------------------

*安装deb*

sudo dpkg -i test.deb

