* Ubuntu
#+AUTHOR: dirtysalt1987@gmail.com
#+OPTIONS: H:5

千万不要抱有一朝一兮就可以搞定的想法。最好的话身边有一个群体，大家都使用Ubuntu这个东西。
这样如果有什么问题的话，大家就比较容易找到解决办法，直到自己完全适应为止。

** 输入法
安装：
   - sudo apt-get install ibus
   - sudo apt-get install ibus-sunpinyin
   - sudo apt-get install python-xlib # 需要在emacs下面调用ibus

*** 切换输入法
在Preferences里面：
   - Input Method 里面添加 SubPinyin
   - 然后在General里面的Keyboard Shortcuts里面设置Enable or disable设置切换按键
     - Release+Shift_L 左边的Shift键
     - Constrol+space control和空格键
     - 这些都和windows输入法的默认配置很像。
TODO（dirlt）：在Emacs里面需要安装ibus.el以及ibus-agent。但是现在不知道为什么左边的Shift键在Emacs里面一直不能使用。

*** 自动启动输入法
另外系统默认是不会自动启动ibus的，可以在System Settings里面的Language Support里面设置Input method为ibus
这样ibus就可以自动启动了。如果emacs需要使用ibus的话，那么ibus-daemon必须先于emacs启动。可能这样agent才能够工作。

** 浏览器
安装：
   - sudo apt-get install chromium-browser # 实验性质版本
   - sudo apt-get install google-chrome-stable # 稳定版本
   - sudo apt-get install firefox

*** 设置默认浏览器

System Settings =》 Details 里面可以设置默认浏览器。至于emacs里面的话可以使用如下配置。
#+BEGIN_SRC elisp
(setq browse-url-generic-program (executable-find "chromium-browser")
      browse-url-browser-function 'browse-url-generic)
#+END_SRC

** 邮件客户端
安装：
   - sudo apt-get install thunderbird

*** 配置gmail
   - pop3 pop.gmail.com SSL/TLS 995 normal password
   - smtp smtp.gmail.com SSL/TLS 465 normal password
   - server settings => 1) leave mesages on server until I delete them. 2) empty trash on exit. 3) check for new messages at startup. 4) check for new messages every 10 minutes.
   - copies and folders => 1) cc these email addresses: dirtysalt1987@gmail.com
   - composition and addressing => 1) start my reply above the quote and place my signature below the quote.

设置签名为
#+BEGIN_EXAMPLE
章炎(dirtysalt)
home:http://dirlt.com
dirtysalt1987@gmail.com
#+END_EXAMPLE

** 虚拟机
安装
   - sudo apt-get install virtualbox
   - sudo apt-get install virtualbox-guest-additions # 设置windows虚拟机共享文件夹

*** 安装windows虚拟机
安装windows虚拟机主要是为了方便一些需要在windows下面完成的操作，比如U盾。
另外windows下面也有一些第三方的软件在Linux下面比较匮乏比如EverBox，
虽然DropBox也非常不错但是相对来说还是国内服务器会比较好一些。

使用virtualbox，通过加载windows xp的镜像安装，这个非常简单。
或者是直接使用别人生成好的.vdi文件。vdi全称应该是virtual disk image。

*** windows虚拟机共享文件夹
设置共享文件夹主要是为了数据可以进行同步。通过windows虚拟机，安装同步软件比如GDrive。
然后通过共享文件夹，将GDrive的同步目录隐射到Linux文件系统上面，完成数据同步。

   - 首先挂载VBoxAdditions.iso,这个文件在/usr/share/virtualbox下面
   - 之后就会在虚拟机里面提示安装相关的驱动程序。
   - 完成之后在设置virtualbox的settings/share folder，创建本地share folder
   - 然后进入虚拟机“我的电脑”右键选择映射网络驱动器，通过浏览可以找到对应的网络驱动器。
   
我是参考这篇图文并茂的文章的 http://hi.baidu.com/hifinan/item/79f22545a8400ed3c1a592f3

*** virtualbox使用U盾
首先需要在 https://www.virtualbox.org/wiki/Downloads VirtualBox Extension Pack，双击执行。
在Settings =》 USB选项里面勾选 Enable USB Controller 和 Enable USB2.0（EHCI） Controller。

然后我们需要添加vboxusers这个群组，同时将自己加入到这个群组内：
   - sudo groupadd vboxusers
   - sudo gpasswd -a dirlt vboxusers
接着重新启动ubuntu。

接着Settings =》 USB里面添加那些已经识别的设备，接着启动windows虚拟机就可以使用U盾了。

** 外观和快捷键
*** 常用快捷键
   - Ctrl+Alt+T // 打开一个terminal。
   - Ctrl+Alt+上下左右 // 在不同的workspace之间切换。
   - 
*** 调整字体大小
System Settings =》 Universal Access里面的Seeing部分可以用来调整字体大小。但是只有等级没有具体的数字可以进行调整。
可以通过安装gnome-tweak-tool并且运行之来进行微调。

参考链接 http://ltek.dyndns.org/wordpress/?p=282

** 系统管理
*** 重启机器
似乎Ubuntu下面限制用户进行重启，所以要重启的话可以执行sudo reboot.

*** 重启unity
unity restart &

** 窗口管理器
*** gnome
安装：
   - gnome-shell # gnome窗口管理器

** 开发和娱乐
安装：
   - sudo apt-get install vlc # 视频
   - sudo apt-get install pidgin # 聊天
   - sudo apt-get install stardict # 词典
   - sudo apt-get install amarok # 音乐
   - sudo apt-get install git
   - sudo apt-get install subversion
   - sudo apt-get install htop
   - sudo apt-get install dstat
   - sudo apt-get install sysstat
   - sudo apt-get install httperf
   - sudo apt-get install rsync
   - sudp apt-get install tree
   - sudo apt-get install tcpdump


*** amarok循环播放
在amarok的右下角有task progression的图标，选择repeat track即可。

