#!/usr/bin/env python
#coding:gbk
#Copyright (C) dirlt

import os
env=Environment(CPPPATH=['../../'],
                CXXFLAGS='-W -Wall -g -Werror -O2 -DDEBUG -fPIC',
                LIBPATH=['../',
                         '../../common'],
                LIBS=['sasuke',
                      'common',
                      'zmq', # zeromq
                      'protobuf', # protobuf
                      'uuid',
                      'pthread'])

env.Program('rpc_client',
            ['rpc_client.cc',
             'echo.pb.cc'])

env.Program('rpc_server',
            ['rpc_server.cc',
             'echo.pb.cc'])

env.Program('test_zmq',
            ['test_zmq.cc'])

