// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/message.proto

package com.dirlt.java.FastHbaseRest;

public final class MessageProtos1 {
  private MessageProtos1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage {
    // Use Request.newBuilder() to construct.
    private Request() {
      initFields();
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dirlt.java.FastHbaseRest.MessageProtos1.internal_static_com_dirlt_java_FastHbaseRest_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dirlt.java.FastHbaseRest.MessageProtos1.internal_static_com_dirlt_java_FastHbaseRest_Request_fieldAccessorTable;
    }
    
    // required string table_name = 1;
    public static final int TABLE_NAME_FIELD_NUMBER = 1;
    private boolean hasTableName;
    private java.lang.String tableName_ = "";
    public boolean hasTableName() { return hasTableName; }
    public java.lang.String getTableName() { return tableName_; }
    
    // required string row_key = 2;
    public static final int ROW_KEY_FIELD_NUMBER = 2;
    private boolean hasRowKey;
    private java.lang.String rowKey_ = "";
    public boolean hasRowKey() { return hasRowKey; }
    public java.lang.String getRowKey() { return rowKey_; }
    
    // required string column_family = 3;
    public static final int COLUMN_FAMILY_FIELD_NUMBER = 3;
    private boolean hasColumnFamily;
    private java.lang.String columnFamily_ = "";
    public boolean hasColumnFamily() { return hasColumnFamily; }
    public java.lang.String getColumnFamily() { return columnFamily_; }
    
    // repeated string qualifiers = 5;
    public static final int QUALIFIERS_FIELD_NUMBER = 5;
    private java.util.List<java.lang.String> qualifiers_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getQualifiersList() {
      return qualifiers_;
    }
    public int getQualifiersCount() { return qualifiers_.size(); }
    public java.lang.String getQualifiers(int index) {
      return qualifiers_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasTableName) return false;
      if (!hasRowKey) return false;
      if (!hasColumnFamily) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasTableName()) {
        output.writeString(1, getTableName());
      }
      if (hasRowKey()) {
        output.writeString(2, getRowKey());
      }
      if (hasColumnFamily()) {
        output.writeString(3, getColumnFamily());
      }
      for (java.lang.String element : getQualifiersList()) {
        output.writeString(5, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTableName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getTableName());
      }
      if (hasRowKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getRowKey());
      }
      if (hasColumnFamily()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getColumnFamily());
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getQualifiersList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getQualifiersList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dirlt.java.FastHbaseRest.MessageProtos1.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.dirlt.java.FastHbaseRest.MessageProtos1.Request result;
      
      // Construct using com.dirlt.java.FastHbaseRest.MessageProtos1.Request.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.dirlt.java.FastHbaseRest.MessageProtos1.Request();
        return builder;
      }
      
      protected com.dirlt.java.FastHbaseRest.MessageProtos1.Request internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.dirlt.java.FastHbaseRest.MessageProtos1.Request();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dirlt.java.FastHbaseRest.MessageProtos1.Request.getDescriptor();
      }
      
      public com.dirlt.java.FastHbaseRest.MessageProtos1.Request getDefaultInstanceForType() {
        return com.dirlt.java.FastHbaseRest.MessageProtos1.Request.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.dirlt.java.FastHbaseRest.MessageProtos1.Request build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.dirlt.java.FastHbaseRest.MessageProtos1.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.dirlt.java.FastHbaseRest.MessageProtos1.Request buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.qualifiers_ != java.util.Collections.EMPTY_LIST) {
          result.qualifiers_ =
            java.util.Collections.unmodifiableList(result.qualifiers_);
        }
        com.dirlt.java.FastHbaseRest.MessageProtos1.Request returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dirlt.java.FastHbaseRest.MessageProtos1.Request) {
          return mergeFrom((com.dirlt.java.FastHbaseRest.MessageProtos1.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dirlt.java.FastHbaseRest.MessageProtos1.Request other) {
        if (other == com.dirlt.java.FastHbaseRest.MessageProtos1.Request.getDefaultInstance()) return this;
        if (other.hasTableName()) {
          setTableName(other.getTableName());
        }
        if (other.hasRowKey()) {
          setRowKey(other.getRowKey());
        }
        if (other.hasColumnFamily()) {
          setColumnFamily(other.getColumnFamily());
        }
        if (!other.qualifiers_.isEmpty()) {
          if (result.qualifiers_.isEmpty()) {
            result.qualifiers_ = new java.util.ArrayList<java.lang.String>();
          }
          result.qualifiers_.addAll(other.qualifiers_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setTableName(input.readString());
              break;
            }
            case 18: {
              setRowKey(input.readString());
              break;
            }
            case 26: {
              setColumnFamily(input.readString());
              break;
            }
            case 42: {
              addQualifiers(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string table_name = 1;
      public boolean hasTableName() {
        return result.hasTableName();
      }
      public java.lang.String getTableName() {
        return result.getTableName();
      }
      public Builder setTableName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTableName = true;
        result.tableName_ = value;
        return this;
      }
      public Builder clearTableName() {
        result.hasTableName = false;
        result.tableName_ = getDefaultInstance().getTableName();
        return this;
      }
      
      // required string row_key = 2;
      public boolean hasRowKey() {
        return result.hasRowKey();
      }
      public java.lang.String getRowKey() {
        return result.getRowKey();
      }
      public Builder setRowKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRowKey = true;
        result.rowKey_ = value;
        return this;
      }
      public Builder clearRowKey() {
        result.hasRowKey = false;
        result.rowKey_ = getDefaultInstance().getRowKey();
        return this;
      }
      
      // required string column_family = 3;
      public boolean hasColumnFamily() {
        return result.hasColumnFamily();
      }
      public java.lang.String getColumnFamily() {
        return result.getColumnFamily();
      }
      public Builder setColumnFamily(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasColumnFamily = true;
        result.columnFamily_ = value;
        return this;
      }
      public Builder clearColumnFamily() {
        result.hasColumnFamily = false;
        result.columnFamily_ = getDefaultInstance().getColumnFamily();
        return this;
      }
      
      // repeated string qualifiers = 5;
      public java.util.List<java.lang.String> getQualifiersList() {
        return java.util.Collections.unmodifiableList(result.qualifiers_);
      }
      public int getQualifiersCount() {
        return result.getQualifiersCount();
      }
      public java.lang.String getQualifiers(int index) {
        return result.getQualifiers(index);
      }
      public Builder setQualifiers(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.qualifiers_.set(index, value);
        return this;
      }
      public Builder addQualifiers(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.qualifiers_.isEmpty()) {
          result.qualifiers_ = new java.util.ArrayList<java.lang.String>();
        }
        result.qualifiers_.add(value);
        return this;
      }
      public Builder addAllQualifiers(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.qualifiers_.isEmpty()) {
          result.qualifiers_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.qualifiers_);
        return this;
      }
      public Builder clearQualifiers() {
        result.qualifiers_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dirlt.java.FastHbaseRest.Request)
    }
    
    static {
      defaultInstance = new Request(true);
      com.dirlt.java.FastHbaseRest.MessageProtos1.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dirlt.java.FastHbaseRest.Request)
  }
  
  public static final class Response extends
      com.google.protobuf.GeneratedMessage {
    // Use Response.newBuilder() to construct.
    private Response() {
      initFields();
    }
    private Response(boolean noInit) {}
    
    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dirlt.java.FastHbaseRest.MessageProtos1.internal_static_com_dirlt_java_FastHbaseRest_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dirlt.java.FastHbaseRest.MessageProtos1.internal_static_com_dirlt_java_FastHbaseRest_Response_fieldAccessorTable;
    }
    
    public static final class KeyValue extends
        com.google.protobuf.GeneratedMessage {
      // Use KeyValue.newBuilder() to construct.
      private KeyValue() {
        initFields();
      }
      private KeyValue(boolean noInit) {}
      
      private static final KeyValue defaultInstance;
      public static KeyValue getDefaultInstance() {
        return defaultInstance;
      }
      
      public KeyValue getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dirlt.java.FastHbaseRest.MessageProtos1.internal_static_com_dirlt_java_FastHbaseRest_Response_KeyValue_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dirlt.java.FastHbaseRest.MessageProtos1.internal_static_com_dirlt_java_FastHbaseRest_Response_KeyValue_fieldAccessorTable;
      }
      
      // required string qualifier = 1;
      public static final int QUALIFIER_FIELD_NUMBER = 1;
      private boolean hasQualifier;
      private java.lang.String qualifier_ = "";
      public boolean hasQualifier() { return hasQualifier; }
      public java.lang.String getQualifier() { return qualifier_; }
      
      // required bytes content = 3;
      public static final int CONTENT_FIELD_NUMBER = 3;
      private boolean hasContent;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasContent() { return hasContent; }
      public com.google.protobuf.ByteString getContent() { return content_; }
      
      private void initFields() {
      }
      public final boolean isInitialized() {
        if (!hasQualifier) return false;
        if (!hasContent) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasQualifier()) {
          output.writeString(1, getQualifier());
        }
        if (hasContent()) {
          output.writeBytes(3, getContent());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasQualifier()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getQualifier());
        }
        if (hasContent()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getContent());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue result;
        
        // Construct using com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue();
          return builder;
        }
        
        protected com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue.getDescriptor();
        }
        
        public com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue getDefaultInstanceForType() {
          return com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue) {
            return mergeFrom((com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue other) {
          if (other == com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue.getDefaultInstance()) return this;
          if (other.hasQualifier()) {
            setQualifier(other.getQualifier());
          }
          if (other.hasContent()) {
            setContent(other.getContent());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setQualifier(input.readString());
                break;
              }
              case 26: {
                setContent(input.readBytes());
                break;
              }
            }
          }
        }
        
        
        // required string qualifier = 1;
        public boolean hasQualifier() {
          return result.hasQualifier();
        }
        public java.lang.String getQualifier() {
          return result.getQualifier();
        }
        public Builder setQualifier(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasQualifier = true;
          result.qualifier_ = value;
          return this;
        }
        public Builder clearQualifier() {
          result.hasQualifier = false;
          result.qualifier_ = getDefaultInstance().getQualifier();
          return this;
        }
        
        // required bytes content = 3;
        public boolean hasContent() {
          return result.hasContent();
        }
        public com.google.protobuf.ByteString getContent() {
          return result.getContent();
        }
        public Builder setContent(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasContent = true;
          result.content_ = value;
          return this;
        }
        public Builder clearContent() {
          result.hasContent = false;
          result.content_ = getDefaultInstance().getContent();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:com.dirlt.java.FastHbaseRest.Response.KeyValue)
      }
      
      static {
        defaultInstance = new KeyValue(true);
        com.dirlt.java.FastHbaseRest.MessageProtos1.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:com.dirlt.java.FastHbaseRest.Response.KeyValue)
    }
    
    // required string table_name = 1;
    public static final int TABLE_NAME_FIELD_NUMBER = 1;
    private boolean hasTableName;
    private java.lang.String tableName_ = "";
    public boolean hasTableName() { return hasTableName; }
    public java.lang.String getTableName() { return tableName_; }
    
    // required string row_key = 2;
    public static final int ROW_KEY_FIELD_NUMBER = 2;
    private boolean hasRowKey;
    private java.lang.String rowKey_ = "";
    public boolean hasRowKey() { return hasRowKey; }
    public java.lang.String getRowKey() { return rowKey_; }
    
    // required string column_family = 3;
    public static final int COLUMN_FAMILY_FIELD_NUMBER = 3;
    private boolean hasColumnFamily;
    private java.lang.String columnFamily_ = "";
    public boolean hasColumnFamily() { return hasColumnFamily; }
    public java.lang.String getColumnFamily() { return columnFamily_; }
    
    // repeated .com.dirlt.java.FastHbaseRest.Response.KeyValue kvs = 5;
    public static final int KVS_FIELD_NUMBER = 5;
    private java.util.List<com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue> kvs_ =
      java.util.Collections.emptyList();
    public java.util.List<com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue> getKvsList() {
      return kvs_;
    }
    public int getKvsCount() { return kvs_.size(); }
    public com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue getKvs(int index) {
      return kvs_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasTableName) return false;
      if (!hasRowKey) return false;
      if (!hasColumnFamily) return false;
      for (com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue element : getKvsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasTableName()) {
        output.writeString(1, getTableName());
      }
      if (hasRowKey()) {
        output.writeString(2, getRowKey());
      }
      if (hasColumnFamily()) {
        output.writeString(3, getColumnFamily());
      }
      for (com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue element : getKvsList()) {
        output.writeMessage(5, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTableName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getTableName());
      }
      if (hasRowKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getRowKey());
      }
      if (hasColumnFamily()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getColumnFamily());
      }
      for (com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue element : getKvsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dirlt.java.FastHbaseRest.MessageProtos1.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dirlt.java.FastHbaseRest.MessageProtos1.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.dirlt.java.FastHbaseRest.MessageProtos1.Response result;
      
      // Construct using com.dirlt.java.FastHbaseRest.MessageProtos1.Response.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.dirlt.java.FastHbaseRest.MessageProtos1.Response();
        return builder;
      }
      
      protected com.dirlt.java.FastHbaseRest.MessageProtos1.Response internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.dirlt.java.FastHbaseRest.MessageProtos1.Response();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dirlt.java.FastHbaseRest.MessageProtos1.Response.getDescriptor();
      }
      
      public com.dirlt.java.FastHbaseRest.MessageProtos1.Response getDefaultInstanceForType() {
        return com.dirlt.java.FastHbaseRest.MessageProtos1.Response.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.dirlt.java.FastHbaseRest.MessageProtos1.Response build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.dirlt.java.FastHbaseRest.MessageProtos1.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.dirlt.java.FastHbaseRest.MessageProtos1.Response buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.kvs_ != java.util.Collections.EMPTY_LIST) {
          result.kvs_ =
            java.util.Collections.unmodifiableList(result.kvs_);
        }
        com.dirlt.java.FastHbaseRest.MessageProtos1.Response returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dirlt.java.FastHbaseRest.MessageProtos1.Response) {
          return mergeFrom((com.dirlt.java.FastHbaseRest.MessageProtos1.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dirlt.java.FastHbaseRest.MessageProtos1.Response other) {
        if (other == com.dirlt.java.FastHbaseRest.MessageProtos1.Response.getDefaultInstance()) return this;
        if (other.hasTableName()) {
          setTableName(other.getTableName());
        }
        if (other.hasRowKey()) {
          setRowKey(other.getRowKey());
        }
        if (other.hasColumnFamily()) {
          setColumnFamily(other.getColumnFamily());
        }
        if (!other.kvs_.isEmpty()) {
          if (result.kvs_.isEmpty()) {
            result.kvs_ = new java.util.ArrayList<com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue>();
          }
          result.kvs_.addAll(other.kvs_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setTableName(input.readString());
              break;
            }
            case 18: {
              setRowKey(input.readString());
              break;
            }
            case 26: {
              setColumnFamily(input.readString());
              break;
            }
            case 42: {
              com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue.Builder subBuilder = com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addKvs(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required string table_name = 1;
      public boolean hasTableName() {
        return result.hasTableName();
      }
      public java.lang.String getTableName() {
        return result.getTableName();
      }
      public Builder setTableName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTableName = true;
        result.tableName_ = value;
        return this;
      }
      public Builder clearTableName() {
        result.hasTableName = false;
        result.tableName_ = getDefaultInstance().getTableName();
        return this;
      }
      
      // required string row_key = 2;
      public boolean hasRowKey() {
        return result.hasRowKey();
      }
      public java.lang.String getRowKey() {
        return result.getRowKey();
      }
      public Builder setRowKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRowKey = true;
        result.rowKey_ = value;
        return this;
      }
      public Builder clearRowKey() {
        result.hasRowKey = false;
        result.rowKey_ = getDefaultInstance().getRowKey();
        return this;
      }
      
      // required string column_family = 3;
      public boolean hasColumnFamily() {
        return result.hasColumnFamily();
      }
      public java.lang.String getColumnFamily() {
        return result.getColumnFamily();
      }
      public Builder setColumnFamily(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasColumnFamily = true;
        result.columnFamily_ = value;
        return this;
      }
      public Builder clearColumnFamily() {
        result.hasColumnFamily = false;
        result.columnFamily_ = getDefaultInstance().getColumnFamily();
        return this;
      }
      
      // repeated .com.dirlt.java.FastHbaseRest.Response.KeyValue kvs = 5;
      public java.util.List<com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue> getKvsList() {
        return java.util.Collections.unmodifiableList(result.kvs_);
      }
      public int getKvsCount() {
        return result.getKvsCount();
      }
      public com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue getKvs(int index) {
        return result.getKvs(index);
      }
      public Builder setKvs(int index, com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.kvs_.set(index, value);
        return this;
      }
      public Builder setKvs(int index, com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue.Builder builderForValue) {
        result.kvs_.set(index, builderForValue.build());
        return this;
      }
      public Builder addKvs(com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.kvs_.isEmpty()) {
          result.kvs_ = new java.util.ArrayList<com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue>();
        }
        result.kvs_.add(value);
        return this;
      }
      public Builder addKvs(com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue.Builder builderForValue) {
        if (result.kvs_.isEmpty()) {
          result.kvs_ = new java.util.ArrayList<com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue>();
        }
        result.kvs_.add(builderForValue.build());
        return this;
      }
      public Builder addAllKvs(
          java.lang.Iterable<? extends com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue> values) {
        if (result.kvs_.isEmpty()) {
          result.kvs_ = new java.util.ArrayList<com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue>();
        }
        super.addAll(values, result.kvs_);
        return this;
      }
      public Builder clearKvs() {
        result.kvs_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dirlt.java.FastHbaseRest.Response)
    }
    
    static {
      defaultInstance = new Response(true);
      com.dirlt.java.FastHbaseRest.MessageProtos1.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dirlt.java.FastHbaseRest.Response)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dirlt_java_FastHbaseRest_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dirlt_java_FastHbaseRest_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dirlt_java_FastHbaseRest_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dirlt_java_FastHbaseRest_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dirlt_java_FastHbaseRest_Response_KeyValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dirlt_java_FastHbaseRest_Response_KeyValue_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/proto/message.proto\022\034com.dirl" +
      "t.java.FastHbaseRest\"Y\n\007Request\022\022\n\ntable" +
      "_name\030\001 \002(\t\022\017\n\007row_key\030\002 \002(\t\022\025\n\rcolumn_f" +
      "amily\030\003 \002(\t\022\022\n\nqualifiers\030\005 \003(\t\"\264\001\n\010Resp" +
      "onse\022\022\n\ntable_name\030\001 \002(\t\022\017\n\007row_key\030\002 \002(" +
      "\t\022\025\n\rcolumn_family\030\003 \002(\t\022<\n\003kvs\030\005 \003(\0132/." +
      "com.dirlt.java.FastHbaseRest.Response.Ke" +
      "yValue\032.\n\010KeyValue\022\021\n\tqualifier\030\001 \002(\t\022\017\n" +
      "\007content\030\003 \002(\014B\020B\016MessageProtos1"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_dirlt_java_FastHbaseRest_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_dirlt_java_FastHbaseRest_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dirlt_java_FastHbaseRest_Request_descriptor,
              new java.lang.String[] { "TableName", "RowKey", "ColumnFamily", "Qualifiers", },
              com.dirlt.java.FastHbaseRest.MessageProtos1.Request.class,
              com.dirlt.java.FastHbaseRest.MessageProtos1.Request.Builder.class);
          internal_static_com_dirlt_java_FastHbaseRest_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_dirlt_java_FastHbaseRest_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dirlt_java_FastHbaseRest_Response_descriptor,
              new java.lang.String[] { "TableName", "RowKey", "ColumnFamily", "Kvs", },
              com.dirlt.java.FastHbaseRest.MessageProtos1.Response.class,
              com.dirlt.java.FastHbaseRest.MessageProtos1.Response.Builder.class);
          internal_static_com_dirlt_java_FastHbaseRest_Response_KeyValue_descriptor =
            internal_static_com_dirlt_java_FastHbaseRest_Response_descriptor.getNestedTypes().get(0);
          internal_static_com_dirlt_java_FastHbaseRest_Response_KeyValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dirlt_java_FastHbaseRest_Response_KeyValue_descriptor,
              new java.lang.String[] { "Qualifier", "Content", },
              com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue.class,
              com.dirlt.java.FastHbaseRest.MessageProtos1.Response.KeyValue.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
