* diary
** 2012-7-26
*** 组织邮件和列表
今天思考了一下应该如何组织邮件和阅读列表。虽然身边的人都习惯使用gmail web以及google reader方式来处理邮件和阅读rss，
但是我不是非常习惯这种操作方式，还是更加prefer本地操作。但是这样会带来一个问题就是，如果你配备了一台新的电脑的话，那么你需要
花非常多的时间进行配置。好比如果原来在你的电脑上面设置了过滤器或者是标签的话，重新设置还是会比较麻烦的。另外就是过滤器以及标签
这件事情本来就非常耗时间。做过滤器以及标签的方式无非就是希望以后可以很方便地进行搜索并且安排todo事项。

我决定最后的做法还是这样的：
   - 首先还是使用客户端thunderbird来进行邮件处理和RSS阅读。
   - 客户端还是使用pop3方式来接受和处理邮件。
   - 我们不对客户端做过多的设置。不设置任何过滤器以及标签。
     - 如果一封邮件需要稍后处理的话，那么添加到自己的todolist里面去。
     - 如果一封邮件里面包含比较有价值的信息的话，通常可以将其加入到自己的todolist里面去并且附上有价值的信息。
这样一来所有的工作都依赖于todolist。开始可以使用简单的方式来维护todolist,之后的话可以考虑好好学习org-mode。

对于rss来说可能还需要考虑在线阅读方式，因为老婆在天津周末都过去，但是不一定带上笔记本。在她的电脑上面通常不需要
编辑过多的内容，大部分还是浏览内容然后可以通过写邮件的方式将阅读的内容整理起来邮件发送给自己。所以最好可以有一个在线阅读rss方式。
现在看来网易云阅读似乎是一个不错的选择，有客户端可以在ipad上面阅读内容。

*** firefox收藏栏
firefox的收藏栏相对于chrome确实好用：
   - 对于刚看到的一篇文章可能不希望直接打上tag，可以通过托拽的方式拖到bookmark toolbar上面。
   - 之后如果决定需要收藏的话，那么可以直接Ctrl+D进行收藏，默认是收藏到bookmark menus里面去，并且焦点在tags上面，输入回车即可。

** 2012-7-27
*** 书签整理
关于书签这个tag来说，其实大部分不用打，因为标题信息已经十分丰富可以很容易地找到，同时firefox也会从链接中提取一些description来方便检索。
所以打tag大部分是因为，如果以后想检索到这个书签的话我们可能希望使用什么关键字来进行检索，这个关键字是否出现在标题内部。如果没有出现在标题
内部的话，那么打上这个tag还是十分有必要的。当然如果不怕麻烦的话，也可以在tag里面做一些冗余信息。

** 2012-7-30
*** firemacs配置
原来firemacs的配置放在了pref.js里面（可以通过about:config察看到），所以应该是可以进行同步的。
但是有个问题就是，这个配置必须等待firefox正常关闭之后才会生效，否则只是存在于Cache里面，这点非常重要。
所以如果修改了firemacs配置的话，尽可能重启一次确保修改写入了配置。

NOTE（dirlt）：似乎配置文件并没有进行同步。看来还必须自己同步pref.js这个文件了？OMG。不过现在看起来
自己机器数量还非常少，在各个地方稍微简单配置一下即可，没有必要始终同步。

*** wget断点续传
使用wget -c就可以使用断点续传功能，但是这个似乎需要服务器端的支持。服务器需要支持从某一个offset读取文件。

** 2012-7-31
*** 一种阅读方式
今天突然发现了一种很好的阅读方式
   - 首先下载ff的clearly插件。这个插件可以很做一些排版工作去除掉网站中一些无意义的内容比如广告等。
   - 然后使用Ctrl+P将其打印成为pdf格式保存下来阅读（或者是将其clip to evenote上阅读）

*** 2012Q3 OKR
   - 参与线上线下统计分析逻辑整合和后端改造工作 30%
   - 数据平台调度器的设计实现和上线，满足目前的需求 30%
   - 统计分析3.0设计和实现 20%
   - 数据平台数据流改造，kafka直接写入hdfs 10%
   - hadoop/hbase加深了解 10%

** 2012-8-2
*** 关于信息整理
关于信息整理的话，最近又有一些想法。

就我现在来说信息整理大致放在这些地方：
   - github // 这上面都是放org-mode整理的东西。这里记录一些笔记或者是琐碎的东西比较方便，或者是网上之言片语。
   - blog（wordpress) // 现在考虑把这个部分扯下来，归并如github里面。考虑废弃。
   - firefox bookmark // 这些收藏通常是一些信息的东西。这些信息可能是搞笑的，或者是视频。
   - evernote // 网上还会存在一些信息，内容可能非常有用你想保留下来，通常是文字或者是知识
   - everbox // 这些存放的都是文档比如doc，ppt，pdf等。可以是自己生产的，也可以从邮件或者是网上down下来的。

bookmark比较适合网页快速保存，这些链接通常我们希望以后使用，但是如果丢掉也没有什么可惜的。而evernote来说的话，
保存的网页内容通常是知识性的，丢掉还是比较可惜的。差别就在这个地方。我打算按照这个方法试行一段时间，如果还有什么问题记录下来。

NOTE（dirlt）：这里界限还不是很明确。其实还是看个人爱好吧，如果确实想收藏以后作为知识管理的话，那么就clip下来，
否则就作为收藏添加即可。

对于一些不同地方需要交换的信息，这些都是temp的东西，可以通过gist/gmail/evernote来交换，这些都没有什么问题。

** 2012-8-3
*** compaq直接掉电
这台compaq笔记本是在研究生二年级时候买的。当时暑假实习赚了一些钱所以寻思着自己购买一个笔记本，具体经历可以看[[file:purchase-compaq-notebook.org][这里]] 。

昨天晚上重新看赛德克巴莱的时候，可能是因为mkv格式高清所以解码占了非常多的CPU过热，所以直接掉电了。这种事情以前看到同学遇到过，
但是自己没有碰到。电脑下面还有iDock这样的支架散热，看来compqa散热着实是一个问题。

这几天寻思自己重新购买一个笔记本，在thinkpad和mba之间选择。thinkpad在百度工作的时候用过x201i型号，感觉非常轻便并且性能也很好。
而且自己可以升级内存以及硬盘获得更好配置。而air的话其实性价比也是非常高的，并且相对thinkpad来说真心不贵，只不过最近我开始习惯使用
ubuntu，如果购买air的话那么又要使用osx（其实切换代价还好吧，多接触这些优秀系统似乎也不是坏事）。

** 2012-8-7
*** 搜索其他时区时间
直接在google.com里面搜索即可，比如想知道加州时间的话搜索“CA time”即可.wonderful:)

*** 关于关税问题
这几天想入手一个macbook air，看好了配置是
   - http://store.apple.com/us/configure/MD224LL/A
   - 升级到i7处理器，4G内存，128G ssd.
    - 价格在1249$，RMB 7950.
正好CTO在USA CA，所以希望他可以在那边帮我购买一个，但是关税确实是一个问题。

现在入境中国的话，对于笔记本这类商品来说有200的关税。但是因为这个抽查的，并且如果拆掉包装的话（相当于自己随身携带的），那么就不需要缴纳任何关税。
但是问题是，在USA的话还有购物税，而且在CA（高达8.25%，USA其他州的税是不同的。不知道香港有没有？）。并且对于商品来说，标价都是税前的。
在USA购物的话，还分网购和实体店购。如果是网购的话可能不需要上税，但是CTO说似乎现在amazon也需要上税了，而对于实体店来说肯定是需要上税。

*** 购买macbook air
终于决定从HK买air了，多亏了tp同学帮忙。i7处理器，8G内存，128Gssd，折合人民币大概在8600.（看了一下在mainland买同样配置在9800左右，囧）
因为更换了配置，所以大概需要等个1-2周才能够送到他住的地方（应该是我的生日8.15他才能收到），然后他坐车到深圳在那边用顺丰给我快递过来。辛苦了。

给他的香港账户汇款是个问题，他的账户是恒生银行的，不知道招行或者是交行都啥办法汇款？如果没有的话有什么比较方便的途经可以汇款吗？

** 2012-8-13
*** DNS轮询
除了LVS，nginx之外，DNS也可以做轮询。之需要每次请求DNS返回不同的nginx实例即可。
