* diary
** 2012-7-26
*** 组织邮件和列表
今天思考了一下应该如何组织邮件和阅读列表。虽然身边的人都习惯使用gmail web以及google reader方式来处理邮件和阅读rss，
但是我不是非常习惯这种操作方式，还是更加prefer本地操作。但是这样会带来一个问题就是，如果你配备了一台新的电脑的话，那么你需要
花非常多的时间进行配置。好比如果原来在你的电脑上面设置了过滤器或者是标签的话，重新设置还是会比较麻烦的。另外就是过滤器以及标签
这件事情本来就非常耗时间。做过滤器以及标签的方式无非就是希望以后可以很方便地进行搜索并且安排todo事项。

我决定最后的做法还是这样的：
   - 首先还是使用客户端thunderbird来进行邮件处理和RSS阅读。
   - 客户端还是使用pop3方式来接受和处理邮件。
   - 我们不对客户端做过多的设置。不设置任何过滤器以及标签。
     - 如果一封邮件需要稍后处理的话，那么添加到自己的todolist里面去。
     - 如果一封邮件里面包含比较有价值的信息的话，通常可以将其加入到自己的todolist里面去并且附上有价值的信息。
这样一来所有的工作都依赖于todolist。开始可以使用简单的方式来维护todolist,之后的话可以考虑好好学习org-mode。

对于rss来说可能还需要考虑在线阅读方式，因为老婆在天津周末都过去，但是不一定带上笔记本。在她的电脑上面通常不需要
编辑过多的内容，大部分还是浏览内容然后可以通过写邮件的方式将阅读的内容整理起来邮件发送给自己。所以最好可以有一个在线阅读rss方式。
现在看来网易云阅读似乎是一个不错的选择，有客户端可以在ipad上面阅读内容。

*** firefox收藏栏
firefox的收藏栏相对于chrome确实好用：
   - 对于刚看到的一篇文章可能不希望直接打上tag，可以通过托拽的方式拖到bookmark toolbar上面。
   - 之后如果决定需要收藏的话，那么可以直接Ctrl+D进行收藏，默认是收藏到bookmark menus里面去，并且焦点在tags上面，输入回车即可。

** 2012-7-27
*** 书签整理
关于书签这个tag来说，其实大部分不用打，因为标题信息已经十分丰富可以很容易地找到，同时firefox也会从链接中提取一些description来方便检索。
所以打tag大部分是因为，如果以后想检索到这个书签的话我们可能希望使用什么关键字来进行检索，这个关键字是否出现在标题内部。如果没有出现在标题
内部的话，那么打上这个tag还是十分有必要的。当然如果不怕麻烦的话，也可以在tag里面做一些冗余信息。

** 2012-7-30
*** 参观天津机房
今天和同事去看了一下天津华苑的机房，在梓苑路上面。通常机房是有一些通信运营商来建立数据中心的，比如联通移动电信这些公司，当然也不排除一些
很大的互联网公司比如facebook以及google等，自己建立数据中心。建立数据中心大致需要：
   - 地皮
   - 传输设施
   - 电源供应
   - 空调设施
   - 机柜
等。今天看的是联通建设的数据中心。但是这样的数据中心通常只是考虑单个地域的数据中心建设，为了更好的提供服务，所以需要有单独的IDC管理团队。
IDC（internet data center）管理团队做的事情大致包括下面这些事情：
   - 从各个数据中心购买机柜
   - 提供一些额外的跨地域服务
   - 可以让团队帮忙去管理机器比如重启机器等
说白了IDC管理团队就是中介，但是这个中介做了一些资源搭配以及方案设计，方便客户更好地使用，我们通常是从IDC管理团队购买服务。对于那些巨头公司来说的话，通常也有自己的IDC管理团队。
百度在中国没有权力自己建立数据中心，但是他们也有自己的IDC管理团队，他们绕过其他IDC管理团队直接从数据中心购买资源。从而对于我们普通客户来说，要做的事情大致就是：
   - 选择IDC管理团队比如世纪互联
   - 自己购买机器以及交换机等设备
   - 和IDC管理团队定价
今天看到的一个机柜有42U，所谓xU就是说一个服务器占用的厚度（通常长度和宽度都是相同的）。如果一个服务器占用4U的话，那么意味着一个机柜最多也就
占用10台服务器。另外限制机柜hold服务器数目因素就是电流大小，9A/12A这样。就我这次观察看到的情况来说，一个机柜里面大约放置了7-10台服务器（每个大约占据2U），
所以猜想限制这些服务器因素应该是电流大小，这大概也是做低功耗的意义吧。每个服务器层面都有两个插座（主备），接到一楼的电源。空调是从下向上吹冷气的，
大约需要维持在20-25度左右，空气湿度在50-60%左右。每个小机房大约有20个机柜吧，最后通过一个交换机链接起来。对于现在普通的交换机来说，带宽也就是在1Gbps上，
和服务器的网卡带宽相似。如果服务器需要提供内网和外网地址的话，需要提供两块网卡绑定IP。

*** firemacs配置
原来firemacs的配置放在了pref.js里面（可以通过about:config察看到），所以应该是可以进行同步的。
但是有个问题就是，这个配置必须等待firefox正常关闭之后才会生效，否则只是存在于Cache里面，这点非常重要。
所以如果修改了firemacs配置的话，尽可能重启一次确保修改写入了配置。

NOTE（dirlt）：似乎配置文件并没有进行同步。看来还必须自己同步pref.js这个文件了？OMG。不过现在看起来
自己机器数量还非常少，在各个地方稍微简单配置一下即可，没有必要始终同步。

*** wget断点续传
使用wget -c就可以使用断点续传功能，但是这个似乎需要服务器端的支持。服务器需要支持从某一个offset读取文件。

** 2012-7-31
*** 一种阅读方式
今天突然发现了一种很好的阅读方式
   - 首先下载ff的clearly插件。这个插件可以很做一些排版工作去除掉网站中一些无意义的内容比如广告等。
   - 然后使用Ctrl+P将其打印成为pdf格式保存下来阅读（或者是将其clip to evenote上阅读）

