* diary
** 2012-7-26
今天思考了一下应该如何组织邮件和阅读列表。虽然身边的人都习惯使用gmail web以及google reader方式来处理邮件和阅读rss，
但是我不是非常习惯这种操作方式，还是更加prefer本地操作。但是这样会带来一个问题就是，如果你配备了一台新的电脑的话，那么你需要
花非常多的时间进行配置。好比如果原来在你的电脑上面设置了过滤器或者是标签的话，重新设置还是会比较麻烦的。另外就是过滤器以及标签
这件事情本来就非常耗时间。做过滤器以及标签的方式无非就是希望以后可以很方便地进行搜索并且安排todo事项。

我决定最后的做法还是这样的：
   - 首先还是使用客户端thunderbird来进行邮件处理和RSS阅读。
   - 客户端还是使用pop3方式来接受和处理邮件。
   - 我们不对客户端做过多的设置。不设置任何过滤器以及标签。
     - 如果一封邮件需要稍后处理的话，那么添加到自己的todolist里面去。
     - 如果一封邮件里面包含比较有价值的信息的话，通常可以将其加入到自己的todolist里面去并且附上有价值的信息。
这样一来所有的工作都依赖于todolist。开始可以使用简单的方式来维护todolist,之后的话可以考虑好好学习org-mode。

对于rss来说可能还需要考虑在线阅读方式，因为老婆在天津周末都过去，但是不一定带上笔记本。在她的电脑上面通常不需要
编辑过多的内容，大部分还是浏览内容然后可以通过写邮件的方式将阅读的内容整理起来邮件发送给自己。所以最好可以有一个在线阅读rss方式。
现在看来网易云阅读似乎是一个不错的选择，有客户端可以在ipad上面阅读内容。

firefox的收藏栏相对于chrome确实好用：
   - 对于刚看到的一篇文章可能不希望直接打上tag，可以通过托拽的方式拖到bookmark toolbar上面。
   - 之后如果决定需要收藏的话，那么可以直接Ctrl+D进行收藏，默认是收藏到bookmark menus里面去，并且焦点在tags上面，输入回车即可。
NOTE(dirlt):似乎Ctrl+D之后还需要使用Tab移动到tags这个栏上面。

** 2012-7-27
将原来思考过的”编程语言要素整理“整理过来。

-----
大家好，一直想整理一下编程语言要素。所谓编程语言要素就是说，一旦我们对于这些编程语言的要素掌握之后，我们就可以用这个语言做一些事情了。
编程语言要素必须是基本的(atomic)，然后我们在学习语言的时候，首先学习这些基本的内容之后，就可以开动了。不要使用形式的东西来概括，
必须是一些可以put into practice的东西

   - 基本类型 // 比如字符串如何表示等
   - 复合结构 // 如何将基本类型复合出来
   - 内存管理 // 如何进行内存分配释放
   - 程序结构 // 变量作用域，变量声明，类的访问权限，程序结构
   - 语言特有特性 // 反射，动态代码生成，continuation
   - 工程组织性 // 如何组织一个大的项目，如何服用代码比如库
   - 文件系统 // 如何操作文件，读取特定字节等
   - 并发控制 // 比如进程，线程，锁
   - 网络通信 // 通讯设施
   - C/C++扩展 // 如何使用C/C++来编写扩展提高效率

