* drive-learning
#+TITLE: 学车经历

--------------------

今天（2011.12.17）终于过了科目三，可以坐等驾照了（还要等差不多2-3天吧）。我是在北方驾校学的C2皮卡，发票上面开出的日期是5月17日，安全法规课本上记录科目一考试时间是6月23日上午9点，计时手册模拟训练完成日期是7月10日，其他时间里程碑就不可考了，这就意味着从报名到真正拿到驾照大概有7个月。7个月啊，从短袖偏偏的少年，到包裹羽绒的少年，浪费了不少青春啊：（

发票上面显示我们是首先交了160元的考试费和工本费（科目一），然后交了200元的法培费，以及3740的皮卡双休64学时培训费（科目二时间）。总共加起来有160+200+3740=4100，也算是相当贵了的。此外我在科目二的时候做了2次模拟训练（一次50元），并且在科目三挂了一次补考（25元），全部花在驾校学车上的钱是4225。

当时是北方驾校来我们单位方便我们集体报名，差不多有100多人报了吧，没有进行体检就直接填写报名单了。当时给我们公司的优惠是提供了双休学车的计划，每周六日晚上5:00-9:00，也不用自己约车教练保证一定能够约上车，但是必须每周六日晚上都去。如果按照这样的计划学习的话，2个月就可以学完科目二，还是比较快的。另外还提供了一种优惠就是双休日只是确保一定可以约到车，这样一来时间可能会拖得比较长。但是最终没有选择计划一是因为女朋友在天津，如果按照计划一学习的话意味着两个月可能见不了面（虽然是下午5:00学车，但是因为北方驾校是在昌平一带，所以从我住的立水桥到那里基本也需要花去2个小时），所以还是选择了计划二，但是结果是并没有他们宣传得那么得到位可以确保每周都约上，这个后面再说。后来我也发现计划一也是打了折扣的，因为教练一般都住在比较远的地方，从北方驾校进城的昌68最后一趟是7:30，所以大部分学到7:30之后教练就回去了，我们在读卡站等到8:45刷卡。

说到刷卡，应该现在大部分驾校都用刷卡的方式签到了吧。科目一完成之后我就会被给到一张卡片，我们把自己的卡片放在教练手上，然后教练如果可以帮助我们约到车之后，就给我们打电话约时间，如果都OK的话那么教练就帮我们约车。练车当天我们到停车场从教练手里拿到卡，学车之前刷一次，学车之后刷一次，证明这段时间确实学车了。学车时间有3个段，8:00-12:00,1:00-5:00,5:00-9:00，发现了吗？下午和晚上是有时间冲突的，除非教练不吃饭。学车刷卡必须在前后15分钟内，完毕刷卡可以提前15分钟。刷卡需要附上你的指纹，这样就不会被冒充了，指纹采集是在学习科目一之前完成了的。

未完待续…

--------------------

科目一就是法律知识培训，教材是《道路交通安全法规与相关知识必读》，反正就是上两天的课，从早上9点左右到下午4点左右，挺累的。其实老师也没有讲什么内容，课堂上大部分人都在睡觉。但是老师时不时会叫我们仔细看一段内容或者是记录一些东西，比如当时知道了驻车制动（手刹）和行车制动（脚刹）以及发动机制动（档位），还有就是为了防抱死使用点刹（后来科目二知道点刹只是气刹时候用的，现在大部分汽车都是油刹而且都有ABS，所以要刹车直接踩下去就好了）。老师讲了这么多内容，我觉得最关键的点就是一定要慢点开车（但是后来在科目三因为转弯的时候过慢，教练觉得不爽直接让我挂了。后来同学和我说，安全是一方面的考虑，保持交通通畅也是需要考虑的）。教材的后面有试题库，我们考试的内容都是从试题库里面抽取的，好像是60道判断题40道选择题。第二天的时候在剩下的3个小时吧，老师会集中帮我们过一遍后面的试题库并且勾出重点出来。其实大部分题目呢，怎么说都是符合我们常识的，一眼就可以知道哪个是正确的哪个是错误的，所以同学们只需要关注那些不符合我们常识（就是按照我们自己的推理）的题目，另外一些题目可能就需要记住了，比如每个交通手势是什么意思，不过幸运的是这类题目不多。值得一提的是，教我们的老师相当的有文采，在课程结束之后让我们写下了几句我们自己都觉得吐血的话： *NOTE（dirlt）：你说是不是很扯淡，我操！*
   1. 我听的不是课，是方向
   2. 发光体，爱生活
   3. 我一定会尊严地生活着
   4. 心存一份美好情感，做一个好人
   5. 一个好人就是在明白了生活的真相之后，依然热爱生活
   6. 时刻提醒振作起来
   7. 学会劳动，学会生存，学会等待成功。让每一个明天都比今天奔向更远的地方。
   8. 时势造就人，梦想让人变得特别
   9. 我不同意你，但是我支持你，这是一种科学精神。
   10. 从此生活完全可以更美好，我会常常想起这些话。 
科目一考试是完全的电脑进行的，因为只有选择题和判断题目，只需要键盘上面的小键盘就可以进行输入了。一定要非常注意使用这些按键，一不小心按成了交卷就悲剧了。科目一考试90分是合格，否则就需要当场补考。科目一考试之前都会要求同学输入自己的指纹，这样在科目二学习时候刷卡需要配上指纹，以免顶替来学习。我记得自己的科目一成绩是95分，很一般。

未完待续…

--------------------


