* excerpt
#+TITLE: 网络摘抄
--------------------

IBM某大型主机的最高温度大概是85度，超过这个温度会自动关机，以保住数据，HP对应的型号最高温度是84度，差了一度。这在正常的采购中，是完全忽略不计的一个参数。真实案例，某天某省移动机房停电，UPS先停了空调，机房温度开始上升，大家知道IBM和HP的结局么？

HP的主机首先到达温度的临界值，自动关机，耗电量下降，UPS开始给空调最小能量供电，因为只剩下了IBM的主机，发热量降低，机房温度逐步下降。结局，用户跑在IBM主机上的结算业务没有停，跑在HP主机上的业务停止运行超过24小时。这是我亲身经历的一个案例

--------------------
火车上教授与农夫相对而坐。教授说：我出一道题你若不知，给我五元；你出一题，我若不知，给你五百元，如何？农夫同意。教授：月亮距地球多远？农夫摇头递给教授五元钱。农夫问：上山三条腿下山四条腿，什么动物？教授苦思无解给五百元。农夫收钱欲睡觉。教授追问：啥动物？农夫递给教授五块遂去睡觉。

--------------------
 【犹太人营销高招十二式】：1.为女性服务；2.为钱走四方；3.78：22法则；4.为嘴巴服务；5.用脑去赚钱；6.节流更需开源；7.惜时如金；8.靠信息抢占先机；9.诚信是根本；10.善于整合资源；11.站得高看得远；12.谈判创造价值。

--------------------
 【情人节这天】艾瑞一早就在忙活，他在明信片上涂涂画画， 巴比问：您在干什么? 艾瑞说：今天要寄1000封‘猜猜我是谁’的卡片。 巴比不解地问：为什么？艾瑞回答：我是专管离婚案件的律师。旁白：在犹太商界，经商是只受法律限制而不受道德约束的，不违法乱纪，可采用一切别出心裁的手法获取财富。 

--------------------
*关于狮子管理狼群的方法*

狮子管理狼群，这是一则笑话，一则寓言，但也是一则经典的团队管理案例。这个故事虽然很简短，但可以从中汲取很多价值的管理方法论，比如绩效工资、末位淘汰法、竞争上岗等，不愧是经营管理中的经典案例。

狮子让一只豹子管理10只狼，并给他们分发食物。豹子领到肉之后，把肉平均分成了11份，自己要了一份，其他给了10只狼。10只狼都感觉自己分的少，这合起伙来跟豹子唱对台戏。虽然一只狼打不过豹子，但10 只狼，豹子却没法应付了。豹子灰溜溜的找狮子辞职。狮子说，看我的。

【第一天 绩效工资】 狮子把肉分成了11份，大小不一，自己先挑了最大的一份，然后傲然对其他狼说：你们自己讨论这些肉怎么分。为了争夺到大点的肉，狼群沸腾了，恶狠狠的 互相攻击，全然不顾自己连平均的那点肉都没拿到。豹子钦佩的问狮子，这是什么办法?狮子微微一笑，听说过人类的绩效工资吗?……

【第二天 末位淘汰】 第二天狮子依然把肉分成11块，自己却挑走了2 块，然后傲然对其他狼说：你们自己讨论这些肉怎么分。10只狼看了看9 块肉，飞快的抢夺起来，一口肉，一口曾经的同伴，直到最后留下一只弱小的狼倒在地上奄奄一息。豹子钦佩的问 狮子，这是什么办法?狮子微微一笑，听说过末位淘汰法吗?……

【第三天 竞争上岗】 第三天狮子把肉分成2块，自己却挑走了1 块，然后傲然对其他狼说：你们自己讨论这些肉怎么分。群狼争夺起来，最后一只最强壮的狼打败所有狼，大摇大摆的开始享用它的战利品。狼吃饱以后才允许其它狼再来吃，这些狼都成了它的小弟，恭敬的服从它的管理，按照顺序来享用它的残羹。从此狮子只需管理一只狼，只需分配给它食物，其它的再不操心豹子钦佩的问狮子，这是什么办法? 狮子微微一笑，听说过竞争上岗吗?……

【最后一天 和谐社会】 最后一天狮子把肉全占了，然后让狼去吃草。因为之前的竞争，狼群已经无力再战了。最后豹子钦佩的问狮子，这是什么办法? 狮子微微一笑，听说过和谐社会吗?

--------------------
*如何让孩子学会接受批评*

和许多成年人一样，孩子们往往也喜欢听表扬而反感批评。法国心理学家高顿教授通过一项专题研究证实，那些难以接受批评的孩子长大后，也大多会对批评持“避而远之”或干脆“拒之门外”的态度。由此看来，让孩子在幼儿时代就学会接受批评无论对一个人完整人格的塑造，还是对促成其事业的成功，都具有相当积极的意义。那么，年轻的爸爸妈妈们该如何让孩子学会接受批评呢？法国的一些儿童教育专家为此提出以下建议：
   - 教育孩子不必对他人的批评大惊小怪。教育孩子，当然应该坚持表扬为主，但不妨在孩子呀呀学语或学步时，就有意识地让孩子既听到正面的肯定，也听到反面的批评。此时，须注意对幼儿的批评一定要语气温和，分析中肯，且以更多的表扬为前提，如：宝宝学说“喝水”很清楚，但学说“吃饭”还不清楚时，妈妈可以说：“你说的话不够清楚，再说一遍，好吗？”或“宝宝昨天学走路一点不怕累，怎么今天就怕累了？”有意识地早早“引进”批评可以帮他下意识体会到：批评和表扬同样常见！事实上，在幼儿时期就能适应批评的孩子，长大后往往也较能适应社会，其中也包括拥有正确对待来自他人的批评乃至非议的平和心态，以及较强的承受挫折能力。
   - 让孩子学会认真倾听。不论批评有多尖锐、多不中听，你都应该要求孩子认真倾听。因为只有认真倾听，才会发现其中也许确实有几分道理，最后才能虚心予以接受。从而让孩子渐渐明白：对他人的批评认真倾听，不仅是一种文明的表现，而且也是完善自我的必要方法。
   - 冷处理但不要默不作声。冷静处理并不意味着对批评默默无语。父母应教育孩子对批评的合理成分虚心接受，甚至列出改进的办法或措施。当然，对批评者的感谢更能体现出接受批评的诚意。要求孩子掌握的“冷处理”技巧包括：不要对批评者反唇相讥，不要“自卫还击”，不要夸张等等，相反，应在认真倾听的基础上冷静地分析出尽可能多的合理成分。
   - 允许作出解释。当批评不符合事实，也应允许孩子作出解释，因为让孩子虚假地表示接受批评，但心里大感委屈实际上不仅于事无补，还可能引发种种弊端。与此同时也要让孩子明白：解释的目的并不是推卸本来应负的责任，还应要求孩子保持解释时心平气和、实事求是的态度。
   - 对批评者一视同仁。不少孩子可以做到认真倾听并虚心接受来自老师或父母的批评，但对来自同龄人的批评却拒之门外。这时应教育孩子：只要批评有道理，即便这批评来自小伙伴，也应虚心接受。
实际上，只要孩子学会了“善待”批评，那么批评完全可以如同表扬一样，成为鼓励孩子前进的春风，而且还起着表扬难以起到的警示作用。

--------------------

白岩松语录：1、人的一生只有5%是精彩的，只有5%是痛苦的，另外的90%是平淡的；人们往往被5%的精彩诱惑着，忍受着5%的痛，在90的平淡中度过。2、生命原本脆弱，我们只能坚强地活着。3、年轻的最大魅力就是不断犯错误，而有时间去改正。乐观面对困难，好好培养一下自己的心理素质。

--------------------

 【大商之道：欲成大器者八律】1、觉人之诈，不愤于言； 2、受人之侮，不动于色； 3、察人之过，不扬于他； 4、施人之惠，不记于心； 5、受人之恩，铭记于心； 6、受人之鱼，而学之渔； 7、识人之才，授之于权； 8、善于谋人，有容乃大 。


--------------------

 【统计局不敢发布的数据】下图是重庆大学法学院院长陈忠林教授的研究结果。

file:../images/secret-data-about-china.jpg

--------------------

 【全年旅行最佳去处】一月：雪国哈尔滨；二月：南国初春海南；三月：江南；四月：山水浪漫桂林、黄山、庐山；五月：迷情云南；六月：奇山张家界；七月：海边青岛、大连；八月：梦想西藏；九月：神秘新疆；十月：童话九寨沟；十一月：美丽贵州；十二月：时尚香港。

--------------------
 【到底谁成就了谁】克林顿和希拉里去加油站，一小工是希的初恋。克林顿跟老婆吹嘘说：你要不嫁给我，你老公可能还是一小工。希看了眼初恋，对克林顿说：我要嫁给他，当总统的可能是他，哪会轮到你——启示：创业者时刻要牢记，是你的追随者成就了自己,而不是自己是救世主成就了大家。

--------------------
《犹太人为什么优秀》：犹太人孩子的教育是从三岁开始的。父母们可以为孩子选择交费的私塾，也可以选择免费的公立学校。在这里，犹太人的目的不是让孩子们理解文章的意思，而是让他们背诵。犹太人认为，如果不能培养出一个好的记忆力，今后就没有办法学习其它事物。

--------------------

许单单-互联网分析师 推荐图书清单

file:../images/xudandan-booklist.jpg

--------------------

提升自我幸福感的五种做法：1、经常联系周围的人。你的家庭、朋友、同事还有邻居。2、让身体动起来去散散步或者跑一圈。3、留心周围，留心那些不经意的美丽。4、学无止境，尝试一些新鲜的东西或找回你过往的某一种兴趣爱好。5、与人为善，尽量多给朋友甚至陌生人提供帮助。

--------------------

「价格大战」：话说重庆二个火锅店进行了价格大战。甲说：三十元一位仼吃。乙接：二十元一位仼吃；甲再战：15元一位仼吃，相当于每位补贴五元。乙说：10元一位不限时。甲立马招来100位棒棒，每人发10元，让他们从早吃到晚！乙瘫,甲恢复50元。

财经频道关于家电价格战的调调真外行：过去很多人说富士彩卷在国内倾销，即低于成本价销售，先打垮对手如乐凯；然后再提高价格，赚大钱。这是个无聊的笑话。如果我是乐凯，那我就干一件事，买富士。富士卖的越多，赔钱越多，乐凯能把富士逐出中国。别提京东发愁！恶性竞争，排挤竞争对手的说法是傻话。

--------------------
爱的最高境界是什么？不是什么你死我活。是习惯，一个女人习惯了一个男人的鼾声，从不适应到习惯再到没有他的鼾声就睡不着觉，这就是爱；一个男人习惯了一个女人的任性、撒娇，甚至无理取闹，这就是爱；一个人会为了另一个人去改变、去迁就，这就是爱。对爱人，迁就多少，就爱了多少

--------------------
识人的几个角度：1、看他的价值观和思维方式。2、看他的面相。3、看他从事的职位。4、看他的衣着和喜好。5、看他的家庭。6、看他的配偶。7、看他的办公室和家庭陈设。8、看他的朋友圈子。9、看他在激怒的情况下如何反映。10、看他接受信息的来源。识人难，但识人是成事的关键。

--------------------
*执行力差的五大原因*

1、员工不知道干什么。2、不知道怎么干。3、干起来不顺畅。4、不知道干好了有什么好处。5、知道干不好没什么坏处。

*解决执行差难题的五大方法*

1、目标明确。2、方法可行。3、流程合理。4、激励到位。5、考核有效。

--------------------
*股神是怎样练成的*

巴菲特说，他7岁对股票感兴趣，8岁阅读父亲股票的藏书，10岁时当地图书馆有关股票的书已读完，11岁买第一只股票，19岁找到正确投资方向，20岁拜格雷厄姆为师。25岁创立合伙企业时，已研究18年，实际投资经验15年，远超过1万小时。

--------------------

学会欣赏别人：1、不能欣赏别人时，等于创造了一个不与别人合作的理由。2、学会欣赏别人是一眼就能发现别人的优点，而不是穿透般的看到别人的不足。3、当我们会“与别人的优点合作，与别人的缺点保持距离”时，我们就成了资源高手。4、一个人最喜欢把自己的价值，赠送给懂得欣赏的人。

--------------------

认识自己的11个问题：1.我喜爱做什么？2.我擅长做什么？3.我本性是什么？4.什么对我最重要？5.我为何而生？6.我独特的才能天赋是什么？7.若不为金钱而生我会做什么？8.我生命的特殊目的是什么？9.什么是只能由我来完成的事？10.什么是我终生要去完成的？11.我希望自己的人生最终被怎样概括？

--------------------

其实文凭不过是一张火车票，清华的软卧，本科的硬卧，专科的硬座，民办的站票，成教的在厕所挤着。火车到站，都下车找工作，才发现老板并不太关心你是怎么来的，只关心你会干什么。

--------------------
*现代人必须具备的十种素质*
   - 储蓄友谊
   - 学会放手
   - 播种善良
   - 懂得音乐
   - 避开得不到之苦和钟情之苦
   - 学会承受
   - 常怀感恩的心
   - 热爱工作
   - 勤于学习
   - 热爱运动

--------------------
*我想成为坐在路边鼓掌的人*

我那上国中的女儿，她同学都管叫她23号。她的班上总共有50个人，而每次考试，女儿都排名23。久而久之，便有了这个雅号，她也就成了名副其实的中等生。我们觉得这外号刺耳，女儿却欣然接受。老公发愁地说，一碰到公司活动，或者老同学聚会，别人都对自家的’小超人’赞不绝口，他却只能扮深沉。人家的孩子，不仅成绩出类拔萃，而且特长多多。唯有我们家的23号女生，没有一样值得炫耀的地方。因此，他一看到娱乐节目那些才艺非凡的孩子，就羡慕得两眼放光。

后来，看到一则九岁孩子上大学的报导，他很受伤地问女儿：『孩子，妳怎么就不是个神童呢？』女儿说：『因为我爸爸不是神父啊!』老公无言以对，我不禁笑出声来。中秋节，亲友相聚，坐满了一个宽大的包厢。众人的话题，也渐渐转向各家的小儿女。趁着酒兴，要孩子们说说将来要做什么？钢琴家，明星，政界要人，孩子们毫不怯场，连那个四岁半的女孩，也会说将来要做电视的主持人，赢得一阵赞叹!15岁的女儿，正为身边的小弟弟小妹妹剔蟹剥虾，盛汤揩嘴，忙得不亦乐乎。大家忽然想起，只剩她没说了。在众人的催促下，她认真地回答： 『长大了，我的第一志愿是，当幼儿园老师，领着孩子们唱歌跳舞，做游戏。』众人礼貌地表示赞许，紧接着追问她的第二志愿。她大大方方地说：『我想做妈妈，穿着印叮当猫的围裙，在厨房做晚餐，然后给我的孩子讲故事，领着他在阳台上看星星。』亲友愕然，面面相觑，不知道该说些什么。老公的神情，极为尴尬。回家后，他叹着气说：『你还真打算让女儿将来当个幼儿园老师？我们难道真的眼睁睁地看着她当中等生？』

其实，我们也动过很多脑筋。为提高她的学习成绩，请家教，报辅导班，买各种各样的资料。孩子也蛮懂事，漫画书不看了，剪纸班退出了，周末的懒觉放弃了。像一只疲惫的小鸟，她从一个班赶到另一个班，卷子，练习册，一沓沓地做。但到底是个孩子，身体先扛不住了，得了重感冒。吊着点滴，在病床上，她还坚持写作业，最后引发了肺炎。病好后，孩子的脸小了一圈。可期末考试的成绩，仍然是让我们哭笑不得的23名。

后来，我们也曾试过增加营养、物质激励等等，几次三番地折腾下来，女儿的小脸越来越苍白。而且，一说要考试，她就开始厌食，失眠，冒虚汗，再接着，考出了令我们瞠目结舌的33名。我和老公，悄无声息地放弃了轰轰烈烈的揠苗助长活动。恢复了她正常的作息时间，还给她画漫画的权利，允许她继续订《儿童幽默》之类的书报，家中安稳了很久。我们对女儿，是心疼的，可面对她的成绩，又有说不出的困惑。

周末，一群同事结伴郊游。大家各自做了最拿手的菜，带着老公和孩子去野餐。一路上笑语盈盈，这家孩子唱歌，那家孩子表演小品。女儿没什么看家本领，只是开心地不停鼓掌。她不时跑到后面，照看着那些食物。把倾斜的饭盒摆好，松了的瓶盖拧紧，流出的菜汁擦净。忙忙碌碌，像个细心的小管家。野餐的时候，发生了一件意外的事。两个小男孩，一个数理天才，一个英语高手，两人同时夹住盘子上的一块糯米饼，谁也不肯放手，更不愿平分。丰盛的美食，源源不断地摆上来，他们看都不看。大人们又笑又叹，连劝带哄，可怎么都不管用。最后，还是女儿，用掷硬币的方法，轻松地打破了这个僵局。回来的路上，堵车，一些孩子焦躁起来。女儿的笑话一个接一个，全车人都被逗乐了。她手底下也没闲着，用装食品的彩色纸盒，剪出许多小动物，引得这群孩子赞叹不已。直到下车，每个人都拿到了自己的生肖剪纸。听到孩子们连连道谢，老公禁不住露出了自豪的微笑。

期中考试后，我接到了女儿班主任的电话。首先得知，女儿的成绩，仍是中等。不过，他说：『有一件奇怪的事想告诉我，他从教三十年了，第一次遇见这种事。语文试卷上有一道附加题：你最欣赏班上的哪位同学，请说出理由。除女儿之外，全班同学，竟然都写上了女儿的名字。理由很多：热心助人，守信用，不爱生气，好相处等等，写得最多的是，乐观幽默。』班主任还说：『很多同学建议，由她来担任班长。』他感叹道：『你这个女儿，虽说成绩普通，可是做人，实在很优秀!』我开玩笑地对女儿说：『妳快要成为英雄了。』正在织围巾的女儿，歪着头想了想，认真地告诉我说：『老师曾讲过一句格言：当英雄路过的时候，总要有人坐在路边鼓掌….。』她轻轻地说：『妈妈，我不想成为英雄，我想成为坐在路边鼓掌的人。』我猛地一震，默默地打量着她。她安静地织着绒线，淡粉的线，在竹针上缠缠绕绕，仿佛一寸一寸的光阴，在她手上，吐出星星点点的花蕾。

我心上，竟是蓦地一暖。那一刻，我忽然被这个不想成为英雄的女孩打动了。这世间，有多少人，年少时渴望成为英雄，最终却成了烟火红尘中的平凡人。如果健康，如果快乐，如果，没有违背自己的心意，我们的孩子，又何妨做一个善良的普通人。长大成人后，她一定会成为：贤淑的妻子，温柔的母亲，甚至，热心的同事，和善的邻居何况她是班上50名之中的23名，我们还不庆幸，还不满足?还想要更高人一等，更出人头地!那后面还有27名半数以上的孩子呢﹖如果我是她们的父母，我要如何自处呢﹖在那些漫长的岁月，她都能安然地过着自己想要的生活；她又没学坏，我作为身教言教的父母，能教养孩子长大成人，并成为社会上有用的人，就可告慰先祖，还想为孩子祈求怎样更美好的未来？就算她将来能当上司法官，能考上建筑师，若她心术不正，口是心非，那又有何用？

另：想起爸爸对我说过的话。“我不希望你成才，我只希望你能够成人。”我一直记在心里。

--------------------

【一个结婚10年的男人总结的】1.在心爱的女人面前,越贱越快乐2.两人吵架后,互换角色再重复一遍刚才吵架的内容;3.在她洗澡的时候悄悄帮她把拖鞋换个方向,要刷牙的时候帮她把牙膏挤好漱口水倒好;4.副驾驶的位子是老婆的专座;5.不要以为沉默很酷,两个人在一起还是要多沟通比较好

--------------------

皮格马利翁效应：希腊神话中国王皮格马利翁是一名雕塑家。他用象牙雕塑了一位美丽的美女。他深深爱上了这个美女，他祈求女神让雕象活过来。他的真诚感动了女神，女神决定帮他。不久，雕象活过来了，并成为了皮格马利翁的妻子。后被教育心理学引用，意思是如果你相信他行，他就会真的行。

--------------------

市场不好，现在质量好点的创业项目或创业者比去年少了至少七成，这种状态非常明显也已持续半年。在这种环境下，敢于出来创业的人虽然数量少了很多，但质量会更高，更成熟，想的更清楚也更有胆识。我相信N多年后我们回顾这段时间，会发现那时很多牛逼公司都是在这段时间里创建，突围和壮大的。

非常认同这个说法。vc不仅仅是给你钱，也会帮助你思考，帮助你获得资源，他们慎重一点对创业风险控制有很大的好处。

--------------------

员工的离职原因林林总总，只有两点最真实：1、钱，没给到位；2、心，委屈了。这些归根到底就一条：干得不爽。员工临走还费尽心思找靠谱的理由，就是为给你留面子，不想说穿你的管理有多烂、他对你已失望透顶。仔细想想，真是人性本善。作为管理者，定要乐于反省。

----------

女同志要想成功须付出更多。要想成功：
   - 一是要自信。
   - 二是要融洽上下级关系乐于助人要知道情商占成功的80%。
   - 三是从琐事做起不能浮躁做每件事尽可能尽善尽美。在国家机关学历不重要，只有在提拔时有用。
   - 四是一旦有机会就要有所表现。不能时刻计较得失。做人热情，大度。小事不计较。

-----

如果你在过完枯燥痛苦的一生后郁郁而终。那是因为你一直听妈妈的话，爸爸的话，老师的话，牧师的话，或者电视里那些大家伙们说的话。他们告诉你什么才是对的。我只想说，你这样死去也活该。

-----

猪圈里,公猪总是把最好的给母猪吃.忽然有一天,公猪性情大变,将好吃的抢着吃,只给母猪吃一点点.每晚不睡警惕张望,母猪大为失望,看着自己在消瘦 公猪越来越肥,她恨公猪不爱她了!有一天,公猪被拖到屠宰场,母猪看到张纸条:“以后少吃点.如果爱无法用语言表达,我愿意用生命来证明!”

--------------------

当你决定要创业时，便意味着：1、没有了稳定的收入；2、没有了请假的权利；3、没有了得红包的机会。然而却更意味着：1、收入不再受限制；2、时间运用更有效；3、手心向下不求人，想法若不同，结果便不同；选择不一样，生活才变样。

----------

我一直愚蠢到认为自己能改变世界。想想这个地球上的真牛人是怎么过的。孔子在世也就影响了几十个学生留了几本书，释迦牟尼大抵如此。老子做了隐士，耶稣猛一点，治病除魔显神迹，却被人给钉死了。咱得承认没法改变世界，之前惹是生非都是证明自己有点小聪明小勇气。混口饭吃，睡好觉，读经念佛。够了。

----------

又有一个朋友离婚了。朋友感慨说当下社会的各种组织都极易破碎，婚姻关系、雇佣关系、联盟关系等等。社会上有各种压力，要增长、要还贷、要安全、要攀比.....压力大了关系就破碎组织就变形。还说互联网对此也有贡献。到处都是免费，鼠标一划就到了另一家网站，当然不肯承受压力而是随时准备抬脚走人。

