* fun
--------------------

乘务员：“先生，飞机马上起飞了，请把手机关掉，好吗？” 乘客：“我开的飞行模式” 乘务员：“对不起先生，现在山寨手机也很多，我们很难保证每个手机都是符合标准的！” F舱乘客大怒，“你说啥？你说俺手机山寨的？老子是苹果的！三卡三待呢！不识货别跟老子吵！”

--------------------

【一个结婚10年的男人总结的】1.在心爱的女人面前,越贱越快乐2.两人吵架后,互换角色再重复一遍刚才吵架的内容;3.在她洗澡的时候悄悄帮她把拖鞋换个方向,要刷牙的时候帮她把牙膏挤好漱口水倒好;4.副驾驶的位子是老婆的专座;5.不要以为沉默很酷,两个人在一起还是要多沟通比较好

--------------------

皮格马利翁效应：希腊神话中国王皮格马利翁是一名雕塑家。他用象牙雕塑了一位美丽的美女。他深深爱上了这个美女，他祈求女神让雕象活过来。他的真诚感动了女神，女神决定帮他。不久，雕象活过来了，并成为了皮格马利翁的妻子。后被教育心理学引用，意思是如果你相信他行，他就会真的行。

--------------------

突然听到解说员说“这是一名92年出生的老将。”顿时感觉这个世界太特么凶残了。

--------------------

市场不好，现在质量好点的创业项目或创业者比去年少了至少七成，这种状态非常明显也已持续半年。在这种环境下，敢于出来创业的人虽然数量少了很多，但质量会更高，更成熟，想的更清楚也更有胆识。我相信N多年后我们回顾这段时间，会发现那时很多牛逼公司都是在这段时间里创建，突围和壮大的。

非常认同这个说法。vc不仅仅是给你钱，也会帮助你思考，帮助你获得资源，他们慎重一点对创业风险控制有很大的好处。

--------------------

员工的离职原因林林总总，只有两点最真实：1、钱，没给到位；2、心，委屈了。这些归根到底就一条：干得不爽。员工临走还费尽心思找靠谱的理由，就是为给你留面子，不想说穿你的管理有多烂、他对你已失望透顶。仔细想想，真是人性本善。作为管理者，定要乐于反省。

--------------------

1思想就像内裤，要有，但不能逢人就证明你有。2我可以选择放弃，但绝不放弃选择。3君子报仇，十年不晚。小人报仇，从早到晚。4我们需要马桶精神，按一下，什么都干净了。5人家有背景，而我只有背影。6眉毛上的汗水，眉毛下的泪水，你总得选一样。7财富改变不了个性，却能让人露出本性。

--------------------

王海滨：到北大读书后，雷声整个人的精神气质有了提升，这对于一个剑客非常重要。雷声：其实北大真正的作用是帮我突破了一个技术瓶颈。记者：噢？雷声：以前我一直解决不了出剑时手腕抖动的技术问题，甚至想到了退役，直到有一天我观察到了北大学一食堂打菜师傅是怎么用勺子的....

--------------------

file:../images/company-architecture.jpg

----------

女同志要想成功须付出更多。要想成功：
   - 一是要自信。
   - 二是要融洽上下级关系乐于助人要知道情商占成功的80%。
   - 三是从琐事做起不能浮躁做每件事尽可能尽善尽美。在国家机关学历不重要，只有在提拔时有用。
   - 四是一旦有机会就要有所表现。不能时刻计较得失。做人热情，大度。小事不计较。

-----

如果你在过完枯燥痛苦的一生后郁郁而终。那是因为你一直听妈妈的话，爸爸的话，老师的话，牧师的话，或者电视里那些大家伙们说的话。他们告诉你什么才是对的。我只想说，你这样死去也活该。

-----

和妹子相处，要义就是： 若她涉世未深，就带她看尽人间繁华； 若她心已沧桑，就带她坐旋转木马。和阿哥相处，要义是：若他情窦初开，你就宽衣解带；如他阅人无数，你就灶边炉台。

-----

培训的时候听上级领导说，全国党员有8000多万，而全世界超过8000万人口的国家不过14个。俺就在想，要是让全体党员随便割据个地方，从中国独立出去，组建一个国家，8000万最先进的人都保持同一信仰信念，没有不明真相的群众干扰建设，没有杂音和不良思潮，世界上第一个共产主义国家不就诞生了么

-----

什么是球星效应？ ——齐达内退休了，法国低迷了6年，这就是球星效应 ——普斯卡什退休了，匈牙利低迷了60年，这就是球星效应 ——高俅退休了，中国低迷了1000年，这就是球星效应

-----

自从我国引入劫持人质现场谈判专家制度，劫匪被击毙的几率反而提高。专家们把现场谈判的录音拿来研究，发现总是到这一句时谈判宣告破裂：“你一定要相信党和政府。”

-----

中午吃饭，旁边一桌的大姐结完帐说：＂开张发票，中国人民银行。＂服务员说：＂您写一下。＂大姐答：＂照钱上面写。＂

-----

猪圈里,公猪总是把最好的给母猪吃.忽然有一天,公猪性情大变,将好吃的抢着吃,只给母猪吃一点点.每晚不睡警惕张望,母猪大为失望,看着自己在消瘦 公猪越来越肥,她恨公猪不爱她了!有一天,公猪被拖到屠宰场,母猪看到张纸条:“以后少吃点.如果爱无法用语言表达,我愿意用生命来证明!”

-----

【一个男人的称号】“伟大领袖”、“天赐大将军”、“世界著名的文学家”、“我们星球的卫士”、“所有杰出将军中最杰出的将军”、“众神之神”、“21世纪的北极星”、“一位拥有百科全书一样丰富知识”的“哲学巨人”、“人类最伟大的音乐天才”、“人类智慧的化身”。

file:../images/great-general.jpg

-----

如果你在澳大利亚电子产品Kogan的网站上进行网购的话,使用IE7的用户们可能会惊喜地发现他们需要你多付6.8%钱.收钱理由:我们费了这么大工夫让网站在IE7下看起来和其它浏览器的效果一样,你们理应付给我们辛苦费.PS:建议IE6收更多费用,解放前端码农,不用在去做无用的大量的Css Hack工作.

-----

file:../images/dont-think-yourself-as-an-ugly-person.jpg

--------------------

“麻麻为什么金牌和铜牌待遇差这么多？”“孩子，你知道世界第一高峰么？”“恩，珠穆朗玛峰嘛。”“那世界第三高峰呢？”“干城章嘉峰啊，麻麻我们不要讨论这个问题了，继续讨论金牌和铜牌的事情啊。”“。。。我没什么可说的，让你整天看那些没用的地理书。。”

--------------------

一人到精神病院送东西，刚到医院，车胎爆了。下车修理一不留神，车胎上的四个螺丝滚到下水道里，他在那儿干着急。一个精神病路过看了看：你把剩下3个轮胎，各拔1个螺丝下来，装到备胎上，然后把车慢慢开到市区，找家修车的不就行了。车主问他，你不是精神病么？精神病说——我是有精神病，但不是傻子。

--------------------

 绝妙的真的假新闻：勃列尼涅夫走路快，每每和来访的外国领导人比赛。一次和尼克松举行竞走比赛，结果，勃输了。但《真理报》（这名字！）的报道却是：在昨日美苏举行的一场竞走比赛中，我国领导人勃烈日涅夫同志获得了第二名的好成绩，而美国领导人尼克松获得了倒数第二名。这就是某些国家的文风啊。

--------------------

当你决定要创业时，便意味着：1、没有了稳定的收入；2、没有了请假的权利；3、没有了得红包的机会。然而却更意味着：1、收入不再受限制；2、时间运用更有效；3、手心向下不求人，想法若不同，结果便不同；选择不一样，生活才变样。

----------

我一直愚蠢到认为自己能改变世界。想想这个地球上的真牛人是怎么过的。孔子在世也就影响了几十个学生留了几本书，释迦牟尼大抵如此。老子做了隐士，耶稣猛一点，治病除魔显神迹，却被人给钉死了。咱得承认没法改变世界，之前惹是生非都是证明自己有点小聪明小勇气。混口饭吃，睡好觉，读经念佛。够了。

----------

中国人就是牛，拿下“首金”“首铜”，让别人“首银”去吧。。。。

----------

又有一个朋友离婚了。朋友感慨说当下社会的各种组织都极易破碎，婚姻关系、雇佣关系、联盟关系等等。社会上有各种压力，要增长、要还贷、要安全、要攀比.....压力大了关系就破碎组织就变形。还说互联网对此也有贡献。到处都是免费，鼠标一划就到了另一家网站，当然不肯承受压力而是随时准备抬脚走人。

----------

我这人脾气好，每次和讨厌的人说话，总是面带笑容，默默的用中指的推推眼镜…

file:../images/smile-and-middle-finger.jpg

----------

一个设计师独白：甲方虐我千百遍，我待甲方如初恋。有朝一日做甲方，虐遍天下设计院。。。

----------

在开幕式演唱红歌 hey 朱德 引发极大反响之后，博伊尔已经决定闭幕式压轴曲目由大卫鲍伊演唱 shopping for girls （小平为女孩），旨在向另一伟大的中国领袖致敬，感谢他带领中国结束革命年代转型世俗社会、并为世界最具潜力经济体融入全球市场打下基础。

----------

伦敦奥运开幕式选用红歌《hey，朱德》作为压轴歌曲，引发热议。据导演介绍，这一选择有深意，该歌曲是由同情革命的披头士乐队于1968年所作，其中有“hey，朱德，don't make it bad”的歌词。当时，中国文革刚刚开始，词作者向中国隐晦喊话，寄望地位较高的元帅朱德勇于担当，出面阻止乱象。

----------

同时也有历史学家提出不同意见，认为这首歌实际反映了初上井冈山时的真实革命状况：革命队伍草创薄弱，反动派步步紧逼，袁文才等匪气未脱，部分指战员包括朱德同志在内，对革命前景一时有所悲观，此时毛委员展现了一位革命家的高瞻远瞩和大无畏精神，他表示：hey，朱德，don't make it bad

----------

寝室有一同学去厕所，玩手机不小心把手机掉下去了，然后，就回去拿了双筷子准备夹出来，正当他要下筷子捞时，一哥们进了厕所看到此景，那人关心地问道：“哥们，还没吃啊”

----------

程序猿问科比：“科比，你为何如此成功？”科比反问：“你知道洛杉矶每天凌晨4点的样子吗？”程序猿：“知道，那个时候我一般还没下班。你问这个干嘛？”科比：“不干嘛，草！”谈话结束了！

----------

因为有前科，都可以预计接下来会发生什么：1、煽情，着力宣传暴雨中的感人事迹，顺杆上升为北京精神2、各路马后炮砖家，大谈城市规划3、官员强调并非ZF不作为或乱作为，实乃天意，61年罕见才会至此4、表决心，谈整改，新闻稿最后一句肯定是“让我们拭目以待”，再一次出现类似情况，前面四点依次循环

----------

某种程度上来说，运动员比小姐都可怜，同样是生计所迫，年纪轻轻开始透支身体，小姐起码是卖，一次一结账，旱涝保收，而运动员则是去赌， 拿到冠军你就牛逼了，拿不到冠军你就歇逼了。更倒霉的是小姐收了钱不用被央视记者问脑残问题，也不用跟谁感恩戴德，运动员就不行，谢错顺序还他妈挨骂。

----------

一女吊丝签名：多年之后，你若娶了，我若没嫁。叫你儿子放学路上小心点。。。

----------

现在小学三年级的暑假作业真难啊，昨天看到侄子的暑假作业有一题什么逻辑规律题，哥想了半天都想不出来，求各位大神解答：986F、875E、764D、653C、--、431A，请问--处应该填什么呢？真心求解答

----------

去停车场取车，发现车头灯被人撞坏了！而且还有不少划伤！附近没见肇事车辆！但是还好，雨刷下压着一张纸条，是肇事着留下的。我拿起来，见上面写着：“抱歉，倒车时不小心撞了你的车灯，现场目睹的人看到我留这张字条时都对我点头面露微笑，他们以为我在写姓名和电话号码给你，可是我没有。

----------

在办公室接待应聘者，拿着那登记表，瞅了好久，弱弱地问：木棍？你叫木棍？那求职者脸都绿了，恶狠狠地回：我叫林昆！然后整个办公室3秒内一片静寂......接着狂笑不止.....

----------

他出身大户门第，身价数十亿，本应是娶女星玩模特的年纪，但是为了自己的信仰，他把数十亿换成了AK47和RPG，钻进了山洞对抗美帝主义，十年来让FBI和CIA颜面扫地，现在评说他是好坏已经没有意义，不过，他的一生注定是个 legend——传奇!—TO: Osama Bin Laden 本·拉登！ 

