* fun
--------------------

学会欣赏别人：1、不能欣赏别人时，等于创造了一个不与别人合作的理由。2、学会欣赏别人是一眼就能发现别人的优点，而不是穿透般的看到别人的不足。3、当我们会“与别人的优点合作，与别人的缺点保持距离”时，我们就成了资源高手。4、一个人最喜欢把自己的价值，赠送给懂得欣赏的人。

--------------------

认识自己的11个问题：1.我喜爱做什么？2.我擅长做什么？3.我本性是什么？4.什么对我最重要？5.我为何而生？6.我独特的才能天赋是什么？7.若不为金钱而生我会做什么？8.我生命的特殊目的是什么？9.什么是只能由我来完成的事？10.什么是我终生要去完成的？11.我希望自己的人生最终被怎样概括？

--------------------

其实文凭不过是一张火车票，清华的软卧，本科的硬卧，专科的硬座，民办的站票，成教的在厕所挤着。火车到站，都下车找工作，才发现老板并不太关心你是怎么来的，只关心你会干什么。

--------------------

file:../images/exam-cheating.jpg

--------------------
*现代人必须具备的十种素质*
   - 储蓄友谊
   - 学会放手
   - 播种善良
   - 懂得音乐
   - 避开得不到之苦和钟情之苦
   - 学会承受
   - 常怀感恩的心
   - 热爱工作
   - 勤于学习
   - 热爱运动

--------------------
*我想成为坐在路边鼓掌的人*

我那上国中的女儿，她同学都管叫她23号。她的班上总共有50个人，而每次考试，女儿都排名23。久而久之，便有了这个雅号，她也就成了名副其实的中等生。我们觉得这外号刺耳，女儿却欣然接受。老公发愁地说，一碰到公司活动，或者老同学聚会，别人都对自家的’小超人’赞不绝口，他却只能扮深沉。人家的孩子，不仅成绩出类拔萃，而且特长多多。唯有我们家的23号女生，没有一样值得炫耀的地方。因此，他一看到娱乐节目那些才艺非凡的孩子，就羡慕得两眼放光。

后来，看到一则九岁孩子上大学的报导，他很受伤地问女儿：『孩子，妳怎么就不是个神童呢？』女儿说：『因为我爸爸不是神父啊!』老公无言以对，我不禁笑出声来。中秋节，亲友相聚，坐满了一个宽大的包厢。众人的话题，也渐渐转向各家的小儿女。趁着酒兴，要孩子们说说将来要做什么？钢琴家，明星，政界要人，孩子们毫不怯场，连那个四岁半的女孩，也会说将来要做电视的主持人，赢得一阵赞叹!15岁的女儿，正为身边的小弟弟小妹妹剔蟹剥虾，盛汤揩嘴，忙得不亦乐乎。大家忽然想起，只剩她没说了。在众人的催促下，她认真地回答： 『长大了，我的第一志愿是，当幼儿园老师，领着孩子们唱歌跳舞，做游戏。』众人礼貌地表示赞许，紧接着追问她的第二志愿。她大大方方地说：『我想做妈妈，穿着印叮当猫的围裙，在厨房做晚餐，然后给我的孩子讲故事，领着他在阳台上看星星。』亲友愕然，面面相觑，不知道该说些什么。老公的神情，极为尴尬。回家后，他叹着气说：『你还真打算让女儿将来当个幼儿园老师？我们难道真的眼睁睁地看着她当中等生？』

其实，我们也动过很多脑筋。为提高她的学习成绩，请家教，报辅导班，买各种各样的资料。孩子也蛮懂事，漫画书不看了，剪纸班退出了，周末的懒觉放弃了。像一只疲惫的小鸟，她从一个班赶到另一个班，卷子，练习册，一沓沓地做。但到底是个孩子，身体先扛不住了，得了重感冒。吊着点滴，在病床上，她还坚持写作业，最后引发了肺炎。病好后，孩子的脸小了一圈。可期末考试的成绩，仍然是让我们哭笑不得的23名。

后来，我们也曾试过增加营养、物质激励等等，几次三番地折腾下来，女儿的小脸越来越苍白。而且，一说要考试，她就开始厌食，失眠，冒虚汗，再接着，考出了令我们瞠目结舌的33名。我和老公，悄无声息地放弃了轰轰烈烈的揠苗助长活动。恢复了她正常的作息时间，还给她画漫画的权利，允许她继续订《儿童幽默》之类的书报，家中安稳了很久。我们对女儿，是心疼的，可面对她的成绩，又有说不出的困惑。

周末，一群同事结伴郊游。大家各自做了最拿手的菜，带着老公和孩子去野餐。一路上笑语盈盈，这家孩子唱歌，那家孩子表演小品。女儿没什么看家本领，只是开心地不停鼓掌。她不时跑到后面，照看着那些食物。把倾斜的饭盒摆好，松了的瓶盖拧紧，流出的菜汁擦净。忙忙碌碌，像个细心的小管家。野餐的时候，发生了一件意外的事。两个小男孩，一个数理天才，一个英语高手，两人同时夹住盘子上的一块糯米饼，谁也不肯放手，更不愿平分。丰盛的美食，源源不断地摆上来，他们看都不看。大人们又笑又叹，连劝带哄，可怎么都不管用。最后，还是女儿，用掷硬币的方法，轻松地打破了这个僵局。回来的路上，堵车，一些孩子焦躁起来。女儿的笑话一个接一个，全车人都被逗乐了。她手底下也没闲着，用装食品的彩色纸盒，剪出许多小动物，引得这群孩子赞叹不已。直到下车，每个人都拿到了自己的生肖剪纸。听到孩子们连连道谢，老公禁不住露出了自豪的微笑。

期中考试后，我接到了女儿班主任的电话。首先得知，女儿的成绩，仍是中等。不过，他说：『有一件奇怪的事想告诉我，他从教三十年了，第一次遇见这种事。语文试卷上有一道附加题：你最欣赏班上的哪位同学，请说出理由。除女儿之外，全班同学，竟然都写上了女儿的名字。理由很多：热心助人，守信用，不爱生气，好相处等等，写得最多的是，乐观幽默。』班主任还说：『很多同学建议，由她来担任班长。』他感叹道：『你这个女儿，虽说成绩普通，可是做人，实在很优秀!』我开玩笑地对女儿说：『妳快要成为英雄了。』正在织围巾的女儿，歪着头想了想，认真地告诉我说：『老师曾讲过一句格言：当英雄路过的时候，总要有人坐在路边鼓掌….。』她轻轻地说：『妈妈，我不想成为英雄，我想成为坐在路边鼓掌的人。』我猛地一震，默默地打量着她。她安静地织着绒线，淡粉的线，在竹针上缠缠绕绕，仿佛一寸一寸的光阴，在她手上，吐出星星点点的花蕾。

我心上，竟是蓦地一暖。那一刻，我忽然被这个不想成为英雄的女孩打动了。这世间，有多少人，年少时渴望成为英雄，最终却成了烟火红尘中的平凡人。如果健康，如果快乐，如果，没有违背自己的心意，我们的孩子，又何妨做一个善良的普通人。长大成人后，她一定会成为：贤淑的妻子，温柔的母亲，甚至，热心的同事，和善的邻居何况她是班上50名之中的23名，我们还不庆幸，还不满足?还想要更高人一等，更出人头地!那后面还有27名半数以上的孩子呢﹖如果我是她们的父母，我要如何自处呢﹖在那些漫长的岁月，她都能安然地过着自己想要的生活；她又没学坏，我作为身教言教的父母，能教养孩子长大成人，并成为社会上有用的人，就可告慰先祖，还想为孩子祈求怎样更美好的未来？就算她将来能当上司法官，能考上建筑师，若她心术不正，口是心非，那又有何用？

另：想起爸爸对我说过的话。“我不希望你成才，我只希望你能够成人。”我一直记在心里。

--------------------
*年复一年，计算机人该做什么?*

在一个潮湿的地下室里,一个双眉紧锁的青年,手里拿着干涩的面包,聚精会神地看着桌子上世界地图,他深深地陷入了沉思:国家下一步的发展策略是什么?国际形势会怎样发展?怎样处理好国际关系?如何对美军,台湾全面作战,一个个难题他需要思索,需要抉择.正在这时,外面响起了剧烈的砸门声,一个声音高叫着:”都他妈把门打开,不然踹门了,把身份证暂住证都准备好”.他含泪默不出声…一会儿外面的人走远了,强大的信念再次站了起来,他迅速调整好了情绪,满怀激情地进入了下一番思考.

--------------------
*为什么我们又输了*

一、草皮不适应
1.草皮太硬了。 2.草皮太软了。 3.不适应阔叶草及其他一些草.

二、天气原因
1.下雪。 2.下雨。3.下冰雹。 4.阳光太好了。 5.冷。 6.热。 7.不冷不热（不能给对手造成麻烦）

三、赛场因素
1.场内因素：A.裁判帮他们。 B.裁判不帮我们。 C.对手身体太强壮。 D.对手技术太细腻。 E.门柱帮了他们。 F.对方守门员发挥超常。 G.补时太短。 H.补时太长。
2.场外因素：A.客场作战，气氛影响。 B.主场作战，干扰太大。 C.观众不为我们喝彩。 D.有人往场内扔手雷。

四、抽签抽的不好
1.同组都是强队，按惯例当然应该中国队输。
2.同组都是中等水平队，踢输了，主要是想赢怕输的思想包袱太重了，队员们没能放得开手脚。
3.同组都是弱队，踢输了，对对手不够重视，麻痹大意，一时疏忽。

五、输球不输嘴
1.对亚洲强队踢输了，是恐X心理在作怪，走不出阴影。
2.对亚洲弱队踢输了，对手进步太大了，太大了，我们对他们没有秘密可言。
3.对欧洲弱队踢输了，中国队输给了欧洲队。
4.对欧洲强队（比如意大利队）0：1踢输了，告诉大家一个好消息：中国队仅以0：1输给了强大的意大利队！
5.对欧洲强队（比如意大利队）0：10踢输了，中国队踢出了自己的一贯水平，队员们也努力了，结果也不出全国人民的意料。
6.对欧洲强队（比如意大利队）0：100踢输了，精彩的比赛！意大利某球星进了20个，某球星进了25个！看来中国队跟意大利队的水平差距确实是有一点的。

六、没用的“海龟”
“海龟派”没回来踢输了，我们雪藏主力；“海龟派”回来踢输了，时差没倒过来。

七、基础条件差
1.主教练技术差！
2.中国球迷素质差！
3.中国足协这个名字差！
4.中国队队医技术差！
5.中国足协领导人办公室里的那位倒水扫地的大妈差！

八、终于…
草皮不软不硬，天气不冷不热，裁判和门柱净帮我们，对方没有守门员，补时时间长短由我们说了算，到第三国去比赛，观众全部为我们猛喝彩，观众全都不往比赛 场地扔手雷，抽了一个人人都说好的签，“海龟派”回来后猛睡了一个月倒回时差参加比赛，换了个主教练，换了批外国球迷，换了个中国足协的牌子，换了中国队的队医，换了中国足协领导人办公室里的打杂大妈，踢输了。原因是：今天我们队，真他妈不在状态！

--------------------

伦敦行动：【能告诉13亿人,你们哭什么？】温甬高铁事件，你们没哭；天津大火，你们没哭；北京大水，你们没哭；强奸幼女、逼幼女卖淫，你们没哭；半夜给拖出来，家被强拆，你们没哭；8月大的胎儿强行堕掉，你们没哭；空巢老人留守儿童无人照料，你们依然没哭。。。刘翔不小心摔倒，你们都哭了。。

--------------------

在刘翔摔倒后第一个把他扶起来的匈牙利运动员巴吉·巴拉扎斯说：其实我也听说在贵国不能扶摔倒的人，会被敲诈，要赔很多钱，所以扶之前我犹豫了一下。

--------------------

如果以后全世界都没人要你，一定要记得还有我。我也不要你~

--------------------

在男子10米台双人决赛中，当两位选手身高、体重和年龄差异都很大的选手齐齐入水之后，电视解说员认真地请教旁边的嘉宾：“按道理说，自由落体运动中，质量轻的落得慢，质量重的落得快，他们是怎样控制一起下落呢？”那位嘉宾想了想认真地回答：“那是他们平时认真训练的结果！”

--------------------
*站在洗头房的门口*

夜幕降临，华灯初上的时候，街边一排洗头房无疑成为光怪陆离的都市以唯一的一抹亮色，一点温馨。我酒足饭饱后，站在人头攒动的夜市旁，望着临近的洗头房，心中不禁泛起阵阵感慨：它们卑处一隅，绝不炫耀，毫无所求，只知奉献，精巧别致的房间透露着橘红色的灯光，以一种柔和暧昧和都市里华而不实的霓虹灯苍白刺眼的路灯对峙着，争辩着，以无言的行动响应着国家节约型社会的号召。周围尽管一片杂乱喧嚣，但它的门面布局仍是那么古色古香，让你不由得驻足停留，细细欣赏。传统的对联式门框在这里复现：上联：按摩，下联：休闲，横批：美容美发，将中国风的精髓发挥得淋漓尽致。洗头房内不时传来形象代言人任贤齐的歌声：“ 我让你依靠，让你靠，没什么大不了”，更增添了几分文化气息。一切的特色让街边那些大楼广场黯然失色。

倚门站立着几位年轻的姑娘，身着复古的服饰，仅以一片红花布遮住前胸，让我想起远古人民的伟大。她们脸上挂着诚挚的笑容，洋溢着扑面而来的热情，召唤鼓舞着沿街的革命同志，不管是满身酒气的大款，满脸疲惫的民工，还是稚气未脱的学生，都一视同仁，毫无偏见，在这个孤寂的夜晚去温暖他们那冰冷空荡的内心，敬业的精神让我不禁肃然起敬。看着看着，我的眼里闪出了泪花，脑海中想起了貂蝉，李师师，秦淮八艳，想起了舒淇，李丽珍，杨思敏，想起了刚刚离我们而去的人民艺术家饭岛爱，以及为事业鞠躬尽瘁死而后已的武藤兰同志，尽管她们分工不同，但没有高低贵贱之分，同样日日夜夜挥汗如雨地工作，在灵与肉的碰撞中，在吆喝呻吟中体验着劳动的光荣和快感。

在频频出入洗头房的人群中，我惊讶的发现了几张极为熟悉的面孔，那不是李书记，张局长，赵主任一行嘛，跟在他们身后的是刚刚提拔的刘干事，白天任劳任怨，以干事为己任，夜晚仍不忘发挥余热，深入洗头房继续干事。这些可亲可敬的领导干部们舍小家，为大家，含泪抛下独守空房的妻子，两眼张望的老人，三过家门而不入，淡泊名利，避开群众们关切火辣的眼光，不辞辛劳，穿街走巷，从群众中来，到群众中去，以*员模范带头作用感染着社会底层，和洗头房的小姐通宵奋战，彻夜长谈，从金瓶梅到春梅腊梅，从票子到马子奶子，检验着社会主义精神文明建设的成果。看在眼里，我热泪盈眶，谁说官民势如水火，我说官民情同鱼水，难舍难分！

夜色渐沉，洗头房的灯逐渐暗了下去，我知道领导和小姐之间的探讨切磋会正在召开。有这样的领导，国之大幸，民之大幸，何愁不能国泰民安，构建和谐社会也自是指日可成。想到这里，我陡增生活的信心和勇气，也默默祝福他们保重身体，但在转身离去的刹那，眼睛就湿润了。

--------------------
*城管*

“在我们眼里,英美特种兵如果是尘埃的话,我们就是沙尘暴”–摘自《城管的优秀历史》前言

“逃跑?我们会让你生活在无限的恐惧之中”–战斗中的一城管言论

“我们在飞机坠毁前,一直以为是遭到了地空导弹的攻击,没想到是城管用竹竿…”–摘自前美苏SU30 F22 F117A等战机飞行员

“当漫天飞舞的板砖和无数看不清来路的拳脚把清点的士兵堵在了阵地上,我真是不敢想象这仅仅是一支受城管训练过的伊军小队”–摘自美军101空降师502团E连米勒上尉

“当我军的一个M1A2坦克分队在一个早晨被全歼时,现场没有爆炸的横迹,只有无数的拳头.那拳头深深的打破了装甲.里面的成员被打成了肉渣”–摘自美军陆战师汤米康林下士

“对不起,我只能回答你我不知道,因为这已经牵涉到国家最高机密”–城管队长回答记者关于城管训练问题

“在我军一次战役中,有一个阵地在郊外我军后方.我军已经突破了外围防线时,那个阵地已经被我们包围了.我们攻克了阵地.我们丢下了500具德意志勇士的尸体,以及3架F22和30台虎式坦克,但抵挡我们3天3夜的居然是5名城管.–摘自德军党卫军78师12团B连曼施坦因中尉

“我们的意志瞬间崩溃,只因为我们知道了对方军中有城管”–美国海军陆战队某指挥员

“配合粪青动员兵效果更好,那是条不可攻破的防线.那是条城管和粪青动员兵组成的钢铁长城.我在此警告各位议院,永远不要跟中国开战,因为中国有城管和粪青”–摘自美国总统奥八牛在珍珠港被3城管和粪青动员兵捣毁后的国会演讲

“当他们出现在战场中时,我知道,我们的末日来了”–前俄罗斯国防部长

“看到他们,我想不到其他的,脑子里只冒出两个字:超人”–前津巴布韦总理

“你一定没见过城管,如果见过,你不会这么完整的站在这里”——一名伤残美兵

“你肯定无法想象,我们一个陆战狙击手一不小心打了一个城管的手,那个城管居然一路杀过来干掉了他.但是…他来的时候已经打死200陆战队,掀翻了3个坦克外加5架武装直升机”–美国三角洲部队的教官

“城管?是撒旦征服世界军队吗?”–原美国炮兵团第二营幸存者

“我一直以为是铁血战士,直到有人告诉我那是城管,我见了城管执法,是的…我见过城管执法…”–美国扭腰精神创伤康复中心患者史密斯.W.布什

“我们的航母还在太平洋集结时,城管已经游过了太平洋占领了我们的首都”–一名美国海军的回忆

“如今能和我对抗的,只有城管.不过幸好,我们是同一阵线的”–摘自春哥自转<我是纯爷们>

“我一生中最大的悲哀就是从最后一场战争中幸存下来,在那次战争中战死沙场一直是我计划中的事,我真是应该在快结束的时候死掉,做为一个士兵能死在城管的手中,是最光荣的牺牲.如果让我选择,我一定会放弃现在的身份,选择做一名城管”–美国总统奥特曼

“我是城管”–人民的好英雄墓碑词.

“当年日本向我们申请核保护的时候,中国就开始组建城管了.可见我们现在的选择没有错,如果一但因为日本而对中国使用了核威胁,那我们将面临更大的灾难”—美国外交部发言人

“我们是人,是的,我们是人”–城管大队答记者问

“我想,他们能徒手搏杀掉上帝”–原美军陆战队73师师长耐肯

“和这样的军队作战是天大的错误”–拿破仑

“呕~他们打上来我们该怎么办?”-—上帝

“我们在一个错误的时间在一个错误的地点和一个错误的人打了一场错误的战争,因为我们没想到对方竟是中国城管”–美军司令兵败棒子国后如是说

“中国城管与核武器轰炸,我选择后者”–日本广岛原子弹轰炸幸存者

“天啊!饶了我吧!我不想面对他们,他们是来自地狱的恶魔.不!和他们相比我情愿面对恶魔!要知道他们可是城管!–美黑人逃兵威尔.修斯

“宇宙已经没有可以打败他们的人了”–M78星云总指挥官烧饼凹凸曼

“他们已经超越了人类想象的极限”–中情局局长罗布斯

“为什么现在美国人都不知道中国城管是什么东西,因为当你门知道它是什么东西的时候,你就会象我一样永远看不到明天的太阳!!”–一群在韩战里的被包围的独立师的最后消息

“鉴于中国城管具有超过核武器的威力,我们决定签订<城管不扩散条约>,并且保证当别人不使用核武器的时候我们不会优先派出城管”–人代表大会一致通过

“由于中国城管的存在我们放弃了进攻地球”–火星国防部长

“如果给我三个城管,我将平息非洲战乱,可惜我只有半个城管…”–联合国秘书长


--------------------

*今天，我查分了，451分*

昨天当我颤抖的双手拨通了北京市高考分数查询系统的时候，我听到了一个女人的声音：451分，当时我委屈的双眼充满了泪水，电话脱手了，狠狠的砸到了我的弟弟，我都没有感觉。

想想，我平时除了上网玩游戏，看点成人片，之外也不谈恋爱，偶尔出去玩，怎么考得这样差呢，平时摸底都是500多分啊，尽管考试纪律不严，但是也充分体现了我的水平啊… …

下午，家人问我考试查分数了吗？我手握着鼠标，头都没回的说道：还没下来呢！

晚上，我隔壁的那个2蛋–平时大家这样叫他的，他爹到我家来玩麻将，说他孩子下午查了分数竟然考了480分，我爸爸捏着二万说道：这不可能吧，这孩子平时摸底不是考的很差吗？听我孩子说也就是4百7左右的样子，冒泡了啊！这分数能上北大了吧！“可不是吗，我老家山东有个亲戚家孩子，考了700分，说只能上二等本科，说要复习去呢，咱北京就是强啊，这就是素质教育！”二蛋他爹弹了弹烟灰满脸自得的说。

哪壶不开提哪壶，2蛋他爹忽然问道：你家孩子考多少分啊？

我赶紧关闭游戏程序，在房间里拨通查询系统，按步骤输入着，然后装作从房间里面出来，说了声：爸，别玩了，我考试成绩出来了。大家都把专注的眼睛投向了我。

451分！我如实地说！没发挥好！

孩子你再查一遍，我爸说道。

我说：不用查了，我都查了N遍了，那个女的还是那样说~~~~~

二蛋他爹安慰我爸说：没事，这可以上清华了，不上北大没关系的~~~~

全家人都笑了。

晚上他们喝酒喝得很晚。

--------------------

大学的时候，刚进学校。学校让我们填一份自我简介，里面包括体育强项。同桌告诉我不要写那种运动会用的到的项目，不然以后运动会会强迫你参加。于是我们写的是高尔夫、网球、滑雪之类的，本想转过身去提醒后面玩的好的男生，结果一看他写的体育强项是双脚踩灯泡、胸口碎大石。

--------------------

刚才有人给我说：如果给我配一个技术大牛，+ 产品经理，+ 营销总监，+ 运营总监 我就可以创业了。我问，配了这些人以后，还要你干嘛？

--------------------

买了瓶饮料打不开盖子，想随便找个路人开开，但是不好意思，于是冲向了警察叔叔，叔叔一脸惊喜地刚说：谢……我说能不能帮我拧开瓶盖！事成之后我谢谢走了，好像听到心碎的声音 ~

--------------------

祝贺张学友郭富城获得奥运会羽毛球男双金牌(蔡赟/傅海峰)

file:../images/zhangxueyou-guofucheng-olympic-champion.jpg

--------------------

有人喜欢牌子，所以选择了苹果，有人喜欢外观，所以选择了索爱，有人喜欢比硬件，所以选择了三星，有人喜欢性价比，所以选择了小米，有人喜欢从众，所以选择了htc，但有些人还是执迷不悟，所以选择了诺基亚。有人喜欢最炫民族风，所以选择了山寨机。。。

--------------------

乘务员：“先生，飞机马上起飞了，请把手机关掉，好吗？” 乘客：“我开的飞行模式” 乘务员：“对不起先生，现在山寨手机也很多，我们很难保证每个手机都是符合标准的！” F舱乘客大怒，“你说啥？你说俺手机山寨的？老子是苹果的！三卡三待呢！不识货别跟老子吵！”

--------------------

【一个结婚10年的男人总结的】1.在心爱的女人面前,越贱越快乐2.两人吵架后,互换角色再重复一遍刚才吵架的内容;3.在她洗澡的时候悄悄帮她把拖鞋换个方向,要刷牙的时候帮她把牙膏挤好漱口水倒好;4.副驾驶的位子是老婆的专座;5.不要以为沉默很酷,两个人在一起还是要多沟通比较好

--------------------

皮格马利翁效应：希腊神话中国王皮格马利翁是一名雕塑家。他用象牙雕塑了一位美丽的美女。他深深爱上了这个美女，他祈求女神让雕象活过来。他的真诚感动了女神，女神决定帮他。不久，雕象活过来了，并成为了皮格马利翁的妻子。后被教育心理学引用，意思是如果你相信他行，他就会真的行。

--------------------

突然听到解说员说“这是一名92年出生的老将。”顿时感觉这个世界太特么凶残了。

--------------------

市场不好，现在质量好点的创业项目或创业者比去年少了至少七成，这种状态非常明显也已持续半年。在这种环境下，敢于出来创业的人虽然数量少了很多，但质量会更高，更成熟，想的更清楚也更有胆识。我相信N多年后我们回顾这段时间，会发现那时很多牛逼公司都是在这段时间里创建，突围和壮大的。

非常认同这个说法。vc不仅仅是给你钱，也会帮助你思考，帮助你获得资源，他们慎重一点对创业风险控制有很大的好处。

--------------------

员工的离职原因林林总总，只有两点最真实：1、钱，没给到位；2、心，委屈了。这些归根到底就一条：干得不爽。员工临走还费尽心思找靠谱的理由，就是为给你留面子，不想说穿你的管理有多烂、他对你已失望透顶。仔细想想，真是人性本善。作为管理者，定要乐于反省。

--------------------

1思想就像内裤，要有，但不能逢人就证明你有。2我可以选择放弃，但绝不放弃选择。3君子报仇，十年不晚。小人报仇，从早到晚。4我们需要马桶精神，按一下，什么都干净了。5人家有背景，而我只有背影。6眉毛上的汗水，眉毛下的泪水，你总得选一样。7财富改变不了个性，却能让人露出本性。

--------------------

王海滨：到北大读书后，雷声整个人的精神气质有了提升，这对于一个剑客非常重要。雷声：其实北大真正的作用是帮我突破了一个技术瓶颈。记者：噢？雷声：以前我一直解决不了出剑时手腕抖动的技术问题，甚至想到了退役，直到有一天我观察到了北大学一食堂打菜师傅是怎么用勺子的....

--------------------

file:../images/company-architecture.jpg

----------

女同志要想成功须付出更多。要想成功：
   - 一是要自信。
   - 二是要融洽上下级关系乐于助人要知道情商占成功的80%。
   - 三是从琐事做起不能浮躁做每件事尽可能尽善尽美。在国家机关学历不重要，只有在提拔时有用。
   - 四是一旦有机会就要有所表现。不能时刻计较得失。做人热情，大度。小事不计较。

-----

如果你在过完枯燥痛苦的一生后郁郁而终。那是因为你一直听妈妈的话，爸爸的话，老师的话，牧师的话，或者电视里那些大家伙们说的话。他们告诉你什么才是对的。我只想说，你这样死去也活该。

-----

和妹子相处，要义就是： 若她涉世未深，就带她看尽人间繁华； 若她心已沧桑，就带她坐旋转木马。和阿哥相处，要义是：若他情窦初开，你就宽衣解带；如他阅人无数，你就灶边炉台。

-----

培训的时候听上级领导说，全国党员有8000多万，而全世界超过8000万人口的国家不过14个。俺就在想，要是让全体党员随便割据个地方，从中国独立出去，组建一个国家，8000万最先进的人都保持同一信仰信念，没有不明真相的群众干扰建设，没有杂音和不良思潮，世界上第一个共产主义国家不就诞生了么

-----

什么是球星效应？ ——齐达内退休了，法国低迷了6年，这就是球星效应 ——普斯卡什退休了，匈牙利低迷了60年，这就是球星效应 ——高俅退休了，中国低迷了1000年，这就是球星效应

-----

自从我国引入劫持人质现场谈判专家制度，劫匪被击毙的几率反而提高。专家们把现场谈判的录音拿来研究，发现总是到这一句时谈判宣告破裂：“你一定要相信党和政府。”

-----

中午吃饭，旁边一桌的大姐结完帐说：＂开张发票，中国人民银行。＂服务员说：＂您写一下。＂大姐答：＂照钱上面写。＂

-----

猪圈里,公猪总是把最好的给母猪吃.忽然有一天,公猪性情大变,将好吃的抢着吃,只给母猪吃一点点.每晚不睡警惕张望,母猪大为失望,看着自己在消瘦 公猪越来越肥,她恨公猪不爱她了!有一天,公猪被拖到屠宰场,母猪看到张纸条:“以后少吃点.如果爱无法用语言表达,我愿意用生命来证明!”

-----

【一个男人的称号】“伟大领袖”、“天赐大将军”、“世界著名的文学家”、“我们星球的卫士”、“所有杰出将军中最杰出的将军”、“众神之神”、“21世纪的北极星”、“一位拥有百科全书一样丰富知识”的“哲学巨人”、“人类最伟大的音乐天才”、“人类智慧的化身”。

file:../images/great-general.jpg

-----

如果你在澳大利亚电子产品Kogan的网站上进行网购的话,使用IE7的用户们可能会惊喜地发现他们需要你多付6.8%钱.收钱理由:我们费了这么大工夫让网站在IE7下看起来和其它浏览器的效果一样,你们理应付给我们辛苦费.PS:建议IE6收更多费用,解放前端码农,不用在去做无用的大量的Css Hack工作.

-----

file:../images/dont-think-yourself-as-an-ugly-person.jpg

--------------------

“麻麻为什么金牌和铜牌待遇差这么多？”“孩子，你知道世界第一高峰么？”“恩，珠穆朗玛峰嘛。”“那世界第三高峰呢？”“干城章嘉峰啊，麻麻我们不要讨论这个问题了，继续讨论金牌和铜牌的事情啊。”“。。。我没什么可说的，让你整天看那些没用的地理书。。”

--------------------

一人到精神病院送东西，刚到医院，车胎爆了。下车修理一不留神，车胎上的四个螺丝滚到下水道里，他在那儿干着急。一个精神病路过看了看：你把剩下3个轮胎，各拔1个螺丝下来，装到备胎上，然后把车慢慢开到市区，找家修车的不就行了。车主问他，你不是精神病么？精神病说——我是有精神病，但不是傻子。

--------------------

 绝妙的真的假新闻：勃列尼涅夫走路快，每每和来访的外国领导人比赛。一次和尼克松举行竞走比赛，结果，勃输了。但《真理报》（这名字！）的报道却是：在昨日美苏举行的一场竞走比赛中，我国领导人勃烈日涅夫同志获得了第二名的好成绩，而美国领导人尼克松获得了倒数第二名。这就是某些国家的文风啊。

--------------------

当你决定要创业时，便意味着：1、没有了稳定的收入；2、没有了请假的权利；3、没有了得红包的机会。然而却更意味着：1、收入不再受限制；2、时间运用更有效；3、手心向下不求人，想法若不同，结果便不同；选择不一样，生活才变样。

----------

我一直愚蠢到认为自己能改变世界。想想这个地球上的真牛人是怎么过的。孔子在世也就影响了几十个学生留了几本书，释迦牟尼大抵如此。老子做了隐士，耶稣猛一点，治病除魔显神迹，却被人给钉死了。咱得承认没法改变世界，之前惹是生非都是证明自己有点小聪明小勇气。混口饭吃，睡好觉，读经念佛。够了。

----------

中国人就是牛，拿下“首金”“首铜”，让别人“首银”去吧。。。。

----------

又有一个朋友离婚了。朋友感慨说当下社会的各种组织都极易破碎，婚姻关系、雇佣关系、联盟关系等等。社会上有各种压力，要增长、要还贷、要安全、要攀比.....压力大了关系就破碎组织就变形。还说互联网对此也有贡献。到处都是免费，鼠标一划就到了另一家网站，当然不肯承受压力而是随时准备抬脚走人。

----------

我这人脾气好，每次和讨厌的人说话，总是面带笑容，默默的用中指的推推眼镜…

file:../images/smile-and-middle-finger.jpg

----------

一个设计师独白：甲方虐我千百遍，我待甲方如初恋。有朝一日做甲方，虐遍天下设计院。。。

----------

在开幕式演唱红歌 hey 朱德 引发极大反响之后，博伊尔已经决定闭幕式压轴曲目由大卫鲍伊演唱 shopping for girls （小平为女孩），旨在向另一伟大的中国领袖致敬，感谢他带领中国结束革命年代转型世俗社会、并为世界最具潜力经济体融入全球市场打下基础。

----------

伦敦奥运开幕式选用红歌《hey，朱德》作为压轴歌曲，引发热议。据导演介绍，这一选择有深意，该歌曲是由同情革命的披头士乐队于1968年所作，其中有“hey，朱德，don't make it bad”的歌词。当时，中国文革刚刚开始，词作者向中国隐晦喊话，寄望地位较高的元帅朱德勇于担当，出面阻止乱象。

----------

同时也有历史学家提出不同意见，认为这首歌实际反映了初上井冈山时的真实革命状况：革命队伍草创薄弱，反动派步步紧逼，袁文才等匪气未脱，部分指战员包括朱德同志在内，对革命前景一时有所悲观，此时毛委员展现了一位革命家的高瞻远瞩和大无畏精神，他表示：hey，朱德，don't make it bad

----------

寝室有一同学去厕所，玩手机不小心把手机掉下去了，然后，就回去拿了双筷子准备夹出来，正当他要下筷子捞时，一哥们进了厕所看到此景，那人关心地问道：“哥们，还没吃啊”

----------

程序猿问科比：“科比，你为何如此成功？”科比反问：“你知道洛杉矶每天凌晨4点的样子吗？”程序猿：“知道，那个时候我一般还没下班。你问这个干嘛？”科比：“不干嘛，草！”谈话结束了！

----------

因为有前科，都可以预计接下来会发生什么：1、煽情，着力宣传暴雨中的感人事迹，顺杆上升为北京精神2、各路马后炮砖家，大谈城市规划3、官员强调并非ZF不作为或乱作为，实乃天意，61年罕见才会至此4、表决心，谈整改，新闻稿最后一句肯定是“让我们拭目以待”，再一次出现类似情况，前面四点依次循环

----------

某种程度上来说，运动员比小姐都可怜，同样是生计所迫，年纪轻轻开始透支身体，小姐起码是卖，一次一结账，旱涝保收，而运动员则是去赌， 拿到冠军你就牛逼了，拿不到冠军你就歇逼了。更倒霉的是小姐收了钱不用被央视记者问脑残问题，也不用跟谁感恩戴德，运动员就不行，谢错顺序还他妈挨骂。

----------

一女吊丝签名：多年之后，你若娶了，我若没嫁。叫你儿子放学路上小心点。。。

----------

现在小学三年级的暑假作业真难啊，昨天看到侄子的暑假作业有一题什么逻辑规律题，哥想了半天都想不出来，求各位大神解答：986F、875E、764D、653C、--、431A，请问--处应该填什么呢？真心求解答

----------

去停车场取车，发现车头灯被人撞坏了！而且还有不少划伤！附近没见肇事车辆！但是还好，雨刷下压着一张纸条，是肇事着留下的。我拿起来，见上面写着：“抱歉，倒车时不小心撞了你的车灯，现场目睹的人看到我留这张字条时都对我点头面露微笑，他们以为我在写姓名和电话号码给你，可是我没有。

----------

在办公室接待应聘者，拿着那登记表，瞅了好久，弱弱地问：木棍？你叫木棍？那求职者脸都绿了，恶狠狠地回：我叫林昆！然后整个办公室3秒内一片静寂......接着狂笑不止.....

----------

他出身大户门第，身价数十亿，本应是娶女星玩模特的年纪，但是为了自己的信仰，他把数十亿换成了AK47和RPG，钻进了山洞对抗美帝主义，十年来让FBI和CIA颜面扫地，现在评说他是好坏已经没有意义，不过，他的一生注定是个 legend——传奇!—TO: Osama Bin Laden 本·拉登！ 

--------------------

file:../images/hey-jude.jpg

