* fun
--------------------
真兄弟！！

file:../images/good-brother.jpg

--------------------
幼儿园开学，许多孩子被送来，家长走后，孩子们哭闹着，简直跟宰猪场差不多！这时候，唯独有一个小孩蹲在墙角巨蛋定，老师准备好好夸一下他，刚走近，那个小孩以迅雷不及掩耳之势，抢过老师手机，连号码都没拨，拿起手机就对着手机哭喊着：“爸爸，快来救我啊！我被妈妈卖了...

--------------------
海南省海口市海府路与国兴大道的交叉路口处，有几块路标牌重叠挂在一根杆子上，最多的有7块方向牌堆叠在一起，让人眼花缭乱，看了也分不清东西南北，被网友称为“最牛路牌”。

file:../images/hainan-road-sign.jpg

--------------------
电梯坏了，老实巴交的肯德基小哥也不知道打个电话，像圣斗士一样背着四四方方的大箱子一层层地爬楼。我看着有些不忍，就上前与他攀谈，希望借此减轻爬楼的枯燥与疲累。终于，小哥到达了13楼。他感激地对我说，谢谢你，大哥。我说，不必客气，把我订的肯德基给我吧。

--------------------
盘点那些无节操的神级PS

file:../images/fuck-ps.jpg

--------------------
话说天下大势，合久必分分久必合，统一最大的敌人是？是康师傅吧！

--------------------

一路口，一大众和宝马3系在等红灯，对面一宝来不知是抽风的还是怎么了直直冲过来看着马上就要撞到3系了，一个转向撞到了大众，3系就这样唱着最炫民族风走了宝来车主下来一个做辑然后赔笑：“3系是在撞不起，只好撞您的帕萨特了”那大众车主冷笑道：“见过12缸的帕萨特么

--------------------

一直觉得《西游记》有个BUG，唐僧肉吃完长生不死，他为什么不咬自己一口？咬完任你各路妖魔奈我何？轻装上路差旅费省四分之三，后来想明白了，觉得吴承恩设计的真他娘缜密——和尚不能吃肉。

--------------------

 刚刚和几个同事讨论好公司的标准，结论如下：1.前台大美女，2.上班不打卡，3.厕所不排队，4.上网无限制，5工资有点高，6.基本不加班，7.上班不无聊，8.死党四五个，9.出差住五星，10.报销不麻烦，11 team building有点多，12.公司没事就发东西，13.HR和Admin态度好。。。。。。

--------------------

 古代人如何说现在网络语言 【1】 城门失火殃及池鱼——躺着也中枪； 【2】 呜呼！——我靠 【3】 是可忍孰不可忍！——草泥马 【4】 黄袍加身——屌丝的逆袭。

--------------------
file:../images/wife-makes-me-dont-worry.jpg

--------------------
*写代码的，都是特么的诗人*

两个黄鹂鸣翠柳：Tree_0f0=sprintf("2_Bird_ff0/a")；

人生自古谁无死： for_$n(@RenSheng)_$n+="die"；

两岸猿声啼不住：while(1)Ape1Cry&&Ape2Cry；

锄荷日当午：dig?F*ckDang5；

平生不看武腾兰，便称男人也枉然：ps!see(5tl)shit!say(man) 

--------------------
父亲：女儿，请记住这五个人生忠告。1、学会拒绝。2、不畏挑战。3、勤奋好学。4、从不同角度思考问题。5、永不言败！女儿：我懂了，就是“雅蠛蝶”、“大力点”、“不要停”、“换个姿势”、“再来一次吧”！。

--------------------
一中国人给外国人考听力试题，题目如下： 羊毛衫大减价啦，件件10元，样样10元，全部10元，问：什么10元？ A件件 B样样 C全部 D羊毛衫

--------------------
小张童鞋很喜欢吃素包子，一天去买包子的时候发现涨价了，就问老板“怎么包子涨价了？”老板说：“因为肉价涨了”。小张就问“肉涨价，素包子为什么要涨价啊？”老板说：“因为做包子的师傅他要吃肉啊！”

--------------------
以前有女朋友的时候每次被问在干嘛我都要想一种在电脑前看书写代码的讲法，比如抚摸键盘、研究屏幕像素点变化等等

--------------------
孔子是微博开创者，《论语》是最早微博集： 1、每条论语都未超过140字； 2、言简意赅、寓意深刻； 3、较为碎片化，多为孔子晒心情，交流哲理； 4、互动性强，经常和子贡、颜回、子路等进行回复，互动； 5、孔子拥有3000多粉，其中72人为VIP。

--------------------
什么叫微博？一个约炮都不会的教给你怎么了解女性，一个连圣经基本教义都不懂的演员向你传教，一个连法律基本程序都不懂的律师向你传授依法治国，一个连真假都搞不清的贩子教你玉的鉴定，一个经常造谣传谣的南方系媒体人告诉你记者的基本操守。这就像：一个傻逼告诉你他可以教给你如何变聪明。

--------------------
一男发浪漫短信给女友：你在干嘛？在做梦吗？把梦传给我；在笑吗？把笑发过来；在哭吗？把泪水传过来，让你的眼泪和我一起悲伤。女友回复：我在便便。

--------------------
*我的男朋友是个学霸，你们输给DOTA，我输给代码*
昨天七夕，他来接我下班，还带我去吃饭，听起来温馨浪漫。一坐下来就忙问我要笔记本和笔，问他要干什么，答曰：构思数据库。。。数据库是男是女啊？长得好看吗？身材好吗？

他吃得比我快，吃完后坐着看我，我一边埋头吃一边想，这场面真是温馨，喜欢的人在对面，看着我吃好吃的。想起就感动。结果我一抬头，尼玛，原来是在看我背后的电视，我转头看过去，发现新闻女主播长得还挺好看的，就问他“她好看还是我好看？”。结果人转过头来很严肃地对我说“摩托罗拉要在中国裁掉80%的员工了”。。。。。。。我心里有万头草泥马狂奔而过，多少次这样的对话我都只想以“关我屁事，关你屁事”来结尾啊

新闻播完了，转过头来和我聊谷歌和摩托罗拉，说谷歌的软件卖的贵，我嘴贱问了句“为什么贵？”，“因为中国有GFW，谷歌的服务器在国外”，再次嘴贱“你又说我听不懂的了，GFW是什么？”。“就是防火墙啦”。“那你为什么不直接说防火墙？！”。“因为那是特殊的防火墙啊”。“那你为什么不直接说特殊的防火墙，说个GFW，全称是什么嘛？”，“great fire wall 啊，你知道great wall 吧，就是长城的意思”。。。万头草泥马再次呼啸而过，尼玛，我六级松松通过，还用你来解释小学词汇great wall。卧槽！恋爱中的女生不至于傻逼成这样啊卧槽！

早上起来打电话：“在干嘛？”，“写代码”。

中午吃饭打电话：“在干嘛？”，“写代码”。

午睡前打电话：“在干嘛？”，“写代码”。

晚上一起吃饭：“在想什么？”，“构思代码”。

睡前打电话：“睡了嘛？”，“没”，“那在干嘛？”，“写代码”。

以前看到一条状态，是一个工科男给他女朋友做了个网站作为生日礼物，里头有一只很可爱的小老鼠。我让他去看这个网站，说是一个工科男做给人家女朋友的，你看那只老鼠多可爱。意思明显到只差说“你看看人家！”了。结果长时间未回复我，过了好久，给我发来了一大段代码，真的一大段，都刷屏了，最后来了句：“这是那只老鼠的代码，你不是喜欢那只老鼠吗？”。。。。。草泥马再次奔腾起来。。。

记得第一次去上橄榄球课，上完后电话里对他抱怨：“橄榄球好累啊，跑来跑去的，好辛苦”，傻逼都知道这个时候应该回答“累了一天要好好休息呀”、“上课不要太拼命”诸如此类安慰的话。结果丫说“橄榄球就是这样啊，它上下半场加起来只有14分钟，规则是blablabla……”，我听着听着就睡着了。。。。我有涵养吧~

每每这个时候，我总是想为什么我会和这样一个人在一起这么久？或许是因为他在一边构思那个代码小三时，一边还是牵着我的手。或许是我随便一说想去哪儿，他就会马上把路线和住宿的查好。或许是只要我一说不舒服，就马上把要用的药都查好送过来。或许是我一生气放大招不理他，他坐在边上不知所措的样子。或许是我一次次任性地说“你一点都不好，一点都不喜欢我”的时候，你生气地说“我要不喜欢你，我大老远跑来给你送吃的？！”

最后我们往往都是哀叹一声“唉，谁叫我喜欢你呢”……

--------------------
今夏巨星扎堆发片，乐坛型男潮叔包青天携新专《Judge Bao》空降本周华语榜中榜：1.你永远不懂爷的黑(Black Forever) 2.看我脸色72变(Poker Face) 3.本府是碳，黑到忧伤(Black Tragedy) 4.开封府之夏(Summer in KaiFeng) 5.升堂（RAP）6.王朝马汉今何在(Pray for My Soldiers) (via 谁允许你直视本蜀黍)

file:../images/judge-bao.jpg

--------------------
#+BEGIN_EXAMPLE
冰清玉洁武藤兰，三贞九烈小泽圆。
不近女色陈冠希，天生丽质金喜善。
坚持原创郭小四，低调沉稳数韩寒。
清心寡欲小日本，万恶帝国美利坚。
与邻为善以色列，安宁祥和阿富汗。
国强民富看朝鲜，宇宙起源在南韩。
民主典范金正日，和平斗士本拉丹。
从不掉线天涯网，从不删贴管理员。
优秀记者冬日娜，尖嘴猴腮毕福剑。
只讲真话西西踢维，人民喉舌焦点访谈。
天籁之音曾轶可，大家闺秀李宇春。
守口如瓶宋祖德，字正腔圆周杰伦。
洁身自好赵忠祥，铁汉无泪冷朱军。
水准专业孙正平，从不口误韩乔生。
貌若天仙芙蓉姐，百毒不侵满文军。
诚信经营陈天桥，永不模仿马化腾。
重庆好人谢才萍，无家可归贾君鹏。
低速行车杭州市，交通顺畅北京城。
舍己为人范跑跑，眉清目秀冯小刚。
用色淡雅张艺谋，代言保真唐国强。
物美价廉奥菲斯，低调奢华阿迪王。
学识渊博余秋雨，淡泊名利查良镛。
勤俭持家章小蕙，从不炒作张纪中。
白面书生奥巴马，没有炸弹巴格达。
和风细雨马景涛，苗条骨感沈殿霞。
高大威猛属梅西，从不假摔是Ｃ罗。
料事如神贝球王，只争第一是国安。
足坛巨擘李大帝，世界强队国足男。
文明执法闵行区，国虎出没镇坪县。
干净公平全运会，春风拂面好城管。
无毒无害三鹿奶，营养健康方便面。
强身健体俯卧撑，安全游戏躲猫猫。
爱管闲事酱油党，不明真相老百姓。
水深火热蛮夷众，欢欣鼓舞天朝民。
#+END_EXAMPLE

--------------------
都说骂人要文明，于是某同学把“真TMD不爽”译为“诚其母之不悦！” 

--------------------
中国的汽车广告只有两种！！！中低端车永远是：老子家庭幸福！有娇妻！有可爱的儿女！老子喜欢带全家人开车出去玩！中高端车永远是：老子事业有成！有美女！有红酒！有合同可以签！老子喜欢独自开车出去装逼！

--------------------
这是早上乘地铁时遇到的牛人。地铁上，突然一个哥们儿的电话铃声大作，众乘客一听“爷爷，那孙子又给您来电话了……爷爷，那孙子又给您来电话了…… 爷爷，那孙子又给您来电话了……” 只见那哥们儿慢慢悠悠的掏出手机，接听：“喂，爸，什么事…… ”

--------------------
今天客户来银行取钱，坐下一句话说的我石化了：“你好，我死期到了。”

--------------------
开心辞典，小丫主持问选手：一年365日，男人最怕哪一日？女人最怕哪一日？男答：男人最怕1月31日。女答：女人最怕12月1日。小丫：回答正确！! !...........

--------------------
问一懂手机哥们，磨砂屏幕贴膜和普通的膜有什么区别？他默默的发了张图片过来，我瞬间就明白了！

file:../images/polish-difference.jpg

--------------------
偷看某人微博看来个笑话：有個人在internet要reset password,結果他新的password是supermanbatmanironmancatwomanspidermanrobinwashington,知不知道為甚麻？因為rest password 要six characters and at least 1 capital......

--------------------
新兵清理军营围墙卫生，趁没人管趴那偷懒，见一穿便装的大爷在墙外散步，就喊：大爷帮忙买包烟吧，那大爷说你们不是不让抽烟吗？那新兵说我没事的时候抽一根而已，帮帮忙呗，青岛人都是活雷锋。于是大爷就帮他买了一包。晚上开会的时候，队长大骂，MD谁叫司令帮忙买烟的，还青岛人都是活雷锋。

--------------------
据说，扬州一女生因收到玫瑰花后发现是货到付款而与男友分手。。。

--------------------
牛郎和织女的故事告诉我们，偷看女生洗澡是找媳妇的一个好方法

可惜通过这种方式找到的，一年只能见一次。

--------------------

海外争端叠起，我们的看门阿伯说：解放军也该干点事儿了，不能白喝了三十多年茅台吧？

file:../images/boom-it.jpg

--------------------
去饭店吃饭，剩了一些菜，我就对服务员说，给我打个包吧。服务员点了点头，出门喊了几个服务员，冲进来把我的头上打得都是包。

--------------------
 【面试】尼采去面试，面试官问：“你叫什么？”“尼采。”“猜你妹啊！下一个！” 网友跟帖：亏他不叫尼迭！

--------------------

 【段子：数据分析让你更安全】有一个美国数学教授平生最怕坐飞机，他研究了近20年的统计数据，发现恐怖分子带炸弹上飞机的几率其实非常低，但是他还不安心，他又进一步研究数据发现，两个人同时带炸弹上飞机的几率几乎为零，于是从此他坐飞机都自己携带一枚炸弹。

--------------------
不要脸这事，如果干的好，叫心理素质过硬。。。

--------------------
老北京面馆最大特色就是吆喝。有天两人去吃面，跑堂吆喝上了：“5号桌，炸酱面两碗”吃完结帐，共25元8毛。甲说：“给你26，别找了”跑堂接过钱便吆喝：“5号桌有客送小费2毛”满大厅的人回头看他，甲脸红了：“得，那2毛你还是找我吧”跑堂又吆喝上了：“5号桌的2毛小费又要回去了!”

--------------------
问：沙僧担子里究竟挑的什么？答：应该是师傅的内衣裤，剃须刀，还有发蜡，男士洗面奶，墨镜，出入境通行证，银行卡，户口本，导航仪，宝马的驾驶证！大师兄的染发剂，洗发水，护发素，修毛剪。八戒的营养快线，可乐，汉堡，薯条，减肥茶，PSP游戏机，MP3，iPad！

--------------------
*屌丝从毕业时的月入3000到三年后亿万身家*

刚毕业我只有3000，但我立志三年后要月入3万是在一家广告公司，每天跑业务我每天都很勤恳地和前辈学习，连修理打印机都自学成才了老板看我很努力，多有嘉许毕业半年后转正，薪水3300 经理找我谈，说如我愿接受夜班，可再加500 我没动心因为晚上是自我提升的宝贵时间我泡图书馆，借了财务的书来看自己必须有一技之长才有立足之地我开始准备CPA和CFA 广告业务也慢慢上了正轨拿到了单，为公司创造了效益年底公司发了2000的年终奖工作满一年，我向老板提出加薪老板没同意，只说年轻人要多学我非常认同，便更加努力下班后我还发挥大学的长处为小朋友补习功课每周补习10小时，每月40小时每小时我收费40元相当于薪水又多了1600元我去考了CFA一级可惜没过，但我并不气馁我需要更加努力到了第二年年底，加了300薪水每月3600，加上奖金有时能到4000 家教做的也不错，现在50元每小时了东家帮我介绍了别家客户每月补50小时家教收入也达到了2500 通过两年的努力，我有了一些积蓄差不多一万我开了一个淘宝店，先是帮人充话费后来卖点卡无人问津，有时朋友帮衬一下有朋友说必须得刷出来好评才有人买然后我想了想，自己小号买给好评然后被发现了，店被封了申述未果虽然没赚什么钱，不过也没亏年中又考了一次CFA一级，这次过了对未来又有了更多期望交了女朋友，她月薪2000 我抱着她，憧憬未来我向她保证，毕业3年一定年薪30万她不信，说已经两年半了还看不到希望我就拿出我攒的一万块钱，进入了股市开始运气好，很快一万变成了两万我信心愈发强了这样慢慢经营下去，又过了3个月股市跳水，只剩下了500 后来女朋友跑了，但我并不气馁不过，眼看着快到毕业三年的时间我还只是一个月6000上下的收入于是我放大招了，使出了最后的一搏我把我的薪水换算成了越南盾共计月入约1.97亿元是的，我超额实现毕业时的理想了。。。。

--------------------
“我成亲了。”“恭喜恭喜，能讲一下细节吗？”“注册了个淘宝，就变成亲了。” 

--------------------
 【男子因自行车胎被扎爬上25米高广告塔骂街 称爬得高骂得远】夏邑县一男子因自行车胎被人扎破，一怒之下爬上高达25米的广告塔高声叫骂，造成交通堵塞。

--------------------
关于刚刚的小强爬进air usb孔事件,感谢各位提供的宝贵而不靠谱的建议…在试过了狂甩,闪光灯,猛敲等一些列手段无效后,我打开土豆随便开了个flash,不到2分钟小强就主动逃出来了.

--------------------
电影里是嫌犯一死所有的线索都断了；新闻里是嫌犯一死所有的案子都破了。

--------------------
以前爷爷喜欢下棋，下不过邻居大爷，很苦闷，我就想替他报仇。私下找邻居大爷，他说让我，我说不要，打开手机里“象棋大师”，调到专家难度。大爷下一步我摁一步，机器人下一步我学一步。大爷都傻了，连输4局。后来他居然找我拜师，说我是天才，一边玩手机都这么厉害，都不带想棋步的…

--------------------
提问：美国人尿急的时候会变成。。。。。。 回答：姜国人 ！！！

--------------------
阴暗潮湿的北京某地下室，一瘦弱青年一手拿了2块钱一包的烟，一边看着凤凰网军事频道，愁眉紧锁的他陷入了沉思：国家下一步该怎么走？如何突破美国封锁？如何收复台湾？如何保住南沙钓鱼岛？如何剿灭反华势力？一个个难题需要他思索，抉择。此时，传来踹门的咣咣声：开门！警察查暂住证！

--------------------

没见过这么霸气的狮子

file:../images/stone-lion.jpg

--------------------

送给吃货们的打油诗:床前明月光,想喝疙瘩汤。春风又绿江南岸,明月何时烤冷面。人比黄花瘦,犹记锅包肉。小荷才露尖尖角，一看排骨炖豆角。月落乌啼霜满天，松仁玉米地三鲜。君问归期未有期，来盘榛蘑炖笨鸡。我劝天公从抖擞，煎饼果子配鸡柳。在天愿作比翼鸟，街边坐等吃烧烤

--------------------

姓黄的一个父亲，给他儿子取名一个军字。一天，他带儿子等8路公交车，突然车来了。父亲叫道“黄（皇）军，八路来啦！旁人齐投困惑的目光。。。（转）

--------------------

儿子被爸爸修理了，跑去找妈妈诉苦：“妈妈，有人打你儿子你会怎样？”妈妈：“我会打他的儿子报仇！”儿子：“……”

--------------------

我有一个朋友，昨天晚上去吃烤翅，他拿着瓶啤酒对服务员说：“你信不信我能徒手起瓶盖？” 服务员摇头说不信。朋友一拍桌子：“那你还不拿起子去！”

--------------------

和女朋友去逛街，路遇一猥琐男。一个劲盯着我俩看，看到那龌龊眼神我顿生怒气，冲他喊了句“看你妹啊！” 逆天的一幕出现了。我女朋友眼前一亮“哥！你怎么也来逛街”....我勒个去。。 。

--------------------
句型填空：我在路上扶起了一位老奶奶，他抓住我的胳膊，迅速抬头对我说了一句话：“_______ ”「转」

file:../images/when-i-help-grandma.jpg

--------------------

对面坐了一对情侣，男生不好看，女生长得还挺文静。女生跟男友说：今天我看着xxx男友了，丑死了啊啊啊啊，男生说：“比我还丑么？”这时我跟媳妇都以为女生会安慰他，说句老公你不丑之类的，三秒后，女生：跟你不是一个丑法。

--------------------

悟空：师傅，分开前我再问一个问题。唐僧：爱过！悟空：还有一个。唐僧：不后悔！悟空：最后一个…唐僧：你不要说了，自度娘赐贫僧神器之后，为师灭妖效率大幅提高，所以必须裁员精编了…

file:../images/baidu-map-ad.jpg

--------------------

某教授在田间授课：“科学研究要不怕脏。。。”然后他蹲下来，用手指戳了一下地上的牛粪，然后把手指放到嘴里舔净。一同学忙说：“我不怕脏。。。”然后也用手指戳了一下地上的牛粪放到嘴里舔净。教授：“另外还要善于观察，比如说，我刚才是用中指戳粪，但舔的是食指。。。

--------------------

去剪头发，一坐下，剪头发的男生就问：“美女，做个一次性烫好不好？很漂亮的！”我说：“不烫。”几分钟后，他又问：“烫吗？！”我说：“不烫。”过了会儿，剪完开始用吹风机吹了，但是风有点烫，男生问：“烫吗？”我说：“烫！”于是他就给我烫起了头发。。。

--------------------

痞子约架码人，电商约架码货！痞子约架码人比比谁有牛人，电商约架码货比比谁有贱货。

--------------------

缅甸版“龙的传说”：有一条恶龙，每年要求村庄献祭一个处女，每年这个村庄都会有一个少年英雄去与恶龙搏斗，但无人生还。又一个英雄出发时，有人悄悄尾随。龙穴铺满金银财宝，英雄用剑刺死恶龙，然后坐在尸身上，看着闪烁的珠宝，慢慢地长出鳞片、尾巴和触角，最终变成恶龙。
--------------------

朋友有点痔疮，喝酒，吃火锅，第二天会很痛（我之前不知道），昨天我心情不太好，死活拉着要和他喝酒，还吃滴火锅，第二天，上班的时候在电梯里，他突然就对着我说老子以后再也不和你喝酒了，屁股好痛！结果瞬间电梯里就安静了，都是一副我懂了的样子！我。。。

--------------------
*人生最高的境界*

拿沙特工资，住英国房子，用瑞典手机，戴瑞士手表，娶韩国女人，包日本二奶，做泰国按摩，开德国轿车，坐美国飞机，喝法国红酒，抽古巴雪茄，穿意大利皮鞋，看奥地利歌剧，买俄罗斯别墅，雇菲律宾女佣，配以色列保镖，当中国干部。

--------------------
*程序出错后，程序员给测试人员的20条高频回复*

第1条会是什么？猜猜看吧！

   20. “That’s weird…” 很奇怪……
   19. “It’s never done that before.” 以前没这样过的。
   18. “It worked yesterday.” 昨天还好好的。
   17. “How is that possible?” 那怎么可能？（怎么会出问题？）
   16. “It must be a hardware problem.” 这一定是硬件问题。
   15. “What did you type in wrong to get it to crash?” 你输入什么东西后才崩溃的？
   14. “There is something funky in your data.” 你的数据有问题。
   13. “I haven’t touched that module in weeks!” 我好几个礼拜没动那个程序了！
   12. “You must have the wrong version.” 你一定在用错误的版本。
   11. “It’s just some unlucky coincidence.” 这只是凑巧。
   10. “I can’t test everything!” 我无法测试所有东西。（我的机器环境下，无法测试所有的可能情况。）
   09. “THIS can’t be the source of THAT.” “这”不可能是问题的原因。
   08. “It works, but it hasn’t been tested.” 程序能用，不过还没有测试。
   07. “Somebody must have changed my code.” 一定有人改了我的代码。
   06. “Did you check for a virus on your system?” 你的电脑扫描病毒了么？
   05. “Even though it doesn’t work, how does it feel? 即便程序不行了，（你觉得）程序写得如何？
   04. “You can’t use that version on your system.” 你不能在你系统上使用那个版本的程序。（程序版本和系统有冲突。）
   03. “Why do you want to do it that way?” 你怎么会想着那样操作啊？
   02. “Where were you when the program blew up?” 程序崩溃时，你在做什么呢？（做了哪些操作？）  
   01. “It works on my machine” 在我机器上好好的！！！（潜台词：怎么在你那就出问题了呢！！！）

--------------------

file:../images/exam-cheating.jpg

--------------------
*年复一年，计算机人该做什么?*

在一个潮湿的地下室里,一个双眉紧锁的青年,手里拿着干涩的面包,聚精会神地看着桌子上世界地图,他深深地陷入了沉思:国家下一步的发展策略是什么?国际形势会怎样发展?怎样处理好国际关系?如何对美军,台湾全面作战,一个个难题他需要思索,需要抉择.正在这时,外面响起了剧烈的砸门声,一个声音高叫着:”都他妈把门打开,不然踹门了,把身份证暂住证都准备好”.他含泪默不出声…一会儿外面的人走远了,强大的信念再次站了起来,他迅速调整好了情绪,满怀激情地进入了下一番思考.

--------------------
*为什么我们又输了*

一、草皮不适应
1.草皮太硬了。 2.草皮太软了。 3.不适应阔叶草及其他一些草.

二、天气原因
1.下雪。 2.下雨。3.下冰雹。 4.阳光太好了。 5.冷。 6.热。 7.不冷不热（不能给对手造成麻烦）

三、赛场因素
1.场内因素：A.裁判帮他们。 B.裁判不帮我们。 C.对手身体太强壮。 D.对手技术太细腻。 E.门柱帮了他们。 F.对方守门员发挥超常。 G.补时太短。 H.补时太长。
2.场外因素：A.客场作战，气氛影响。 B.主场作战，干扰太大。 C.观众不为我们喝彩。 D.有人往场内扔手雷。

四、抽签抽的不好
1.同组都是强队，按惯例当然应该中国队输。
2.同组都是中等水平队，踢输了，主要是想赢怕输的思想包袱太重了，队员们没能放得开手脚。
3.同组都是弱队，踢输了，对对手不够重视，麻痹大意，一时疏忽。

五、输球不输嘴
1.对亚洲强队踢输了，是恐X心理在作怪，走不出阴影。
2.对亚洲弱队踢输了，对手进步太大了，太大了，我们对他们没有秘密可言。
3.对欧洲弱队踢输了，中国队输给了欧洲队。
4.对欧洲强队（比如意大利队）0：1踢输了，告诉大家一个好消息：中国队仅以0：1输给了强大的意大利队！
5.对欧洲强队（比如意大利队）0：10踢输了，中国队踢出了自己的一贯水平，队员们也努力了，结果也不出全国人民的意料。
6.对欧洲强队（比如意大利队）0：100踢输了，精彩的比赛！意大利某球星进了20个，某球星进了25个！看来中国队跟意大利队的水平差距确实是有一点的。

六、没用的“海龟”
“海龟派”没回来踢输了，我们雪藏主力；“海龟派”回来踢输了，时差没倒过来。

七、基础条件差
1.主教练技术差！
2.中国球迷素质差！
3.中国足协这个名字差！
4.中国队队医技术差！
5.中国足协领导人办公室里的那位倒水扫地的大妈差！

八、终于…
草皮不软不硬，天气不冷不热，裁判和门柱净帮我们，对方没有守门员，补时时间长短由我们说了算，到第三国去比赛，观众全部为我们猛喝彩，观众全都不往比赛 场地扔手雷，抽了一个人人都说好的签，“海龟派”回来后猛睡了一个月倒回时差参加比赛，换了个主教练，换了批外国球迷，换了个中国足协的牌子，换了中国队的队医，换了中国足协领导人办公室里的打杂大妈，踢输了。原因是：今天我们队，真他妈不在状态！

--------------------

伦敦行动：【能告诉13亿人,你们哭什么？】温甬高铁事件，你们没哭；天津大火，你们没哭；北京大水，你们没哭；强奸幼女、逼幼女卖淫，你们没哭；半夜给拖出来，家被强拆，你们没哭；8月大的胎儿强行堕掉，你们没哭；空巢老人留守儿童无人照料，你们依然没哭。。。刘翔不小心摔倒，你们都哭了。。

--------------------

在刘翔摔倒后第一个把他扶起来的匈牙利运动员巴吉·巴拉扎斯说：其实我也听说在贵国不能扶摔倒的人，会被敲诈，要赔很多钱，所以扶之前我犹豫了一下。

--------------------

如果以后全世界都没人要你，一定要记得还有我。我也不要你~

--------------------

在男子10米台双人决赛中，当两位选手身高、体重和年龄差异都很大的选手齐齐入水之后，电视解说员认真地请教旁边的嘉宾：“按道理说，自由落体运动中，质量轻的落得慢，质量重的落得快，他们是怎样控制一起下落呢？”那位嘉宾想了想认真地回答：“那是他们平时认真训练的结果！”

--------------------
*站在洗头房的门口*

夜幕降临，华灯初上的时候，街边一排洗头房无疑成为光怪陆离的都市以唯一的一抹亮色，一点温馨。我酒足饭饱后，站在人头攒动的夜市旁，望着临近的洗头房，心中不禁泛起阵阵感慨：它们卑处一隅，绝不炫耀，毫无所求，只知奉献，精巧别致的房间透露着橘红色的灯光，以一种柔和暧昧和都市里华而不实的霓虹灯苍白刺眼的路灯对峙着，争辩着，以无言的行动响应着国家节约型社会的号召。周围尽管一片杂乱喧嚣，但它的门面布局仍是那么古色古香，让你不由得驻足停留，细细欣赏。传统的对联式门框在这里复现：上联：按摩，下联：休闲，横批：美容美发，将中国风的精髓发挥得淋漓尽致。洗头房内不时传来形象代言人任贤齐的歌声：“ 我让你依靠，让你靠，没什么大不了”，更增添了几分文化气息。一切的特色让街边那些大楼广场黯然失色。

倚门站立着几位年轻的姑娘，身着复古的服饰，仅以一片红花布遮住前胸，让我想起远古人民的伟大。她们脸上挂着诚挚的笑容，洋溢着扑面而来的热情，召唤鼓舞着沿街的革命同志，不管是满身酒气的大款，满脸疲惫的民工，还是稚气未脱的学生，都一视同仁，毫无偏见，在这个孤寂的夜晚去温暖他们那冰冷空荡的内心，敬业的精神让我不禁肃然起敬。看着看着，我的眼里闪出了泪花，脑海中想起了貂蝉，李师师，秦淮八艳，想起了舒淇，李丽珍，杨思敏，想起了刚刚离我们而去的人民艺术家饭岛爱，以及为事业鞠躬尽瘁死而后已的武藤兰同志，尽管她们分工不同，但没有高低贵贱之分，同样日日夜夜挥汗如雨地工作，在灵与肉的碰撞中，在吆喝呻吟中体验着劳动的光荣和快感。

在频频出入洗头房的人群中，我惊讶的发现了几张极为熟悉的面孔，那不是李书记，张局长，赵主任一行嘛，跟在他们身后的是刚刚提拔的刘干事，白天任劳任怨，以干事为己任，夜晚仍不忘发挥余热，深入洗头房继续干事。这些可亲可敬的领导干部们舍小家，为大家，含泪抛下独守空房的妻子，两眼张望的老人，三过家门而不入，淡泊名利，避开群众们关切火辣的眼光，不辞辛劳，穿街走巷，从群众中来，到群众中去，以*员模范带头作用感染着社会底层，和洗头房的小姐通宵奋战，彻夜长谈，从金瓶梅到春梅腊梅，从票子到马子奶子，检验着社会主义精神文明建设的成果。看在眼里，我热泪盈眶，谁说官民势如水火，我说官民情同鱼水，难舍难分！

夜色渐沉，洗头房的灯逐渐暗了下去，我知道领导和小姐之间的探讨切磋会正在召开。有这样的领导，国之大幸，民之大幸，何愁不能国泰民安，构建和谐社会也自是指日可成。想到这里，我陡增生活的信心和勇气，也默默祝福他们保重身体，但在转身离去的刹那，眼睛就湿润了。

--------------------
*城管*

“在我们眼里,英美特种兵如果是尘埃的话,我们就是沙尘暴”–摘自《城管的优秀历史》前言

“逃跑?我们会让你生活在无限的恐惧之中”–战斗中的一城管言论

“我们在飞机坠毁前,一直以为是遭到了地空导弹的攻击,没想到是城管用竹竿…”–摘自前美苏SU30 F22 F117A等战机飞行员

“当漫天飞舞的板砖和无数看不清来路的拳脚把清点的士兵堵在了阵地上,我真是不敢想象这仅仅是一支受城管训练过的伊军小队”–摘自美军101空降师502团E连米勒上尉

“当我军的一个M1A2坦克分队在一个早晨被全歼时,现场没有爆炸的横迹,只有无数的拳头.那拳头深深的打破了装甲.里面的成员被打成了肉渣”–摘自美军陆战师汤米康林下士

“对不起,我只能回答你我不知道,因为这已经牵涉到国家最高机密”–城管队长回答记者关于城管训练问题

“在我军一次战役中,有一个阵地在郊外我军后方.我军已经突破了外围防线时,那个阵地已经被我们包围了.我们攻克了阵地.我们丢下了500具德意志勇士的尸体,以及3架F22和30台虎式坦克,但抵挡我们3天3夜的居然是5名城管.–摘自德军党卫军78师12团B连曼施坦因中尉

“我们的意志瞬间崩溃,只因为我们知道了对方军中有城管”–美国海军陆战队某指挥员

“配合粪青动员兵效果更好,那是条不可攻破的防线.那是条城管和粪青动员兵组成的钢铁长城.我在此警告各位议院,永远不要跟中国开战,因为中国有城管和粪青”–摘自美国总统奥八牛在珍珠港被3城管和粪青动员兵捣毁后的国会演讲

“当他们出现在战场中时,我知道,我们的末日来了”–前俄罗斯国防部长

“看到他们,我想不到其他的,脑子里只冒出两个字:超人”–前津巴布韦总理

“你一定没见过城管,如果见过,你不会这么完整的站在这里”——一名伤残美兵

“你肯定无法想象,我们一个陆战狙击手一不小心打了一个城管的手,那个城管居然一路杀过来干掉了他.但是…他来的时候已经打死200陆战队,掀翻了3个坦克外加5架武装直升机”–美国三角洲部队的教官

“城管?是撒旦征服世界军队吗?”–原美国炮兵团第二营幸存者

“我一直以为是铁血战士,直到有人告诉我那是城管,我见了城管执法,是的…我见过城管执法…”–美国扭腰精神创伤康复中心患者史密斯.W.布什

“我们的航母还在太平洋集结时,城管已经游过了太平洋占领了我们的首都”–一名美国海军的回忆

“如今能和我对抗的,只有城管.不过幸好,我们是同一阵线的”–摘自春哥自转<我是纯爷们>

“我一生中最大的悲哀就是从最后一场战争中幸存下来,在那次战争中战死沙场一直是我计划中的事,我真是应该在快结束的时候死掉,做为一个士兵能死在城管的手中,是最光荣的牺牲.如果让我选择,我一定会放弃现在的身份,选择做一名城管”–美国总统奥特曼

“我是城管”–人民的好英雄墓碑词.

“当年日本向我们申请核保护的时候,中国就开始组建城管了.可见我们现在的选择没有错,如果一但因为日本而对中国使用了核威胁,那我们将面临更大的灾难”—美国外交部发言人

“我们是人,是的,我们是人”–城管大队答记者问

“我想,他们能徒手搏杀掉上帝”–原美军陆战队73师师长耐肯

“和这样的军队作战是天大的错误”–拿破仑

“呕~他们打上来我们该怎么办?”-—上帝

“我们在一个错误的时间在一个错误的地点和一个错误的人打了一场错误的战争,因为我们没想到对方竟是中国城管”–美军司令兵败棒子国后如是说

“中国城管与核武器轰炸,我选择后者”–日本广岛原子弹轰炸幸存者

“天啊!饶了我吧!我不想面对他们,他们是来自地狱的恶魔.不!和他们相比我情愿面对恶魔!要知道他们可是城管!–美黑人逃兵威尔.修斯

“宇宙已经没有可以打败他们的人了”–M78星云总指挥官烧饼凹凸曼

“他们已经超越了人类想象的极限”–中情局局长罗布斯

“为什么现在美国人都不知道中国城管是什么东西,因为当你门知道它是什么东西的时候,你就会象我一样永远看不到明天的太阳!!”–一群在韩战里的被包围的独立师的最后消息

“鉴于中国城管具有超过核武器的威力,我们决定签订<城管不扩散条约>,并且保证当别人不使用核武器的时候我们不会优先派出城管”–人代表大会一致通过

“由于中国城管的存在我们放弃了进攻地球”–火星国防部长

“如果给我三个城管,我将平息非洲战乱,可惜我只有半个城管…”–联合国秘书长


--------------------

*今天，我查分了，451分*

昨天当我颤抖的双手拨通了北京市高考分数查询系统的时候，我听到了一个女人的声音：451分，当时我委屈的双眼充满了泪水，电话脱手了，狠狠的砸到了我的弟弟，我都没有感觉。

想想，我平时除了上网玩游戏，看点成人片，之外也不谈恋爱，偶尔出去玩，怎么考得这样差呢，平时摸底都是500多分啊，尽管考试纪律不严，但是也充分体现了我的水平啊… …

下午，家人问我考试查分数了吗？我手握着鼠标，头都没回的说道：还没下来呢！

晚上，我隔壁的那个2蛋–平时大家这样叫他的，他爹到我家来玩麻将，说他孩子下午查了分数竟然考了480分，我爸爸捏着二万说道：这不可能吧，这孩子平时摸底不是考的很差吗？听我孩子说也就是4百7左右的样子，冒泡了啊！这分数能上北大了吧！“可不是吗，我老家山东有个亲戚家孩子，考了700分，说只能上二等本科，说要复习去呢，咱北京就是强啊，这就是素质教育！”二蛋他爹弹了弹烟灰满脸自得的说。

哪壶不开提哪壶，2蛋他爹忽然问道：你家孩子考多少分啊？

我赶紧关闭游戏程序，在房间里拨通查询系统，按步骤输入着，然后装作从房间里面出来，说了声：爸，别玩了，我考试成绩出来了。大家都把专注的眼睛投向了我。

451分！我如实地说！没发挥好！

孩子你再查一遍，我爸说道。

我说：不用查了，我都查了N遍了，那个女的还是那样说~~~~~

二蛋他爹安慰我爸说：没事，这可以上清华了，不上北大没关系的~~~~

全家人都笑了。

晚上他们喝酒喝得很晚。

--------------------

大学的时候，刚进学校。学校让我们填一份自我简介，里面包括体育强项。同桌告诉我不要写那种运动会用的到的项目，不然以后运动会会强迫你参加。于是我们写的是高尔夫、网球、滑雪之类的，本想转过身去提醒后面玩的好的男生，结果一看他写的体育强项是双脚踩灯泡、胸口碎大石。

--------------------

刚才有人给我说：如果给我配一个技术大牛，+ 产品经理，+ 营销总监，+ 运营总监 我就可以创业了。我问，配了这些人以后，还要你干嘛？

--------------------

买了瓶饮料打不开盖子，想随便找个路人开开，但是不好意思，于是冲向了警察叔叔，叔叔一脸惊喜地刚说：谢……我说能不能帮我拧开瓶盖！事成之后我谢谢走了，好像听到心碎的声音 ~

--------------------

祝贺张学友郭富城获得奥运会羽毛球男双金牌(蔡赟/傅海峰)

file:../images/zhangxueyou-guofucheng-olympic-champion.jpg

--------------------

有人喜欢牌子，所以选择了苹果，有人喜欢外观，所以选择了索爱，有人喜欢比硬件，所以选择了三星，有人喜欢性价比，所以选择了小米，有人喜欢从众，所以选择了htc，但有些人还是执迷不悟，所以选择了诺基亚。有人喜欢最炫民族风，所以选择了山寨机。。。

--------------------

乘务员：“先生，飞机马上起飞了，请把手机关掉，好吗？” 乘客：“我开的飞行模式” 乘务员：“对不起先生，现在山寨手机也很多，我们很难保证每个手机都是符合标准的！” F舱乘客大怒，“你说啥？你说俺手机山寨的？老子是苹果的！三卡三待呢！不识货别跟老子吵！”

--------------------

突然听到解说员说“这是一名92年出生的老将。”顿时感觉这个世界太特么凶残了。

--------------------

1思想就像内裤，要有，但不能逢人就证明你有。2我可以选择放弃，但绝不放弃选择。3君子报仇，十年不晚。小人报仇，从早到晚。4我们需要马桶精神，按一下，什么都干净了。5人家有背景，而我只有背影。6眉毛上的汗水，眉毛下的泪水，你总得选一样。7财富改变不了个性，却能让人露出本性。

--------------------

王海滨：到北大读书后，雷声整个人的精神气质有了提升，这对于一个剑客非常重要。雷声：其实北大真正的作用是帮我突破了一个技术瓶颈。记者：噢？雷声：以前我一直解决不了出剑时手腕抖动的技术问题，甚至想到了退役，直到有一天我观察到了北大学一食堂打菜师傅是怎么用勺子的....

--------------------

file:../images/company-architecture.jpg

-----

和妹子相处，要义就是： 若她涉世未深，就带她看尽人间繁华； 若她心已沧桑，就带她坐旋转木马。和阿哥相处，要义是：若他情窦初开，你就宽衣解带；如他阅人无数，你就灶边炉台。

-----

培训的时候听上级领导说，全国党员有8000多万，而全世界超过8000万人口的国家不过14个。俺就在想，要是让全体党员随便割据个地方，从中国独立出去，组建一个国家，8000万最先进的人都保持同一信仰信念，没有不明真相的群众干扰建设，没有杂音和不良思潮，世界上第一个共产主义国家不就诞生了么

-----

什么是球星效应？ ——齐达内退休了，法国低迷了6年，这就是球星效应 ——普斯卡什退休了，匈牙利低迷了60年，这就是球星效应 ——高俅退休了，中国低迷了1000年，这就是球星效应

-----

自从我国引入劫持人质现场谈判专家制度，劫匪被击毙的几率反而提高。专家们把现场谈判的录音拿来研究，发现总是到这一句时谈判宣告破裂：“你一定要相信党和政府。”

-----

中午吃饭，旁边一桌的大姐结完帐说：＂开张发票，中国人民银行。＂服务员说：＂您写一下。＂大姐答：＂照钱上面写。＂

-----

【一个男人的称号】“伟大领袖”、“天赐大将军”、“世界著名的文学家”、“我们星球的卫士”、“所有杰出将军中最杰出的将军”、“众神之神”、“21世纪的北极星”、“一位拥有百科全书一样丰富知识”的“哲学巨人”、“人类最伟大的音乐天才”、“人类智慧的化身”。

file:../images/great-general.jpg

-----

如果你在澳大利亚电子产品Kogan的网站上进行网购的话,使用IE7的用户们可能会惊喜地发现他们需要你多付6.8%钱.收钱理由:我们费了这么大工夫让网站在IE7下看起来和其它浏览器的效果一样,你们理应付给我们辛苦费.PS:建议IE6收更多费用,解放前端码农,不用在去做无用的大量的Css Hack工作.

-----

file:../images/dont-think-yourself-as-an-ugly-person.jpg

--------------------

“麻麻为什么金牌和铜牌待遇差这么多？”“孩子，你知道世界第一高峰么？”“恩，珠穆朗玛峰嘛。”“那世界第三高峰呢？”“干城章嘉峰啊，麻麻我们不要讨论这个问题了，继续讨论金牌和铜牌的事情啊。”“。。。我没什么可说的，让你整天看那些没用的地理书。。”

--------------------

一人到精神病院送东西，刚到医院，车胎爆了。下车修理一不留神，车胎上的四个螺丝滚到下水道里，他在那儿干着急。一个精神病路过看了看：你把剩下3个轮胎，各拔1个螺丝下来，装到备胎上，然后把车慢慢开到市区，找家修车的不就行了。车主问他，你不是精神病么？精神病说——我是有精神病，但不是傻子。

--------------------

 绝妙的真的假新闻：勃列尼涅夫走路快，每每和来访的外国领导人比赛。一次和尼克松举行竞走比赛，结果，勃输了。但《真理报》（这名字！）的报道却是：在昨日美苏举行的一场竞走比赛中，我国领导人勃烈日涅夫同志获得了第二名的好成绩，而美国领导人尼克松获得了倒数第二名。这就是某些国家的文风啊。

----------

中国人就是牛，拿下“首金”“首铜”，让别人“首银”去吧。。。。

----------

我这人脾气好，每次和讨厌的人说话，总是面带笑容，默默的用中指的推推眼镜…

file:../images/smile-and-middle-finger.jpg

----------

一个设计师独白：甲方虐我千百遍，我待甲方如初恋。有朝一日做甲方，虐遍天下设计院。。。

----------

在开幕式演唱红歌 hey 朱德 引发极大反响之后，博伊尔已经决定闭幕式压轴曲目由大卫鲍伊演唱 shopping for girls （小平为女孩），旨在向另一伟大的中国领袖致敬，感谢他带领中国结束革命年代转型世俗社会、并为世界最具潜力经济体融入全球市场打下基础。

----------

伦敦奥运开幕式选用红歌《hey，朱德》作为压轴歌曲，引发热议。据导演介绍，这一选择有深意，该歌曲是由同情革命的披头士乐队于1968年所作，其中有“hey，朱德，don't make it bad”的歌词。当时，中国文革刚刚开始，词作者向中国隐晦喊话，寄望地位较高的元帅朱德勇于担当，出面阻止乱象。

----------

同时也有历史学家提出不同意见，认为这首歌实际反映了初上井冈山时的真实革命状况：革命队伍草创薄弱，反动派步步紧逼，袁文才等匪气未脱，部分指战员包括朱德同志在内，对革命前景一时有所悲观，此时毛委员展现了一位革命家的高瞻远瞩和大无畏精神，他表示：hey，朱德，don't make it bad

----------

寝室有一同学去厕所，玩手机不小心把手机掉下去了，然后，就回去拿了双筷子准备夹出来，正当他要下筷子捞时，一哥们进了厕所看到此景，那人关心地问道：“哥们，还没吃啊”

----------

程序猿问科比：“科比，你为何如此成功？”科比反问：“你知道洛杉矶每天凌晨4点的样子吗？”程序猿：“知道，那个时候我一般还没下班。你问这个干嘛？”科比：“不干嘛，草！”谈话结束了！

----------

因为有前科，都可以预计接下来会发生什么：1、煽情，着力宣传暴雨中的感人事迹，顺杆上升为北京精神2、各路马后炮砖家，大谈城市规划3、官员强调并非ZF不作为或乱作为，实乃天意，61年罕见才会至此4、表决心，谈整改，新闻稿最后一句肯定是“让我们拭目以待”，再一次出现类似情况，前面四点依次循环

----------

某种程度上来说，运动员比小姐都可怜，同样是生计所迫，年纪轻轻开始透支身体，小姐起码是卖，一次一结账，旱涝保收，而运动员则是去赌， 拿到冠军你就牛逼了，拿不到冠军你就歇逼了。更倒霉的是小姐收了钱不用被央视记者问脑残问题，也不用跟谁感恩戴德，运动员就不行，谢错顺序还他妈挨骂。

----------

一女吊丝签名：多年之后，你若娶了，我若没嫁。叫你儿子放学路上小心点。。。

----------

现在小学三年级的暑假作业真难啊，昨天看到侄子的暑假作业有一题什么逻辑规律题，哥想了半天都想不出来，求各位大神解答：986F、875E、764D、653C、--、431A，请问--处应该填什么呢？真心求解答

----------

去停车场取车，发现车头灯被人撞坏了！而且还有不少划伤！附近没见肇事车辆！但是还好，雨刷下压着一张纸条，是肇事着留下的。我拿起来，见上面写着：“抱歉，倒车时不小心撞了你的车灯，现场目睹的人看到我留这张字条时都对我点头面露微笑，他们以为我在写姓名和电话号码给你，可是我没有。

----------

在办公室接待应聘者，拿着那登记表，瞅了好久，弱弱地问：木棍？你叫木棍？那求职者脸都绿了，恶狠狠地回：我叫林昆！然后整个办公室3秒内一片静寂......接着狂笑不止.....

----------

他出身大户门第，身价数十亿，本应是娶女星玩模特的年纪，但是为了自己的信仰，他把数十亿换成了AK47和RPG，钻进了山洞对抗美帝主义，十年来让FBI和CIA颜面扫地，现在评说他是好坏已经没有意义，不过，他的一生注定是个 legend——传奇!—TO: Osama Bin Laden 本·拉登！ 
