* movie
** list
*** 听说看了这20部电影相当于读完清华大学经济管理学院
在复杂的商业社会，你想创业，不懂经济、不懂商业、不懂人情世故、不懂法律边沿，你只有勇气、只有梦想、只有天真，那么也就只有一场空。这20部电影都是商学院学生在学习商科时被要求必须看的影片，其中包括哈佛商学院一直首推的《华尔街》，还有沃顿商学院排第一位的《颠倒乾坤》，斯坦福要求商科学生必看的《锅炉房》。看完之后，你会对商业运行的本质和规则有更深入的了解，对你的职场生涯亦会有不小的帮助。

1.《华尔街》（Wall Street）（1987）

内部交易是违法的，不违法怎么能够发财，关键看如何违法的同时可以掩盖。不看这个影片怎么能够随便进入股市？

2.《拜金一族》（Glengarry Glenn Ross）（1992）

当房地产进入萧条的时候，美国房屋中介的销售顾问都在忙什么？看他们如何利用数据库，如何门到门地将房地产销售出去，如何在萧条期包装房地产，如何瞄准新婚家庭的住房需求。

3.《颠倒乾坤》（Trading Places）（1983）

经济是交易行为的代名词。只要有交易，就需要学会评估交易是否合算，就需要透视交易对方内心的秘密。交易中学到的核心法则，在世界上任何国家只要有交易的地方都适用。

4.《锅炉房》（Boiler Room）（2000）

难以想象的是违法交易几乎与证券市场形影不离。一个19岁的年轻人如此近距离地目睹财富的操纵过程，让谁富有，那不过是一个随机的选择。

5.《硅谷传奇》（Pirates of Silicon Valley）（1999）


比尔&#8226;盖茨与斯蒂夫&#8226;乔布斯几乎在所有方面的看法、观点都是对立的，他们只有在一个事情上是共同的，那就是尽一切可能封杀这个影片。硅谷的高科技公司是如何孵化的？不到25岁的年轻人利用了什么样的市场规则，又是如何让市场规则、让客户、让竞争对手形成一个共同体的？层出不穷的阴谋笼罩在硅谷的上空。

6.《可口可乐小子》（The Coca—Cola Kid）（1985）


这是一个男孩用可乐创造一项事业的故事。作为一个碳酸饮料的营销从业员，他不得不回答一个问题，在边远的澳大利亚小镇，为什么没有一瓶可口可乐？营销是生意不可或缺的部分，尤其是在创业中不可缺少。

7.《发达之路》（The Secret of My Success）（1987）

主要讲述了美国堪萨斯的男孩在纽约飘荡的历程。如果纽约可以代表近100年人类商业活动的中心，那么，任何21世纪的年轻人，都不得不面对大城市的浮华、喧嚣和躁动。

8.《优势合作》（In Good Company）（2004）

大公司都是通过收购长大的，你会收购吗？知道收购后销售主管是怎么想的吗？知道销售人员背后议论什么吗？联想收购IBM失败的核心因素就是根本没有看懂这个影片。当公司与公司之间发生买卖的时候，作为公司一员的你，位置在哪里？

9.《巴塞罗那》（Barcelona）（1994）

美国人的销售方式真的可以通行全球吗？一个美国销售员在西班牙的销售经历让我们学到销售的价值观，销售对客户文化的处理方式，销售对客户关系的把握。

10.《甜心先生》（Jerry Maguire）（1996）

做生意要拿出诚意来。show me the money，让我看到钱才是真的，任何生意都如此。生意中没有牢靠的友谊，这是你在创业前必须要牢记的教训。

11.《上班一条虫》（Office Space）（1999）

办公室政治课实战教材。在市场经济环境中当公司遇到危机时，裁员的本质动机，员工对公司的作用的核心意义都是必须要学习的商业社会的基本规则。

12.《解构企业》（The Corporation）（2003）

18世纪美国法律正式通过了一个企业可以是一个个人的组织行为后，仅仅两个多世纪，美国的这个公司法居然影响了全球，你可以在中国的公司法中也看到类似的描述。这个冠之以法人的称号横行全球，世界每一个角度都受到影响。个人的贪婪、个人的欲望没有止境地膨胀，本片从最深刻的本质揭示了资本主义商业规则，并无情地揭示了其存在的弊病。

13.《惊爆内幕》（The Insider）（1999）

商业社会的本质是货币自由交换，只要你情我愿，似乎交换什么都可以。交易中的商业价值，交易中的定价原理，商业信誉在交易中的作用都是这个影片中活生生地展示出来的，商科学生必须要理解金钱统治人类社会的必然结果，以及这种结果具备的不可逆的特性。

14.《影子大亨》（The Hudsucker Proxy）（1994）

一部票房不怎么样、但懂商业的人却说好的影片。一个公司的老板自杀了，但其公司还蒸蒸日上，董事会的实权人物开始行动，行动的目的当然是私欲横流。公司治理、企业董事会操作实战等都是这部影片中不可多得的实战教案。

15.《反垄断》（Antitrust）（2001）

一个斯坦福的电脑天才毕业后被科技大亨录用后负责发展全球通信系统，之后他发现原来自己是被用作侦察商业对手以达到垄断市场的目的。此片向微软的垄断幽了一默，讲述了一个有鲜明时代和全球意义的反对金钱和高科技垄断的故事。

16.《魔鬼营业员》（Rogue Trader）（1998）

1995年，巴林银行，这家全球最古老的银行之一破产了，曾经是英国贵族最为信赖的金融机构，拥有200多年优异的经营历史，却没能逃过破产的结局。令人震惊的是，这样一个惨痛的结局，却出自于一个普通的证券交易员尼克&#8226;李森之手。这部出自真实案例的电影是大家学习银行业务，尤其是投资业务最好的教案。

17.《抢钱世界》（Other People's Money）（1991）

这也是一部基于美国真实故事改编的影片，从中可以了解商业法、企业兼并、商业诉讼规范、商业流程、兼并重组流程等。美国商业自由市场中到处充满了利己行为与利他行为的冲突和矛盾，也恰好是从这些冲突和矛盾中可以学到不同的动机，以及各种让人眼花缭乱的手段。

18.《败露》（Disclosure）（1994）

一位踌躇满志的公司高管在一天中，不仅失去了原应属于自己的晋升机会，而且迎来了自己10年前的同居女友担任顶头上司。已有妻儿的他拒绝了女上司与他重温旧梦的要求，于是，女上司耍出种种手腕在公司中排挤他，甚至诬称他对自己性骚扰。忍无可忍的他诉诸法律，在一位精明女律师的帮助下，与公司及那位霸道的女上司展开了较量……片中体现的办公室政治、公司群体人际关系行为准则等都是难得的职场教材。

19.《男人百分百》（What Women Want）（2000）


一个小小的意外，让主角具备了能够阅读女性头脑的能力，这是一部用巧妙的方式揭示女性所思所想的影片。商业心理学、女性行为学、广告学等都是这部影片中可学习的亮点。

20.《门口的野蛮人》（Barbarians At The Gate）（1993）

1988年，KKR公司收购雷诺-纳贝斯克公司是华尔街震惊全球的重大金融事件。专业人士事后分析，这桩交易是在合法基础上的骗局。因为KKR公司用的杠杆收购手法不仅不需要现金，也不需要看见现金，甚至也没有人知道钱从哪里来，整个过程根本就是个圈套。而KKR那些高层，以及交易过程中的那些华尔街人士，由于表现出了前所未有的贪婪和狡猾的技巧，也被冠以“野蛮人”的称号 

*** 十三部公认的高境界电影
　No.1穆赫兰道

　　《穆赫兰道》可以算是每个悬疑片爱好者必观影片。和很多悬疑片一样，电影开头都有很不起眼的细节提示，但本片的细节提示可以算是技术含量最高的了——就是那一个谁也不会注意到的细节，竟然是全片的最重要的地方，这个细节还让我想起了爱因斯坦曾说过的一句话：“第一句话错误，整个假设失败。”(不能说太多了)而且这部电影也不是普通的在情节上或结局上让人感觉不可思议，它更是一种学术上的严肃的研究，关于梦境。这在我看来，确是大卫林奇最好的电影。

　No.2 电锯惊魂1

　　要论结局最让人震惊是，《电锯惊魂》以绝对优势当选。最开始我是以为这是恐怖片，但实际上这并不是恐怖片。反而我们能看见John作为一个“痛恨杀人犯”的杀人犯的用心良苦，在这一点上，毋宁说他是一个拯救者。后面几部也还不错，但明显逊于1。

No.3 恐怖游轮

　　杰西游艇出海游玩，但她总有一种有不好的事情发生的感觉。果然，游艇遇到了风暴，于是所有人只好换乘了一辆刚好路过的大游轮来保证安全。可是洁西深信她曾乘坐过这辆大游轮，船上的钟突然停止了，一些恐怖的事情接踵而至……

　　《恐怖游轮》是所有悬疑片中情节最复杂的，但又似乎有一个很清晰的思路。在看它的过程中，你的大脑不得不飞速运转，才能理清全片的结构。

　No.4 致命魔术

　　《致命魔术》，2007上映的美国电影。其讲述的是在魔术产生盛行的维多利亚时期，出现了两位极有天赋的年轻魔术师、两个好朋友，罗伯特·安吉尔和阿尔弗雷德·波登。两个人因为互相嫉妒猜疑，而成了势不两立的对手，他们用各种方法来证明自己是那个时代的第一魔术师的故事。

　　《致命魔术》的结局很有震撼力，一开始还真想不到。但其实片中很多地方都揭示了这个结局，但也许由于一种惰性吧，也没多想。所以大家看悬疑片还是要多想想。

　NO.5 万能钥匙

　　年轻的姑娘卡罗琳(凯特•哈德森 Kate Hudson 饰)受雇于老妇人维奥莱特(吉娜•罗兰兹 Gena Rowlands 饰)，前往她家照顾她卧病在床的丈夫本(约翰•赫特 John Hurt 饰)。维奥莱特的大房子坐落于以神秘习俗和宗教仪式闻名的地区，卡罗琳刚到这里就觉得阴森诡异。随着日子一天天过去，卡罗琳渐渐对这件大房子和古怪的维奥莱特起疑。一次偶然，她从维奥莱特那里得到了一把万能钥匙，用它可以打开这座大房子的所有房间。当卡罗琳走进了隐藏在顶楼的房间时，她看到了令人惊悚的一幕，直觉告诉她，本的卧病在床和维奥莱特以及这间房间有着莫大的关系，她决心揭开这个迷!

　　《万能钥匙》，如果没有这个结局，那么这其实是个挺俗套的故事，但只要你看了结局你是绝对不会后的。

NO.6 死亡幻觉

　　《死亡幻觉》(Donnie Darko)是一部2001年推出的美国心理惊悚、科幻电影，由理查·凯利(Richard Kelly)编剧和执导。故事叙述一位名叫东尼·达克(Donnie Darko，与电影原文标题相同)的青少年，在一个拟人化兔子的怂恿下，做出一些为了要终结世界的破坏行为。本片在美国上映时票房不尽理想，但在DVD租售市场却表现相当优异，目前被认为是一部另类经典作品(cult classic)。

　No.7 致命ID

　　惊悚剧情类型的电影看多了，《致命ID》当之无愧是其中最好的，总之，看本片心情是相当的纠结：从肯定A是凶手到肯定B是凶手到肯定C是凶手到肯定D…最后不知道谁是凶手，最后的最后以为就是那样了，最后的最后的最后又再一次深深的震惊了。

NO.8 记忆碎片

　　《记忆碎片》注定不是一般的作品，电影故事其实不太复杂，但很难看懂，这是由于它采用两条平行故事线，一条倒叙，以彩色呈现，另一条顺叙，以黑白呈现，两条线每隔几分钟穿插一次，直至片尾天衣无缝地与片头衔接在一起(观看者可注意何时衔接到了一起)。

　NO.9 十二宫

　　大卫·芬奇的《十二宫》完美地描述出来一场让人惊恐的心理战，对手则是美国历史上最聪明、最难以捉摸的系列杀人犯。

　NO.10 停留

　　《停留》是一部需要仔细斟酌的影片，每字每句，每事每物.哪怕你有一点的大意便会失去感觉，不知其意.影片中更多的运用了暗示，铺垫等表达手法.在影片结束的刹那一切谜底都被揭开，而新的迷团又马上降临了。

　NO.11 七宗罪

　　《七宗罪》：凶手宣称自己的“伟大杰作”仍会完成，在警方的严密看管下，插翅难飞的杀人犯又能做什么呢?结局大大出乎人的意料。

　NO.12 搏击俱乐部

　　《搏击俱乐部》：人性的黑暗与压抑，充满暴力的拍摄镜头，过程时时震撼人心，直到最后一刻，所有谜底揭开，你才知道这是一个多么大的骗局。

　NO.13 禁闭岛

　　《禁闭岛》：小岛关押着精神病患者，一名高智商调查员，想要揭开岛上人体实验的黑暗内幕，却难以想象自己原来是...


