* swap
** java
   - 日志,log4j
   - 泛型 
   - 容器 
   - 多线程

** hadoop
存在两套API，现在比较推荐使用mapreduce而非mapred名字空间下面的类，现在mapreduce下面的类使用起来更加简单。

hbase支持increment http://hbase.apache.org/apidocs/org/apache/hadoop/hbase/client/Increment.html

** 婚礼喜钱
   - 张闻宇 400
   - 九震 400
   - 金葛+上官 1000
   - 黄学超 800
   - 姜悦 400
   - 李正 400
   - 熊春斌 1000
   - 李海峰 400
   - 王智慧 400
   - 任传永 400
   - 张林娟 600
   - 边志华 600
   - 其余人 400

** 老婆事情
   - 3个月增添化妆品大件，2011.07.11
   - 6个月换发型，2011.07.11
   - 太阳镜
   - 衣柜
   - 鞋柜
   - 首饰箱
   - 克丽缇娜碧泉SPA时尚馆
   - DQ和哈根达斯
   - 买首饰
   - 泡温泉

** 水管
UPVC 管：实际上就是一种塑料管，接口处一般用胶粘接，UPVC 管的抗冻和耐热 能力都不好，所以很难用作热水管，由于其强度不能适用于水管的承压要求，所以冷水管也 很少使用。大部分情况下，PVC 管适用于电线管道和排污管道。另外，近年内科技界发现， 能使 PVC 变得更为柔软的化学添加剂酞，对人体内肾、肝、睾丸影响甚大，会导致癌症、 肾损坏，破坏人体功能再造系统，影响发育。所以建议大家不要购买。

镀锌管：老房子大部分用的都是镀锌管，现在煤气、暖气用的那种铁管也是镀锌管， 镀锌管作为水管，使用几年后，管内产生大量锈垢，流出的黄水不仅污染洁具，而且夹杂着 不光滑内壁滋生的细菌， 锈蚀造成水中重金属含量过高， 严重危害人体的健康。 六七十年代， 国际上发达国家开始开发新型管材， 并陆续禁用镀锌管。 中国建设部等四部委也发文明确从 二 000 年起禁用镀锌管，目前新建小区的冷水管已经很少使用镀锌管了，有些小区的热水 管使用的是镀锌管。

铝塑管：铝塑复合管是市面上较为流行的一种管材，目前市场比较有名的有日丰和 金德，由于其质轻、耐用而且施工方便，其可弯曲性更适合在家装中使用。其主要缺点是在 用作热水管使用时， 由于长期的热胀冷缩会造成管壁错位以致造成渗漏。 北京很多小区使用 的是铝塑管，在装修理念比较新的广东和上海，铝塑管已经渐渐的没有了市场，目前铝塑管 在北京市场还比较活跃，相信在不久的将来，北京市场铝塑管也会面临淘汰。

PPR 管：作为一种新型的水管材料，PPR 水管具有得天独厚的优势，它既可以用作冷水 管，也可以用作热水管，由于其无毒、质轻、耐压、耐腐蚀，正在成为一种推广的材料，目 前北京装修工程中选用的还比较少，PPR 管不仅适用于冷水管道，也适用于热水管道，甚 至纯净饮用水管道。PPR 管的接口采用热熔技术，管子之间完全融合到了一起，所以一旦 安装打压测试通过， 不会象铝塑管一样存在时间长了老化漏水现象， 而且 PPR 管不会结垢， 目前北京的一些高档住宅和公寓普遍采用 PPR 水管作为冷水管和热水管， PPR 管号称永不 结垢、永不生锈、永不渗漏、绿色高级给水材料。

铜管：铜管具有耐腐蚀，消菌等优点，是水管中的上等品，铜管接口的方式有卡套 和焊接两种，卡套跟铝塑管一样，长时间存在老化漏水的问题，所以在上海等地，安装铜管 的用户大部分采用焊接式，焊接就是接口处通过氧焊接到一起，这样就能够跟 PPR 水管一 样，永不渗漏，铜管的一个缺点是导热快，所以有名的上海三净、宝洋等铜管厂商生产的热 水管外面都覆有防止热量散发的塑料和发泡剂， 铜管的另一个缺点就是价格贵， 极少有小区 的供水系统是铜管的，恐怕只有在外销公寓和高档别墅里才会看到。如果你打算换水管，又 觉得铜管不错的话， 建议一定要采用焊接的接口方式。 有网友提到东方家园西三旗店有英国 IBP 的铜管，我没有用过，大家可以去考察。

不锈钢管：属于非常贵的水管，施工困难，很少被采用，性能与铜管类似。

4、 埋在墙里的水管部分千万不要有接头， 一定要是一根完整的管子， 不要省这点钱。 不要将水管埋在地下，宁可费点管从吊顶里通过，也不要放到地下。
5、水管安装完成之后一定要打压测试，如果你找的安装工人不能做这件事，你要小 心了，他们的安装可能会有问题。
6、安装完成后一定要索取质保书。 
7、 不建议找装修公司做水管， 太贵， 一般的铝塑管都要几十元每米， PPR 要近百元， 建议直接找水管安装队伍不但专业而且负责墙面开槽，所以算下来不是很贵，一般 PPR 下 来也就千元左右，铜管 2000 左右.

http://bjjc.zhcoo.com/show_manage_article.aspx?articleid=9120
【宝胜】【鲁能泰山】【远东】【胜华电缆】【上上】【亨通光电】【熊猫电线】【耐克森】【五彩江南】【日辉-阳谷电缆】

1.金德 2.伟星 3.金牛角 4.星德 5.白蝶 )6.日丰 7.联塑 8.中财 9.皮尔萨 10.爱康-保利


** temp
处理到 http://dirlt.com/blog/?paged=30

** hadoop-lzo
#+BEGIN_EXAMPLE
https://github.com/kevinweil/hadoop-lzo
安装liblzo2库，sudo apt-get install liblzo2-2(liblzo2-dev)
安装lzop程序，sudo apt-get install lzop
clone git://github.com/kevinweil/hadoop-lzo.git
编译，ant compile-native tar 将结果build/hadoop-lzo-0.4.14的hadoop-lzo-0.4.14.jar复制到 $HADOOP_HOME/lib，将build/hadoop-lzo-0.4.14/lib/native下的文件复制到$HADOOP_HOME/lib/native (native/Linux-amd64-64)
修改core-site.xml配置
<property>

<name>io.compression.codecs</name>    <value>org.apache.hadoop.io.compress.GzipCodec,org.apache.hadoop.io.compress.DefaultCodec,com.hadoop.compression.lzo.LzoCodec,com.hadoop.compression.lzo.LzopCodec,org.apache.hadoop.io.compress.BZip2Codec</value>
</property>
<property>

<name>io.compression.codec.lzo.class</name>

<value>com.hadoop.compression.lzo.LzoCodec</value>
</property>

#+END_EXAMPLE

