#!/usr/bin/env python
#coding:utf-8
#Copyright (C) dirlt

from dsgm import DSGM
import sys

def usage():
    sys.stderr.write("""Documentation Synchronize based on Google Mail. http://dirlt.com/dsgm.html
usage:
  dsgm help // help information
  dsgm pull // pull gmail to local
  dsgm push // push local to gmail
  dsgm // dsgm pull + dsgm push
""")

def main():
    if(len(sys.argv)>2):
        usage()
        sys.exit(-1)

    arg=None
    if(len(sys.argv)==2):
        arg=sys.argv[1]
    
    if(arg=='help'):
        usage()
        sys.exit(0)

    d=DSGM()
    d.open()
    
    uids=d.pullUids()
    d.pullSubjectsAndUpdateToDB(uids)
    info=d.constructLocalDirectoryInfo()

    if(arg=='pull'):
        d.pull(info)
    elif(arg=='push'):
        d.push(info)
    else:
        d.pull(info)
        d.push(info)
    
    d.close()

if __name__=='__main__':
    main()
